== Introduction

=== Intent of This Document

Automotive CAN, LIN, FlexRay, CAN FD, CAN XL and Ethernet are network technologies that have been applied successfully over many years by all automotive OEMs world wide.
Virtualizing electronic control units (ECUs) and then simulating multiple such virtual ECUs requires connecting them using a virtual version of these network technologies.

This layered standard defines what input and output variables and which FMI 3.0 features are used and how to emulate a transport layer for such network traffic.
At this point it should be explicitly mentioned that this layered standard not only relates to automotive buses, but can also be extended to buses from other domains in the future.

There are mainly two base use cases envisioned here:

* Physical signal abstraction ("high cut") to simply transport physical signal values between virtual ECUs. +
The network properties are largely idealized: infinite bandwidth, zero-delay etc.
Signals, groups of signals and their properties _(e.g., units)_ are usually derived from (existing and validated) standard network topology description formats _(such as DBC, LDF, Fibex and ARXML)_.
* Network abstraction ("low cut") to realize virtualized bus driver implementations footnote:[In AUTOSAR context this means a driver implementation within the MicroController Abstraction Layer (MCAL)]. +
This transport layer emulation allows anything from idealized to more detailed network simulations, including bandwidth restrictions, message arbitration and delays.
It forwards the network payloads using binary variables.
The "low cut" abstraction layer is meant to allow virtualized bus driver implementations, including feedback from the physical drivers about transmission status or network node states.
Since the network abstraction layer is protocol-independent, it can also be used for the simulation of non-automotive control units, _e.g., from the field of industrial automation_.

So that this layered standard can be supported in a variety of FMU importers and other types of simulators three possible communication architectures for bus communication are specified:

* Direct Communication: Limited to exactly two FMUs, a common FMU importer that not require any special features for simulating buses, apart from supporting FMI variables, clocks and terminals can be use to emulate bus communication.
* Composition with dedicated Bus Simulation FMU: A separate Bus Simulation FMU is used to simulate the specific bus behavior.
Other FMUs that want to emulate bus communication provide and relate network information via this Bus Simulation FMU.
This communication architecture can be operated by a common FMU importer and allows complex and detailed bus simulations.
* Importer with Integrated Bus Simulation: Works analogously to the Composition with dedicated Bus Simulation FMU architecture, whereby the Bus Simulation FMU is directly integrated into an importer or other simulator.

=== How to Read This Document

Conventions used in this document:

 - Non-normative text is given in square brackets in italic font: _[Especially examples are defined in this style.]_
 - The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in <<RFC2119>> (regardless of formatting and capitalization).

=== Remarks

This layered standard currently only refers to the FMI for Co-Simulation (CS).
At the current time, Model Exchange (ME) and Scheduled Execution (SE) are not taken into account.
All explanations in this document are therefore to be understood in the context of FMI for Co-Simulation (CS).

== Layered Standard Manifest File

This layered standard defines requires the use of a layered standard manifest file and <<table-schema-fmi-ls-bus-attributes>> shows the content of `fmi-ls-manifest.xml`.

.Attribute Details.
[[table-schema-fmi-ls-bus-attributes]]
[cols="1,1,1,2",options="header"]
|====
|Attribute
|Namespace
|Value
|Description

|`fmi-ls-name`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `org.fmi-standard.fmi-ls-bus`
| Name of the layered standard in reverse domain name notation.

|`fmi-ls-version`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `1.0.0`
| Version of the layered standard. This layered standard uses semantic versioning, as defined in <<PW13>>.

|`fmi-ls-description`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `Layered Standard for the simulation of bus communication on a signal or network abstraction based level.`
| String with a brief description of the layered standard that is suitable for display to users.

|====

An example of a manifest file for this layered standard is shown below:

[source, xml]
----
include::examples/fmi_ls_bus_manifest_example.xml[]
----

The manifest file shall be stored inside the FMU at the following path: `/extra/org.fmi-standard.fmi-ls-bus/fmi-ls-manifest.xml`.
