== Introduction

=== Intent of This Document

Automotive CAN, LIN, FlexRay, CAN FD, CAN XL and Ethernet are network technologies that have been applied successfully over many years by all automotive OEMs world wide.
Virtualizing electronic control units (ECUs) and then simulating multiple such virtual ECUs requires connecting them using a virtual version of these network technologies.

This layered standard defines what input and output variables and which FMI 3.0 features are used and how to emulate a transport layer for such network traffic.

There are mainly two base use cases envisioned here:

* Physical signal abstraction ("high cut") to simply transport physical signal values between virtual ECUs. +
The network properties are largely idealized: infinite bandwidth, zero-delay etc.
Signals, groups of signals and their properties _(e.g. units)_ are usually derived from (existing and validated) standard network topology description formats _(such as DBC, LDF, Fibex and ARXML)_.
* Network abstraction ("low cut") to realize virtualized bus driver implementations footnote:[In AUTOSAR context this concrete means a driver implementation within the MicroController Abstraction Layer (MCAL)]. +
This transport layer emulation allows anything from idealized to more detailed network simulations, including bandwidth restrictions, message arbitration and delays.
It forwards the network payloads using binary variables.
The "low cut" abstraction layer is meant to allow virtualized bus driver implementations, including feedback from the physical drivers about transmission status or network node state.
Since the Network abstraction Layer is protocol-independent, it can also be used for the simulation of non-automotive control units, _e.g. from the field of industrial automation_.

In the simplest use case, the importer does not need provide specific bus semantics of certain variables of an FMU; it simply forwards variable values between 2 FMUs according to the FMI standard (<<multiOutput,with one exception noted at the end of the document>>).
Only when more than two FMUs are connected to a single network a bus simulation component is required to handle the bus communication between multiple senders and receivers according to the semantic of the selected bus type.

See the following image describing three potential architectures for connecting two or more networked virtual ECUs packaged into FMI 3.0 FMUs:

.Three ways to connect FMUs with bus support and network variables, for example virtual ECUs.
[#vECU-network-architectures]
image::architecture.svg[width=80%, align="center"]

=== How to Read This Document

Conventions used in this document:

 - Non-normative text is given in square brackets in italic font: _[Especially examples are defined in this style.]_
 - The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119 (regardless of formatting and capitalization).

=== Remarks

This layered standard currently only refers to the FMI Co-Simulation (CS).
At the current time, Scheduled Execution (SE) is not taken into account.
All explanations in this document are therefore to be understood in the context of FMI Co-Simulation (CS).

== Layered Standard Manifest File

This layered standard defines the required capability flags in the layered standard manifest file.
<<table-schema-fmi-ls-bus-attributes>> shows the content of `fmi-ls-manifest.xml`.

.`fmiLayeredStandardManifest` attribute details.
[[table-schema-fmi-ls-bus-attributes]]
[cols="1,1,1,2",options="header"]
|====
|Attribute
|Namespace
|Value
|Description

|`fmi-ls-name`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `org.fmi-standard.fmi-ls-bus`
| Name of the layered standard in reverse domain name notation.

|`fmi-ls-version`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `1.0.0`
| Version of the layered standard. This layered standard uses semantic versioning, as defined in <<PW13>>.

|`fmi-ls-description`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `Layered Standard for Bus`
| String with a brief description of the layered standard that is suitable for display to users.

|====

An example of a manifest file for this layered standard is shown below:

[source, xml]
----
include::examples/fmi_ls_bus_manifest_example.xml[]
----
