== Physical Signal Abstraction ("high cut")

=== Overview

Physical signal abstraction allows an idealized exchange of unit-based variables between FMUs.
In AUTOSAR, this would be equivalent to the Virtual Function Bus.
Variables are clocked to reflect the timing aspects of the information flow.
Changes to these clocked variables always reach the destination.

=== Variables

This section explains the different variable types used to carry network traffic through FMI input and output variables.

==== Signal Variables

To define the signal abstraction layer (or "high cut"), signal variables are defined.

A signal variable carries the physical value of a network signal normally packaged inside a PDU or frame.
The unit definition of the variable must match the one defined in the <<NetworkDescriptionFile>>, if provided.

Each network signal must be listed as <<TerminalMemberVariable>> of its corresponding <<PDUTerminal>>.

In case multiplexed signals are present in a frame/PDU/container PDU: all signals/PDUs are present, but only the active signal according to the multiplex switch signal contains a valid value, all inactive variables have undefined values _[those values could even be outside their specified min-max range without fault]_.

Generally, signal variables are optional, but they must either be all missing or all present to clearly indicate support for the signal abstraction layer.

All signal variables are clocked to exactly indicate when they have been sent, see <<ClockVariableHighCut>>.


==== Clock Variables [[ClockVariableHighCut]]
In order to use FMU input and output variables as transport layer for networks, input and output clocks are used.
Such a clock is scheduled by the sending FMU to indicate the transmission of the corresponding frame or frames.

The output clock type, periodic or aperiodic, is defined by the sending FMU.
This allows the FMU (or better the exporting tool) to balance the accuracy and performance of its network communication:

 - While aperiodic clocks allow very accurate network simulations, frequently entering Event Mode will reduce the network simulation speed.
 - Using periodic clocks reduces the number of Event Modes required and speeds up the simulation at the cost of simulation accuracy, because timing must be forced into a fixed grid and some intermediate values might not be transmitted.
 - One could use (structural) parameters to define the accuracy of aperiodic clocks, allowing control of the simulation accuracy and performance with the same FMU.
 - The input clocks shall be triggered clocks.

The importer will then connect and merge output clock activations, even those of different clock types, and forwards them to the input clocks, as required by the network semantics.

Signal variables belonging to frame `BusName::FrameName` are triggered by the clock `BusName::FrameName_Clock` and all these variables and their corresponding clock must share the same `causality` (`input` or `output`).

=== Network Description Files [[NetworkDescriptionFile,network description file]]

Standardized <<NetworkDescriptionFile,network description files>> may optionally be shipped with each FMU to describe properties of signals and frames, such as signal units, frame composition and trigger conditions.
If these <<NetworkDescriptionFile,network description files>> are shipped, they must be placed into the `/extra/org.fmi-standard.fmi-ls-bus` folder.
DBC, LDF, Fibex and ARXML files are allowed, e.g., `Powertrain.dbc`.
The case sensitive root name of the <<NetworkDescriptionFile>> must be used as network identifier in the bus terminal type and prefix in the variable names.

Multiple files can be specified, each one defining one network used by the FMU.
This standard does not support composing one network from multiple <<NetworkDescriptionFile,network description files>>, even if using internal include mechanisms, it rather enforces the rule: one network - one file.

It is recommended to use ARXML over DBC files for CAN whenever possible, because the DBC standard lacks some key frame/PDU properties that were added only later using non-standard extensions with different dialects in use.

This document does not address potential open points of these description formats, it is assumed that such ambiguities will be handled elsewhere (e.g., message timing in the DBC format).
This document does not address IP protection or copyright issues.
These are technical and legal issues that need attention from standardization bodies of the referenced description formats, tool vendors and end users.

=== Terminal Definitions

==== Bus Terminal [[BUSTerminalHighCut,bus terminal]]

Each network connected to the FMU must be described in `icons/terminalsAndIcons.xml` as a `<Terminal>` element of `<fmiTerminalsAndIcons><Terminals>` that wraps all <<FrameTerminal,frame terminals>>.
The attribute `name` of the `<Terminal>` must match the root name of its <<NetworkDescriptionFile>> if it exists
_[e.g., `Powertrain`, if the file is `/extra/org.fmi-standard.fmi-ls-bus/Powertrain.dbc`]_.
In any case, the attribute `name` of the `<Terminal>` must be consistent with the `BusName` component of all its corresponding signal, frame and clock variables.

Attribute definitions::
 * `terminalKind` must be set to `bus`.
 * `matchingRule` must be set to `bus`.
 * `name` is the network name, e.g., `Powertrain`, see <<ExampleHighCut>> and constraints above.

Element definitions::
 * There must be no `<TerminalStreamMemberVariable>` element.
 * There must be one `<Terminal>` element per network frame described in the <<NetworkDescriptionFile>>, if their signal and lock variables are present in the `modelDescription.xml`.

Annotation element::
 * There must be an `<Annotation>` element defining which node or nodes (as comma-separated list without spaces) of the <<NetworkDescriptionFile>> are wrapped inside the FMU.
If the combination of nodes specified for this FMU turns a frame and its signals into both input and output because sending and receiving nodes are specified, only the sending (output) role will be defined in the FMU interface.
Receiving such frames must then be handled internally to the FMU.

==== Frame Terminal [[FrameTerminal,frame terminal]]

Each frame listed in the <<NetworkDescriptionFile>> must be an element of its corresponding <<BUSTerminalHighCut>>.

Attribute definitions::
 * `terminalKind` must be set to `frame`.
 * `matchingRule` must be set to `bus`.
 * `name` must match the frame name as defined in the <<NetworkDescriptionFile>> in `/extra/org.fmi-standard.fmi-ls-bus`.

Element definitions::
 * There must be no `<TerminalStreamMemberVariable>` element.
 * There must be one <<PDUTerminal>> element per PDU of this frame.
 * There must be one `<TerminalMemberVariable>` for the clock this frame is connected to.
   The name of this variable is composed as <<ClockVariable,`BusName::FrameName_Clock`>>, e.g., `Powertrain::tcuSensors_Clock`.

The <<TerminalMemberVariable>> must have the same causality as all variables referenced in the <<PDUTerminal,PDU Terminals>> included here.

==== PDU Terminal [[PDUTerminal,PDU terminal]]

Each PDU listed in the <<NetworkDescriptionFile>> must be an element of its corresponding <<FrameTerminal>>.

Attribute definitions::
 * `terminalKind` must be set to `pdu`.
 * `matchingRule` must be set to `bus`.
 * `name` must match a PDU name of the <<NetworkDescriptionFile>> in `/extra/org.fmi-standard.fmi-ls-bus`, if given.
    For network types not natively referencing a "PDU", like CAN, a synthetic PDU with the same name as its frame is inserted.

Element definitions::
 * There must be no `<TerminalStreamMemberVariable>` element.
 * There must be no `<Terminal>` element.
 * There must be one `<TerminalMemberVariable>` per <<TerminalMemberVariable,signal>> of this PDU.

All <<TerminalMemberVariable,`TerminalMemberVariables`>> must have the same causality of either `input` or `output`.

==== Terminal Member Variable for Signals [[TerminalMemberVariable,Terminal Member Variable]]

<<PDUTerminal,PDU terminals>> list all the contained signals as `<TerminalMemberVariable>`.

Attribute definitions::
 * `variableName` refers to the input or output variable name of the FMU and to enforce uniqueness is built as follows: `BusName::FrameName::PDUName::SignalName`, e.g., `Powertrain::tcuSensors::tcuSensors::vCar`.
    These variables represent the signal abstraction layer ("high cut").
 * `memberName` is the `SignalName` as given in the <<NetworkDescriptionFile>>, e.g., `vCar`, if given.
    This is redundant information but simplifies signal name extraction.
 * `variableKind` is `signal`.

==== Example [[ExampleHighCut,ExampleHighCut]]

The following excerpts from files are used throughout this document as examples and should illustrate how the different concepts relate.

The following partial DBC file lists merely the CAN message (frame) structure.
Signal trigger conditions are not included because they have no bearing on this standard.

.Example Powertrain.dbc file
[#Powertrain.dbc]
[source, C]
----
...
BO_ 256 tcuSensors: 4 TCU
 SG_ vCar :          0|16@1- (32,0)  [-500|500] "km/h" ECU
 SG_ oilTemp :      16|9@1-  (2,50)  [-50|150]  "Degree C" ECU

BO_ 257 tcuState: 2 TCU
 SG_ state :         0|2@1+  (1,0)   [ 0|2] "-" ECU
 SG_ gear :          2|4@1-  (1,0)   [-2|6] "-" ECU
 SG_ targetGear :    6|4@1-  (1,0)   [-2|6] "-" ECU

BO_ 512 ecuState: 4 ECU
 SG_ accelPedal :    0|8@1+ (2,0)   [0|100]   "%" TCU
 SG_ k15 :           8|1@1+ (1,0)   [0|1]     "-" TCU
 SG_ oilTemp :       9|9@1- (2,50)  [-50|150] "Degree C" TCU
 SG_ radiatorTemp : 18|9@1- (2,50)  [-50|150] "Degree C" TCU
...
----

The `modelDescription.xml` excerpt listed below shows which variables would exist for the `Powertrain.dbc` shown above.

.Example modelDescription.xml for ECU node
[#modelDescriptionHighCut.xml]
[source, XML]
----
include::examples/X_network4FMI_modelDescription_highCut.xml[]
----

The following file shows the `<Terminal>` definition representing the network and frame structure defined with `Powertrain.dbc` above.

.Example terminalsAndIcons.xml file
[#terminalsAndIconHighCut.xml]
[source, XML]
----
include::examples/X_network4FMI_terminalsAndIcons_highCut.xml[]
----
