== Physical Signal Abstraction (High-Cut) [[high-cut]]
This chapter describes the Physical Signal Abstraction or High-Cut in detail.

=== Overview [[high-cut-overview]]
Physical Signal Abstraction allows an idealized exchange of unit-based variables between FMUs.
Variables representing these physical signals are clocked to reflect the bus timing aspects of the information flow.
Changes to these clocked variables always reach the destination.
An FMU can take on specific roles here.
This role can be a Bus Simulation FMU or an importer with bus simulation support on one side, and Network FMUs (e.g., virtual ECUs) on the other side (see <<common-concepts-system-compositions, System Compositions>>).
To allow importers an easy distinction between these FMU roles, for Bus Simulation FMUs the attribute `isBusSimulationFMU` shall be set to `true` in the Manifest file.

The figure below shows an example architecture of a Physical Signal Abstraction.
The signals (_Signal 1...8_) are modeled as clocked variables of a specific type.
The corresponding signals are structurally combined using Protocol Data Units (PDUs), which in turn are assigned to frames.
The PDU and frame structuring is done via terminals (_PDU A, B, C_ and _Frame X, Y_).
The respective variables are connected to a Bus Simulation, which emulates them according to their own needs for e.g. according to accuracy.

.Physical Signal Abstraction example architecture.
[#figure-transmission-high-cut-overview]
image::high_cut_network_fmu.svg[width=80%, align="center"]

=== Signal Variables [[high-cut-signal-variables]]
To define the Physical Signal Abstraction layer, signal variables are used.

A signal variable carries the physical value of a network signal normally packaged inside a PDU or frame.
The unit definition of the variable must match the one defined in the <<high-cut-network-description-files>>, if provided.

Each network signal must be listed as a <<high-cut-terminal-member-variable-for-signals>> of its corresponding <<high-cut-pdu-terminal>>.

In case multiplexed signals are present in a frame/PDU/container PDU:
All signals/PDUs are present, but only the active signal according to the multiplex switch signal contains a valid value, all inactive variables have undefined values.
_[These values could even be outside their specified min-max range without fault.]_

All signal variables are clocked to indicate when they have been sent/received, see <<high-cut-clock-variables>>.

=== Clocks [[high-cut-clock-variables]]
In order to use FMU input and output variables as transport layer for networks, Clocks are used to indicate the timing.
Such a Clock is scheduled by the sending FMU to indicate the transmission of the corresponding frame or frames.

The Clock type (`periodic` or `aperiodic`) is defined by the sending FMU.

_[This allows the FMU (or better the exporting tool) to balance the accuracy and performance of its network communication:_


_- While `aperiodic` Clocks allow very accurate network simulations, frequently entering `Event Mode` might reduce the network simulation speed._

_- Using `periodic` Clocks might reduces the number of `Event Modes` required and might speeds up the simulation at the cost of simulation accuracy, because timing must be forced into a fixed grid and some intermediate values might not be transmitted._

_- One could use (structural) parameters to define the accuracy of `aperiodic` Clocks, allowing control of the simulation accuracy and performance with the same FMU._
 
_Note: The statements regarding `aperiodic` and `periodic` Clocks and their impact on performance should be understood as general tendencies rather than universally valid truths, as other aspects such as baud rates and expected bus loads must be taken into account for a more precise estimate.]_
 
The Clocks of a receiving frame shall be `triggered` Clocks if they are to be driven by the respective Clock of the sending frame.
Alternatively, Clocks of a receiving frame can be `periodic` Clocks matching the relevant Clock of the sending frame, which causes them to be scheduled for the same time instances
_[This may allow for more efficient simulation in the case that there exists a more or less static communications schedule, and more detailed simulation of timing variation is not needed.]_

Signal variables belonging to frame `BusName.FrameName` and all its variables must share the same `causality` (`input` or `output`).

=== Network Description Files [[high-cut-network-description-files,network description file]]
Standardized <<high-cut-network-description-files,network description files>> may optionally be shipped with each FMU to describe properties of signals and frames, such as signal units, frame composition and trigger conditions.
If these <<high-cut-network-description-files,network description files>> are shipped, they must be placed into the `/extra/org.fmi-standard.fmi-ls-bus` folder.
DBC, LDF, Fibex and ARXML files are allowed, e.g., `Powertrain.dbc`.
The case-sensitive root name of the <<high-cut-network-description-files>> must be used as network identifier in the Bus Terminal type and prefix in the variable names.

Multiple files can be specified, each one defining one network used by the FMU.
This standard does not support composing one network from multiple <<high-cut-network-description-files,network description files>>, even if using internal include mechanisms, it rather enforces the rule: One network - one file.

It is recommended to use ARXML over DBC files for CAN whenever possible, because the DBC standard lacks some key frame/PDU properties that were added only later using non-standard extensions with different dialects in use.

This document does not address potential open points of these description formats, it is assumed that such ambiguities will be handled elsewhere (e.g., message timing in the DBC format).
This document does not address IP protection or copyright issues.
These are technical and legal issues that need attention from standardization bodies of the referenced description formats, tool vendors and end users.

=== Terminal Definitions [[high-cut-terminal-definitions]]
This section defines terminals for Physical Signal Abstraction.

==== Bus Terminal [[high-cut-bus-terminal,Bus Terminal]]
Each network connected to the FMU must be described in `icons/terminalsAndIcons.xml` as a `<Terminal>` element of `<fmiTerminalsAndIcons><Terminals>` that wraps all its <<high-cut-frame-terminal,frame terminals>>.
The attribute `name` of the `<Terminal>` element must match the root name of its <<high-cut-network-description-files>> if it exists
_[e.g., `Powertrain`, if the file is `/extra/org.fmi-standard.fmi-ls-bus/Powertrain.dbc`]_.

Attribute definitions::
 * `terminalKind` must be `org.fmi-ls-bus.network-terminal`.
 * `matchingRule` must be `bus`.
 * `name` is the network name, e.g., `Powertrain`, see <<high-cut-examples, examples>> and constraints above.

Element definitions::
 * All signal variables and Clocks related to the Physical Signal Abstraction in the `modelDescription.xml` must be covered by a `<Terminal>` element representing the network frame the signals belong to.

Annotation element::
 * If a <<high-cut-network-description-files,network description file>> is shipped with the specified FMU, there must be an `<Annotation>` element defining which node or nodes (as comma-separated list without spaces) of the <<high-cut-network-description-files>> are wrapped inside the FMU.
If the combination of nodes specified for this FMU turns a frame and its signals into both input and output because sending and receiving nodes are specified, only the sending (output) role will be defined in the FMU interface.
Receiving such frames must then be handled internally to the FMU.
If no <<high-cut-network-description-files,network description file>> is shipped with the specified FMU the `<Annotation>` shall not exist.

==== Frame Terminal [[high-cut-frame-terminal,frame terminal]]
Each frame listed in the <<high-cut-network-description-files>> must be an element of its corresponding <<high-cut-bus-terminal>>.

Attribute definitions::
 * `terminalKind` must be `org.fmi-ls-bus.frame-terminal`.
 * `matchingRule` must be `bus`.
 * `name` must match the frame name as defined in the <<high-cut-network-description-files>> in `/extra/org.fmi-standard.fmi-ls-bus`.

Element definitions::
 * There must be one <<high-cut-pdu-terminal>> element per PDU of this frame.
 * There must be one `<TerminalMemberVariable>` for the Clock this frame is connected to.
   The `memberName` of this variable must be `TransmissionClock`.

The <<high-cut-terminal-member-variable-for-signals>> must have the same `causality` as all variables referenced in the <<high-cut-pdu-terminal,PDU terminals>> included here.

==== PDU Terminal [[high-cut-pdu-terminal,PDU terminal]]
Each PDU listed in the <<high-cut-network-description-files>> must be an element of its corresponding <<high-cut-frame-terminal>>.

Attribute definitions::
 * `terminalKind` must be `org.fmi-ls-bus.pdu-terminal`.
 * `matchingRule` must be `bus`.
 * `name` must match a PDU name of the <<high-cut-network-description-files>> in `/extra/org.fmi-standard.fmi-ls-bus`, if given.
    For network types not natively referencing a "PDU", like CAN, a synthetic PDU with the same name as its frame is inserted.

Element definitions::
 * There must be one `<TerminalMemberVariable>` per <<high-cut-terminal-member-variable-for-signals,signal>> of this PDU.

All <<high-cut-terminal-member-variable-for-signals,`TerminalMemberVariables`>> must have the same `causality` of either `input` or `output`.

==== Terminal Member Variable for Signals [[high-cut-terminal-member-variable-for-signals,Terminal Member Variable]]
<<high-cut-pdu-terminal,PDU terminals>> list all the contained signals as `<TerminalMemberVariable>`.

Attribute definitions::
 * `variableName` refers to the input or output variable name of the FMU.
    These variables represent the Physical Signal Abstraction layer.
    Unless there are other requirements, it is recommended to build the variable names as follows: `BusName.FrameName.PDUName.SignalName`, e.g., `Powertrain.tcuSensors.tcuSensors.vCar`.
    This approach automatically provides unique names for all bus-related variables, and can also be used for Clocks, to allow automatic grouping by non-terminal-aware tools.
 * `memberName` is the `SignalName` as given in the <<high-cut-network-description-files>>, e.g., `vCar`, if given.
    This is redundant information but simplifies signal name extraction.
 * `variableKind` is `signal`.

=== Examples [[high-cut-examples]]
The following excerpts from files are used throughout this document as examples and should illustrate how the different concepts relate.

==== CAN Bus Databases (DBC) [[high-cut-examples-can-bus-databases]]
The following partial DBC file lists merely the CAN message (frame) structure.
Signal trigger conditions are not included because they have no bearing on this standard.

.Example Powertrain.dbc file.
[[example-powertrain-dbc]]
[source, C]
----
...
BO_ 256 tcuSensors: 4 TCU
 SG_ vCar :          0|16@1- (32,0)  [-500|500] "km/h" ECU
 SG_ oilTemp :      16|9@1-  (2,50)  [-50|150]  "Degree C" ECU

BO_ 257 tcuState: 2 TCU
 SG_ state :         0|2@1+  (1,0)   [ 0|2] "-" ECU
 SG_ gear :          2|4@1-  (1,0)   [-2|6] "-" ECU
 SG_ targetGear :    6|4@1-  (1,0)   [-2|6] "-" ECU

BO_ 512 ecuState: 4 ECU
 SG_ accelPedal :    0|8@1+ (2,0)   [0|100]   "%" TCU
 SG_ k15 :           8|1@1+ (1,0)   [0|1]     "-" TCU
 SG_ oilTemp :       9|9@1- (2,50)  [-50|150] "Degree C" TCU
 SG_ radiatorTemp : 18|9@1- (2,50)  [-50|150] "Degree C" TCU
...
----

The `modelDescription.xml` excerpt listed below shows which variables would exist for the `Powertrain.dbc` shown above.

.Example modelDescription.xml for ECU node.
[[example-modelDescriptionHighCut-dbc-xml]]
[source, XML]
----
include::examples/X_network4FMI_modelDescription_highCut_dbc.xml[]
----

The following file shows the <<high-cut-bus-terminal,Bus Terminal>> definition representing the network and frame structure defined with `Powertrain.dbc` above.
The `name` of the <<high-cut-frame-terminal,frame terminal>> and the <<high-cut-pdu-terminal,PDU terminal>> are derived from the DBC attribute `_BO`.
The `SignalName`, and so the resulting `memberName`, is derived from the DBC attribute `_SG`.

.Example terminalsAndIcons.xml file.
[[example-terminalsAndIconHighCut-dbc-xml]]
[source, XML]
----
include::examples/X_network4FMI_terminalsAndIcons_highCut_dbc.xml[]
----

==== AUTOSAR [[high-cut-examples-autosar]]
The following AUTOSAR system extract (in ARXML format) shows the mapping of an AUTOSAR Frame-Triggering, PDU-Triggering and Signal-Triggering structure within the Physical Signal Abstraction.

.Incomplete example AUTOSAR Powertrain.arxml system extract file.
[[example-powertrain-autosar]]
[source, xml]
----
...
<AR-PACKAGE>
  <SHORT-NAME>SystemExtract</SHORT-NAME>
  <ELEMENTS>
    <CAN-CLUSTER>
      <SHORT-NAME>PowertrainCluster</SHORT-NAME>
      <CAN-CLUSTER-VARIANTS>
        <CAN-CLUSTER-CONDITIONAL>
          <PHYSICAL-CHANNELS>
            <CAN-PHYSICAL-CHANNEL>
              <SHORT-NAME>Powertrain</SHORT-NAME>
              <FRAME-TRIGGERINGS>
                <CAN-FRAME-TRIGGERING>
                  <SHORT-NAME>tcuSensors_FrameTriggering</SHORT-NAME>
                  <FRAME-REF>/.../Frames/tcuSensors</FRAME-REF>
                  <PDU-TRIGGERINGS>
                    <PDU-TRIGGERING-REF-CONDITIONAL>
                      <PDU-TRIGGERING-REF>/.../tcuSensors_PduTriggering</PDU-TRIGGERING-REF>
                    </PDU-TRIGGERING-REF-CONDITIONAL>
                  </PDU-TRIGGERINGS>
                  <IDENTIFIER>256</IDENTIFIER>
                </CAN-FRAME-TRIGGERING>
              </FRAME-TRIGGERINGS>
              <I-SIGNAL-TRIGGERINGS>
                <I-SIGNAL-TRIGGERING>
                  <SHORT-NAME>vCar_ISignalTriggering</SHORT-NAME>
                  <I-SIGNAL-REF>/.../ISignals/vCar</I-SIGNAL-REF>
                </I-SIGNAL-TRIGGERING>
                <I-SIGNAL-TRIGGERING>
                  <SHORT-NAME>oilTemp_ISignalTriggering</SHORT-NAME>
                  <I-SIGNAL-REF>/.../ISignals/oilTemp</I-SIGNAL-REF>
                </I-SIGNAL-TRIGGERING>
              </I-SIGNAL-TRIGGERINGS>
              <PDU-TRIGGERINGS>
                <PDU-TRIGGERING>
                  <SHORT-NAME>tcuSensors_PduTriggering</SHORT-NAME>
                  <I-PDU-REF>/.../PDUs/tcuSensors</I-PDU-REF>
                  <I-SIGNAL-TRIGGERINGS>
                    <I-SIGNAL-TRIGGERING-REF-CONDITIONAL>
                      <I-SIGNAL-TRIGGERING-REF>/.../vCar_ISignalTriggering</I-SIGNAL-TRIGGERING-REF>
                    </I-SIGNAL-TRIGGERING-REF-CONDITIONAL>
                    <I-SIGNAL-TRIGGERING-REF-CONDITIONAL>
                      <I-SIGNAL-TRIGGERING-REF>/.../oilTemp_ISignalTriggering</I-SIGNAL-TRIGGERING-REF>
                    </I-SIGNAL-TRIGGERING-REF-CONDITIONAL>
                  </I-SIGNAL-TRIGGERINGS>
            ...
  </ELEMENTS>
</AR-PACKAGE>
...
----

The `modelDescription.xml` excerpt listed below shows which variables would exist for the `Powertrain.arxml` shown above.

.Example modelDescription.xml for ECU node.
[[example-modelDescriptionHighCut-autosar-xml]]
[source, XML]
----
include::examples/X_network4FMI_modelDescription_highCut_autosar.xml[]
----

The following file shows the <<high-cut-bus-terminal,Bus Terminal>> definition representing the network and frame structure defined with `Powertrain.arxml` above.
The `name` of the <<high-cut-frame-terminal,frame terminal>> is derived from the ShortName attribute of the respective AUTOSAR frame.
The `name` of the <<high-cut-pdu-terminal,PDU terminal>> is derived from the ShortName attribute of the respective AUTOSAR PDU.
The `SignalName`, and so the resulting `memberName`, is derived from the respective AUTOSAR ISignal.
The `BusName` is derived from the AUTOSAR Cluster ShortName concatenated via a `.` character with the AUTOSAR Physical Channel ShortName.

.Example terminalsAndIcons.xml file.
[[example-terminalsAndIconHighCut-autosar-xml]]
[source, XML]
----
include::examples/X_network4FMI_terminalsAndIcons_highCut_autosar.xml[]
----

=== Limitations [[high-cut-limitations]]
Physical Signal Abstraction maps several network protocols onto co-simulation variables as transport layer simulating in many ways an ideal network.
Such an ideal network differs from physical networks in the following ways (and potentially others):

 * Network frame arbitration: Frames are sent on the wire according to network-specific priority rules. +
   Here all frames are transmitted at the same time without delay.

 * Network congestion/bandwidth: Too many network frames sent for the bandwidth of the network. +
   Here the network has infinite capacity. +
   If network properties are required, a bus simulation component must be added or included with the importer.

 * Protocol functions of higher levels: I.e. CAN request for retransmit is a specific protocol function. +
   Here such specialties must be handled by the first layer inside the FMU.

 * Incoming buffer overflow: When an ECU receives more frames than its buffer can hold. +
   Here the FMU will receive all frames, regardless of buffer size and would need to handle those limitations internally.

 * Network protocols allow frames to be sent from more than one node. +
   Here this is also possible, with output variables for frames (and their signals) that are sent by more than one FMU.
   This requires the importer to handle the case when multiple source FMUs are sending the same frame.
   Importers must know how to handle this, just like they must know how to handle flow variables according to Kirchhoff's law.
