==== Ethernet [[low-cut-ethernet]]
This chapter describes the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> for Ethernet.

===== Overview [[low-cut-ethernet-overview]]
===== Operations [[low-cut-ethernet-operations]]
This section defines the specified operations for Ethernet.
The following tables provides an overview of all operations and specifies the position and length of the corresponding arguments, as well as the respective flow direction.

====== Format Error [[low-cut-ethernet-format-error-operation]]
Represents a format error that indicates a syntax or content error of receiving operations.
See <<low-cut-format-error-operation, `Format Error`>> for definition.

====== Wake Up [[low-cut-ethernet-wake-up-operation]]
By using <<low-cut-ethernet-wake-up-operation, `Wakeup`>> and <<low-cut-ethernet-sleep-operation, `Sleep`>> operations, the underlying Bus Simulation can trigger a bus-specific wake up and sleep requests.

.Detailed description of the Wakeup operation.
[#table-ethernet-wakeup-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Wakeup
h|Description
3+|Represents an operation for triggering a bus-specific wake up.
h|OP Code [hex]
3+|0x42
.3+h|Content h|Argument h|Length h|Description
|OP Code
|4 byte
|Contains the OP Code (0x42) of the operation.

|Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 8`.

h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the wake-up initiator, of the bus using the Bus Simulation.
If a Network FMU does not support wake up, this operation can be ignored on the consumer side.

|====

====== Sleep [[low-cut-ethernet-sleep-operation]]
By using <<low-cut-ethernet-wake-up-operation, `Wakeup`>> and <<low-cut-ethernet-sleep-operation, `Sleep`>> operations, the underlying Bus Simulation can trigger a bus-specific wake up and sleep requests.

.Detailed description of the Sleep operation.
[#table-ethernet-sleep-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Sleep
h|Description
3+|Represents an operation for triggering a bus-specific sleep.
h|OP Code [hex]
3+|0x43
.3+h|Content h|Argument h|Length h|Description
|OP Code
|4 byte
|Contains the OP Code (0x43) of the operation.

|Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 8`.

h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the sleep requesting initiator, of the bus using the Bus Simulation.
If a Network FMU does not support sleep requests, this operation can be ignored on the consumer side.

|====

===== Network Parameters [[low-cut-ethernet-network-parameters]]
===== Configuration of Bus Simulation [[low-cut-ethernet-configuration-of-bus-simulation]]
===== Transmission [[low-cut-ethernet-transmission]]
===== Error Handling [[low-cut-ethernet-error-handling]]
===== Wake Up/Sleep [[low-cut-ethernet-wakeup-sleep]]
This standard supports wake up and sleep functionality for the Ethernet bus, based on the TC10 Sleep/Wake-up 
Specification.
Note that Wake Up/Sleep is not available for all Ethernet variants, but only for 10BASE-T1S, 100BASE-T1, 1000BASE-T1 and Multi-G BASE-T1.
However, the realization of local virtual ECU wake-up and sleeping processes, i.e., the transition to the sleep state as well as the virtual ECU local wake-up process, is considered internal to the FMU implementation.
Therefore, only the bus-related aspects are defined in this document.

The Ethernet-specific wake-up pulse can be simulated by using the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation, initiated by one Network FMU.
The Bus Simulation shall distribute this operation to all participants on the bus, excluding the wake-up initiator.

.Wake up initiated by FMU 1 wakes up FMU 2 and FMU 3 via bus.
[#figure-ethernet-wake-up]
image::ethernet_wake_up.svg[width=70%, align="center"]

Analogously, the <<low-cut-ethernet-sleep-operation, `Sleep`>> operation is used to prompt corresponding receivers to go to sleep.
The flow direction is analogous to the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation.
