==== Ethernet [[low-cut-ethernet]]
This chapter describes the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> for Ethernet.

===== Overview [[low-cut-ethernet-overview]]

====== Scope of this standard

Ethernet support in the LS-BUS should cover both normal and automotive Ethernet.

In the Ethernet stack, similar to other busses, the LS-BUS for Ethernet cuts right above the MAC layer. Though, effects on lower layers are also modeled at an abstracted level.

TODO:

* PHY compatibility
* Link establishment
* PLCA

This standard should cover all variants of Ethernet described in IEEE 802.3-2022 while being flexible enough to support future versions without adaption.
Specifically, 100BASE-TX, 1000BASE-T, 100BASE-T1, 1000BASE-T1 and 10BASE-T1S have been evaluated in detail for this standard.
In addition, common extensions are considered.

TODO:

* Mention AVB/TSN (e.g., preemption)
* Mention OpenAlliance (e.g., TC10 wakeup/sleep)
* Reference what exactly is part of the standard, and what can be achieved on higher layers. (table?)


====== Ethernet topologies

Ethernet support both point-to-point and multidrop topologies.
In a point-to-point topology, Ethernet devices are either connected directly and more than two devices are connected using and Ethernet switch.
This topology is used for all modern Ethernet variants except 10BASE-T1S.
In a multidrop topology, multiple devices are connected to the same segment either directly, daisy-chained or interconnected via hubs.
This topology is used for legacy Ethernet standards as well as 10BASE-T1S.

In terms of the LS-BUS, each point-to-point connection or multidrop segment represents a dedicated virtual bus, which may be simulated by an independent bus simulation or combined into an consolidated simuation.
Ethernet switches can be modeled as normal FMUs, where switch ports correspond to LS-BUS terminals, to allow simulating any kind of Ethernet switch.
To simplify interconnecting Ethernet FMUs, a bus simulation may decide to incorporate the Ethernet switching instead of delegating it to a dedicated FMU.


===== Transmission [[low-cut-ethernet-transmission]]

A transmission of an Ethernet frame is modeled by a transmit operation.
The transmit operation is received by the bus simulation and forwarded to the communication partner after the transmission delay which should be calculated by the bus simulation.

The bus simulation then sends a confirm operation to the sender, if the <<low-cut-ethernet-bus-notification-parameter, Bus Notification parameter>> is configured.
In the case of an error or collision, a bus error operation may be returned instead.

The following sections will describe special transmission scenarios.

====== Normal transmission

TODO

====== Transmission with avoided collision

TODO

====== Transmission with collision

TODO

====== Fragmented transmission using the MAC Merge sublayer

When using the MAC Merge sublayer (See chapter 99 of 802.3-2022),
the transmit operation can also indicate the transmission of Express frames and the initial fragment of preempted frames.
Continuation packets of a preempted frame are transmitted using the transmit continuation operation.

TODO: Examples


===== Configuration of bus Simulation [[low-cut-ethernet-configuration-of-bus-simulation]]


===== Error Handling [[low-cut-ethernet-error-handling]]
===== Wake Up/Sleep [[low-cut-ethernet-wakeup-sleep]]
This standard supports wake up and sleep functionality for the Ethernet bus, based on the TC10 Sleep/Wake-up
Specification.
Note that Wake Up/Sleep is not available for all Ethernet variants, but only for 10BASE-T1S, 100BASE-T1, 1000BASE-T1 and Multi-G BASE-T1.
However, the realization of local virtual ECU wake-up and sleeping processes, i.e., the transition to the sleep state as well as the virtual ECU local wake-up process, is considered internal to the FMU implementation.
Therefore, only the bus-related aspects are defined in this document.

The Ethernet-specific wake-up pulse can be simulated by using the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation, initiated by one Network FMU.
The Bus Simulation shall distribute this operation to all participants on the bus, excluding the wake-up initiator.

.Wake up initiated by FMU 1 wakes up FMU 2 and FMU 3 via bus.
[#figure-ethernet-wake-up]
image::ethernet_wake_up.svg[width=70%, align="center"]

Analogously, the <<low-cut-ethernet-sleep-operation, `Sleep`>> operation is used to prompt corresponding receivers to go to sleep.
The flow direction is analogous to the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation.


===== Network parameters [[low-cut-ethernet-network-parameters]]
By using configuration parameters on bus terminal-level, network FMUs can be parameterized by the user or bus simulation (e.g., by using the parameter propagation mechanism).
This chapter specifies the configuration parameters that should exist on an Ethernet bus terminal.

====== Bus notification parameter [[low-cut-ethernet-bus-notification-parameter]]
For a detailed simulation, a network FMU needs information about whether a frame has been sent or whether a bus error has occurred.
A bus simulation can simulate these effects by sending bus notifications in terms of <<low-cut-ethernet-confirm-operation, `Confirm-`>> and <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operations to the network FMUs.


include::4_4_4_ethernet_operations.adoc[]
