==== Ethernet [[low-cut-ethernet]]
This chapter describes the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> for Ethernet.

===== Overview [[low-cut-ethernet-overview]]
To simulate the Ethernet bus type, Ethernet-specific operations are specified based on the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>>.
Overall, the following groups of operations exists:

* Transmit: This group of operations is used to simulate a frame transmission.
Different types of Ethernet frames (e.g. Express frames) are taken into account here.
* Confirm: Represents an confirmation of transmitted Ethernet frames.
* Error: This group of operations is used for protocol format errors and to simulate bus failures.
For example, the failure of a transmission can be indicated.
* Configuration: This operation enables the configuration of bus-specific parameters and options that are required to simulate the bus behavior properly.
* Auto-Negotiation: This group of operations is used to simulate different Ethernet Auto-Negotiation mechanisms.
* Link State Indication: This operation indicates the state of the physical medium attachment.
* Wake up: Ethernet supports wake up and sleep scenarios.
Normally there are two ways to wake up from sleep mode: a local wake up on a specified wake-up pin, or a wake-up on the Ethernet bus via a Ethernet specific wake-up pulse.
This operation is used to simulate triggering a wake-up from bus side.

The following table gives a detailed overview of the available operations.
It shows all operations and the arguments they contain.

#TODO: Add overview table#

====== Scope of this Standard [[low-cut-ethernet-scope-of-this-standard]]
This standard should allow simulation of Ethernet bus systems and shall cover commercial, industrial and automotive use cases.

This standard should cover all variants of Ethernet described in <<IEEE-802.3-2022>> while being flexible enough to support future versions without adaption due to the high cadence of the Ethernet standardization process.
In addition, common supplementary standards are considered, including the following:

* <<OpenAlliance-TC10-100BASE-T1, Open Alliance TC10 sleep/wake-up>> (including <<OpenAlliance-TC10-100BASE-T1, 100BASE-T>>, <<OpenAlliance-TC10-1000BASE-T1, 1000BASE-T1>> and <<OpenAlliance-TC10-10BASE-T1S, 10BASE-T1S>>)

Especially the physical layers 100BASE-TX, 1000BASE-T, 10GBASE-T, 100BASE-T1, 1000BASE-T1 and 10BASE-T1S have been evaluated in detail for this standard.
In addition, it should consider requirements for time-sensitive networking (TSN), specifically the use of the MAC Merge sublayer (also known as Ethernet Frame Preemption).

In the 802.3 architecture, the layered standard aims to provide an abstraction of the Ethernet controller on the Media Access Control (MAC) sublayer.
Effects on lower layers are modeled on a simplified level.

====== Ethernet Topologies [[low-cut-ethernet-ethernet-topologies]]
Ethernet support both point-to-point and multidrop topologies.
In a point-to-point topology, Ethernet devices are either connected directly or more than two devices are connected using an Ethernet switch.
This topology is used for all modern Ethernet variants except 10BASE-T1S.
In a multidrop topology, multiple devices are connected to the same segment either directly, daisy-chained or interconnected via hubs.
This topology is used in legacy Ethernet systems as well as 10BASE-T1S networks.

In terms of the FMI-LS-BUS specification, each point-to-point connection or multidrop segment represents a dedicated virtual bus, which may be simulated by an independent Bus Simulation or combined into a consolidated simulation.
Ethernet switches can be modeled as normal FMUs, where switch ports correspond to Bus Terminals, to allow simulating any kind of Ethernet switch.
To simplify interconnecting Ethernet FMUs, a Bus Simulation may decide to incorporate the Ethernet switching instead of delegating it to a dedicated FMU.

===== Transmission and Reception [[low-cut-ethernet-transmission]]
A transmission of an Ethernet frame is modeled by a <<low-cut-ethernet-transmit-operation, `Transmit`>> operation.
The <<low-cut-ethernet-transmit-operation, `Transmit`>> operation is received by the Bus Simulation and forwarded to the communication partner after the transmission delay which should be calculated by the Bus Simulation.

The Bus Simulation then sends a <<low-cut-ethernet-confirm-operation, `Confirm`>> operation to the sender, if the <<low-cut-ethernet-bus-notification-parameter, `BusNotifications`>> parameter is configured.
In the case of an error or collision, a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation may be returned instead.

The following sections will describe different transmission scenarios in detail.

====== Normal Transmission [[low-cut-ethernet-normal-transmission]]
In a normal transmission, the Network FMU sends a <<low-cut-ethernet-transmit-operation, `Transmit`>> operation which is
forwarded to the communication partner after the calculated transmission time.
The Bus Simulation confirms the transmission with a <<low-cut-ethernet-confirm-operation, `Confirm`>> operation.

<<#figure-ethernet-transmit>> illustrates the behavior, whereby FMU 1 transmits network data to FMU 2 via a Bus Simulation.
After the transmission has been successfully completed, the Bus Simulation acknowledges this process by using a <<low-cut-ethernet-confirm-operation, `Confirm`>> operation, which is provided to FMU 1.

.Normal transmission.
[#figure-ethernet-transmit]
image::ethernet_transmit.svg[width=70%, align="center"]

====== Transmission with avoided Collision [[low-cut-ethernet-transmission-with-avoided-collision]]
On a real Ethernet bus, an Ethernet node can use carrier sensing to detect ongoing transmissions to defer its own transmission until the medium is free.
In the FMI-LS-BUS specification, this is not possible, thus a special bus error is introduced to indicate when the medium is busy.

When a Network FMU starts a transmission in this case, the Bus Simulation returns a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation with value of argument argument `Error Code` set to <<table-fmi3-ls-bus-ethernet-bus-error-code-values-medium-busy, `MEDIUM_BUSY`>>.
The Network FMU should the re-attempt the transmission at a later point in time.

_Note: In this scenario the ongoing transmission continues._

<<figure-ethernet-transmit-collision-avoided>> illustrates how FMU 1 firstly provides a <<low-cut-ethernet-transmit-operation, `Transmit`>> operation to the Bus Simulation.
While the transmission is still running, FMU 2 tries to provide another <<low-cut-ethernet-transmit-operation, `Transmit`>> operation.
This leads to a conflict because the simulated bus is already occupied by the transmission from FMU 1.
FMU 2 is notified of this situation by receiving a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation with argument `Error Code` set to <<table-fmi3-ls-bus-ethernet-bus-error-code-values-medium-busy, `MEDIUM_BUSY`>> by the Bus Simulation.
The <<low-cut-ethernet-transmit-operation, `Transmit`>> operation, originally provided by FMU 1, is then provided to FMU 2 and FMU 3.
FMU 1 acknowledges a successful transmission using a <<low-cut-ethernet-confirm-operation, `Confirm`>> operation.

.Transmission with avoided collision.
[#figure-ethernet-transmit-collision-avoided]
image::ethernet_transmit_collision_avoided.svg[width=80%, align="center"]

====== Transmission with Collision [[low-cut-ethernet-transmission-with-collision]]
If the Ethernet node does not detect an ongoing transmission in time, the Ethernet frames collide causing both transmissions to be destroyed.

When a Network FMU starts a transmission in this case, the Bus Simulation returns a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation with value of argument `Error Code` set to <<table-fmi3-ls-bus-ethernet-bus-error-code-values-collision, `COLLISION`>>.
This is also sent to other nodes on the bus including the sender of the other transmission.

_Note: In this scenario the ongoing transmission is destroyed as well._

<<figure-ethernet-transmit-collision>> illustrates how FMU 1 firstly provides a <<low-cut-ethernet-transmit-operation, `Transmit`>> operation to the Bus Simulation.
While the transmission is still running, FMU 2 tries to provide another <<low-cut-ethernet-transmit-operation, `Transmit`>> operation.
This leads to a conflict because the simulated bus is already occupied by the transmission from FMU 1.
All three Network FMUs are notified of this situation by receiving a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation with argument `Error Code` set to <<table-fmi3-ls-bus-ethernet-bus-error-code-values-collision, `COLLISION`>> by the Bus Simulation.

.Transmission with collision.
[#figure-ethernet-transmit-collision]
image::ethernet_transmit_collision.svg[width=80%, align="center"]

====== Fragmented Transmission using the MAC Merge Sublayer [[low-cut-ethernet-fragmented-transmission-using-merge-sublayer]]
When using the MAC Merge sublayer (see chapter 99 of <<IEEE-802.3-2022>>),
the <<low-cut-ethernet-transmit-operation, `Transmit`>> operation can also indicate the transmission of Express frames and the initial fragment of preempted frames.
Continuation packets of a preempted frame are transmitted using the <<low-cut-ethernet-transmit-continuation-operation, `Transmit Continuation`>> operation.

Before the MAC Merge sublayer is used, _Verify_ and _Respond_ frames are used to verify that the link partner supports this functionality, these are indicated by an <<low-cut-ethernet-transmit-verify-respond-operation, `Transmit Verify/Respond`>> operation.

<<figure-ethernet-transmit-fragmented>> illustrates how the two Network FMUs FMU 1 and FMU 2 first agree on the exchange of Express frames with the help of a Bus Simulation by performing a handshake via the <<low-cut-ethernet-transmit-verify-respond-operation, `Transmit Verify/Respond`>> operation.
Afterwards, the first fragment of the first Ethernet frame is sent from FMU 1 to FMU 2 via the Bus Simulation by using a <<low-cut-ethernet-transmit-operation, `Transmit`>> operation.
In the next step, FMU 1 sends another <<low-cut-ethernet-transmit-operation, `Transmit`>> operation, which does not refer to the first Ethernet frame fragment.
In the third step, the second fragment of the Ethernet frame is provided from FMU 1 to FMU 2 by using the special <<low-cut-ethernet-transmit-continuation-operation, `Transmit Continuation`>> operation.

.Fragmented transmission. The frame 1 is fragmented into two fragments 1.1 and 1.2 due to a transmission of an Express frame 2.
[#figure-ethernet-transmit-fragmented]
image::ethernet_transmit_fragmented.svg[width=80%, align="center"]

===== Configuration and Startup [[low-cut-ethernet-configuration-and-startup]]
To initialize the Ethernet communication, the Network FMUs need to exchange
their capabilities and the current parameters of the Ethernet link.
This serves to properly simulate compatibility of the used PHY and to determine the correct link speed and behavior.

In addition, configuration and simulation of auto-negotiation, auto MDI-X and lower layer mechanisms like PLCA is supported using this mechanism.

The configuration and startup phase consists of the following steps:

. Exchange of <<low-cut-ethernet-configuration-operation, `Configuration`>> operations (see <<low-cut-ethernet-configuration-phase>>)
. Sending of an initial <<low-cut-ethernet-link-state-indication-operation, `Link State Indication`>> operation
. <<low-cut-ethernet-configuration-phase, Auto-Negotiation>> (optional)
. Sending of an updated <<low-cut-ethernet-link-state-indication-operation, `Link State Indication`>> operation (optional)

These phases are described in further detail in the following sections.

TODO: PLCA

====== Configuration Phase [[low-cut-ethernet-configuration-phase]]
Before an Ethernet Network FMU may communicate, it must send a <<table-fmi3-ls-bus-ethernet-configuration-operation, `Configuration`>> operation.
Only after also receiving a <<low-cut-ethernet-configuration-operation, `Configuration`>> operation and evaluating it against its own configuration for compatibility, it may start transmitting frames.

In a direct connection scenario, <<low-cut-ethernet-configuration-operation, `Configuration`>> operations are exchanged as-is.
With a Bus Simulation, <<low-cut-ethernet-configuration-operation, `Configuration`>> operations may either be forwarded by a Bus Simulation or the Bus Simulation may supply its own <<low-cut-ethernet-configuration-operation, `Configuration`>> operation to each node.
In a multidrop configuration, the Bus Simulation shall not forward <<low-cut-ethernet-configuration-operation, `Configuration`>> operations but should supply a single <<low-cut-ethernet-configuration-operation, `Configuration`>> operation to each Network FMU.

In addition to the <<low-cut-ethernet-configuration-operation, `Configuration`>> operation, the link state should be indicated with a <<low-cut-ethernet-link-state-indication-operation, `Link State Indication`>> operation.
This may be done right after the <<low-cut-ethernet-configuration-operation, `Configuration`>> operation or at the latest after receiving the <<low-cut-ethernet-configuration-operation, `Configuration`>> operation of the connected Network FMU.

====== Auto-Negotiation [[low-cut-ethernet-auto-negotiation]]
If auto-negotiation is enabled for the Network FMU, it should perform it after the configuration phase.
The initial link indication should set a physical medium attachment of "unknown".

Both auto-negotiation according to <<IEEE-802.3-2022, IEEE 802.3>> section 28 (e.g., for 10BASE-T, 100BASE-TX, 1000BASE-T, 10GBASE-T) and <<IEEE-802.3-2022, IEEE 802.3>> section 98 (e.g., for 100BASE-T1, 1000BASE-T1, 10BASE-T1S) are supported.
Auto-negotiation according to <<IEEE-802.3-2022, IEEE 802.3>> section 37 (e.g., for 1000BASE-LX, 1000BASE-CX) is currently not explicitly supported.

This standard defines a simplified auto-negotiation procedure in which all pages are exchanged at the same time.

To perform auto-negotiation, the Network FMU should send a <<low-cut-ethernet-auto-negotatiation-base-page-operation, Section 28 `Base Page`>> operation or <<low-cut-ethernet-single-differential-pair-auto-negotatiation-base-page-operation, Section 98 `Base Page`>> operation optionally followed by one more <<low-cut-ethernet-auto-negotatiation-message-page-operation, `Message Page`>> operations (for section 28), <<low-cut-ethernet-auto-negotatiation-unformatted-page-operation, `Unformatted Page`>> operations (for section 28), <<low-cut-ethernet-auto-negotatiation-extended-unformatted-page-operation, `Extended Message Page`>> operations (for section 28 and section 98), or <<low-cut-ethernet-auto-negotatiation-extended-message-page-operation, `Extended Unformatted Page`>> operations (for section 28 and section 98).
Note that the section 28 extended next pages and section 98 next pages have the same structure and are thus represented by the same bus operations.

After both sending and receiving the auto-negotiation pages, the Network FMU should determine the highest-common-denominator physical medium attachment and enable communication if compatible with the connected node.
This should be indicated with a <<low-cut-ethernet-link-state-indication-operation, `Link State Indication`>> operation.

===== Error Handling [[low-cut-ethernet-error-handling]]
To model errors on the Ethernet bus, <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operations are used.
These operations may be sent by a Bus Simulation to all Network FMUs which may detect that errors.

A Bus Simulation may also inject errors into the simulation, by sending a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation.

.Architectural error handling overview.
[#figure-ethernet-architectural-error-handling-overview]
image::ethernet_error_handling_overview.svg[width=80%, align="center"]

TODO: Extend and specify error scenarios

===== Wake Up/Sleep [[low-cut-ethernet-wakeup-sleep]]
This standard supports wake up and sleep functionality for the Ethernet bus, based on the TC10 Sleep/Wake-up
Specification.
Note that Wake Up/Sleep is not available for all Ethernet variants, but only for 10BASE-T1S, 100BASE-T1, 1000BASE-T1 and Multi-G BASE-T1.
However, the realization of local virtual ECU wake-up and sleeping processes, i.e., the transition to the sleep state as well as the virtual ECU local wake-up process, is considered internal to the FMU implementation.
Therefore, only the bus-related aspects are defined in this document.

The Ethernet-specific wake-up pulse can be simulated by using the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation, initiated by one Network FMU.
The Bus Simulation shall distribute this operation to all participants on the bus, excluding the wake-up initiator.

.Wake up initiated by FMU 1 wakes up FMU 2 and FMU 3 via bus.
[#figure-ethernet-wake-up]
image::ethernet_wake_up.svg[width=70%, align="center"]

===== Network Parameters [[low-cut-ethernet-network-parameters]]
By using configuration parameters on Bus Terminal-level, Network FMUs can be parameterized by the user or Bus Simulation (e.g., by using the parameter propagation mechanism).
This chapter specifies the configuration parameters that should exist on an Ethernet Bus Terminal.

====== Bus Notification Parameter [[low-cut-ethernet-bus-notification-parameter]]
For a detailed simulation, a Network FMU needs information about whether a frame has been sent or whether a bus error has occurred.
A Bus Simulation can simulate these effects by sending bus notifications in terms of <<low-cut-ethernet-confirm-operation, `Confirm-`>> and <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operations to the Network FMUs.

However, in scenarios where Network FMUs are connected directly to each other, or where the Bus Simulation does not simulate such effects, it must be possible to configure the Network FMU such that it does not wait for any response after a <<low-cut-ethernet-transmit-operation, `Transmit`>> operation.
Therefore, a parameter with `memberName = "BusNotifications"` can be added within the Ethernet-specific  <<low-cut-configuration-terminal,Configuration Terminal>>. +
If a Network FMU supports bus notifications, the <<low-cut-ethernet-bus-notification-parameter, `BusNotifications`>> parameter shall be exposed.
The default value of this parameter shall be `false`. +
_[The default value `false` allows a simple integration of Network FMUs to simulation scenarios where <<low-cut-ethernet-confirm-operation, `Confirm-`>> or <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operations are not used.]_

Only Network FMUs with the corresponding optionally exposed <<low-cut-ethernet-bus-notification-parameter, `BusNotifications`>> parameter set to `fmi3True` might wait for <<low-cut-ethernet-confirm-operation, `Confirm-`>> and <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operations and respond accordingly; otherwise Network FMUs must not wait ("fire-and-forget").
Even if the Network FMU does not expect bus notifications, i.e. <<low-cut-ethernet-bus-notification-parameter, `BusNotifications`>> variable was not set to `fmi3True`, but receives them, it shall ignore them, i.e. it shall not report warnings or errors.

.Parameter to configure bus notifications within an Ethernet Bus Terminal of Network FMUs.
[[figure-fmu-ethernet-bus-notifications-parameter]]
----
 memberName:    BusNotifications
 type:          Boolean
 causality:     parameter
 variability:   fixed
 start:         false
----

A Bus Simulation FMU shall indicate via a variable with `memberName = "BusNotifications"` within the Ethernet-specific  <<low-cut-configuration-terminal,Configuration Terminal>> whether it provides bus notifications or not.
If the provision of bus notifications can be configured (e.g., via a structural parameter), the attributes of the <<low-cut-ethernet-bus-notification-parameter, `BusNotifications`>> variable shall contain `causality = "calculatedParameter"` and `variability = "fixed"`; or `causality = "output"` and `variability = "constant"` otherwise.

.Parameter to configure bus notifications within an Ethernet Bus Terminal of the Bus Simulation.
[[figure-fmu-ethernet-bus-notifications-parameter-in-bus-simulation]]
----
 memberName:    BusNotifications
 type:          Boolean
 causality:     calculatedParameter/output
 variability:   fixed/constant
----

include::4_4_4_ethernet_operations.adoc[]
