===== Operations [[low-cut-ethernet-operations]]
This section defines the specified operations for Ethernet.
The following tables provide an overview of all operations and specifies the position and length of the corresponding arguments, as well as the respective flow direction.

====== Transmit [[low-cut-ethernet-transmit-operation]]
Represents the transmission of an Ethernet frame or MAC Merge Packet (mPacket).

.Detailed description of the Transmit operation.
[#table-fmi3-ls-bus-ethernet-transmit-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Transmit
h|Description 3+| Indicates the transmission of an Ethernet frame or mPacket.
h|OP Code [hex] 3+| 0x10
.11+h|Content h|Argument h|Length h|Description

| OP Code
| 4 bytes
| Type of the operation.

| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 26 + Data Length`.

| Start Delimiter
| 1 byte
| The start frame (SFD) or start mPacket (SMD) delimiter.
Always set to 0xD5 for ordinary Ethernet frames when not using preemption/fragmentation.

| Fragment Counter
| 1 byte
| Fragment counter of the continuation mPacket.
Must be set to 0, if this is not a continuation mPacket.

| Last Fragment
| 1 byte
| Indicates whether this is the last fragment of a fragmented Ethernet frame.
Must be set to `TRUE` if this is a full Ethernet frame.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.

| Destination Address
| 6 bytes
| The destination address of the frame.
Only applicable if this is a full Ethernet frame or the first fragment of an Ethernet frame.

| Source Address
| 6 bytes
| The destination address of the frame.
Only applicable if this is a full Ethernet frame or the first fragment of an Ethernet frame.

| EtherType or Length
| 2 bytes
| Indicates the type of Ethernet frame (Ethernet II) or frame length (802.3).

| Data Length
| 1 byte
| The length of the data of this Ethernet frame or mPacket.
Note that this does not correspond to a field in the Ethernet frame.

| Data
| n bytes
| The payload data of the Ethernet frame or mPacket.

h|Behavior
3+|#TODO#

|====

====== Confirm [[low-cut-ethernet-confirm-operation]]
The <<low-cut-ethernet-confirm-operation, `Confirm`>> operation is used to indicate the successful transmission of an Ethernet frame by a Network FMU.

.Detailed description of the Confirm operation.
[#table-fmi3-ls-bus-ethernet-confirm-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Confirm
h|Description 3+| Indicates the successful transmission of an Ethernet frame.
h|OP Code [hex] 3+| 0x15
.3+h|Content h|Argument h|Length h|Description

| OP Code
| 4 bytes
| Type of the operation.

| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 8`.

h|Behavior
3+|#TODO#

|====

====== Format Error [[low-cut-ethernet-format-error-operation]]
Represents a format error that indicates a syntax or content error of receiving operations.
See <<low-cut-format-error-operation, `Format Error`>> for definition.

====== Bus Error [[low-cut-ethernet-bus-error-operation]]
The <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation is used to indicate a bus communication error.
Bus errors are delivered to every participant in the network.

.Detailed description of the Bus Error operation.
[#table-fmi3-ls-bus-ethernet-bus-error-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Bus Error
h|Description 3+| Indicates an error during the transmission of an Ethernet frame. #TODO. To be defined.#
h|OP Code [hex] 3+| 0x16
.5+h|Content h|Argument h|Length h|Description

| OP Code
| 4 bytes
| Type of the operation.

| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 10`.

| Error Code
| 1 byte
| Represents the specified bus error to simulate.
See <<table-fmi3-ls-bus-ethernet-bus-error-code-values>> for possible values.

| Is Sender
| 1 byte
| Indicates whether this bus error occurs in response to a transmission of this FMU.

h|Behavior
3+|#TODO#

|====

.Valid values for the bus error code.
[#table-fmi3-ls-bus-ethernet-bus-error-code-values]
[cols="2,1,5"]
|====

h|Name h|Value h|Description
|[[table-fmi3-ls-bus-ethernet-bus-error-code-values-unknown]]UNKNOWN|0x0|Unknown error. #TODO#
|[[table-fmi3-ls-bus-ethernet-bus-error-code-values-medium-busy]]MEDIUM_BUSY|0x1|The medium is currently busy.
|[[table-fmi3-ls-bus-ethernet-bus-error-code-values-collision]]COLLISION|0x2|A frame collided during transmission.

|====

====== Configuration [[low-cut-ethernet-configuration-operation]]
Represents the transmission of a continuation mPacket.

.Detailed description of the Configuration operation.
[#table-fmi3-ls-bus-ethernet-configuration-operation]
[cols="6,1,5,4,3,20"]
|====
h|Name 5+| Configuration
h|Description 5+| Provides information to configure the Ethernet bus.
h|OP Code [hex] 5+| 0x20
.8+h|Content 3+h|Argument h|Length h|Description

3+| OP Code
| 4 bytes
| Type of the operation.

3+| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 9 + Length of parameter arguments in bytes`.

3+| Parameter Type
| 1 byte
| Defines the current configuration parameter.

.4+h|
4+h|Parameter

.3+|SUPPORTED_PHY_TYPES
| MDI Mode
| 1 bytes
| The configuration of the node's media-dependent interface.
See <<table-fmi3-ls-bus-ethernet-mdi-mode-values>> for possible values.

| Number of supported PHY types
| 1 bytes
| The number of characters in the list of supported PHY types.

| Supported PHY types
| 1 bytes
| An array of zero-terminated strings describing PHY types supported by this Ethernet node.
The first element in this list indicates the type of PHY used by this node.
The list must have at least one element.
Elements describing a PHY standardized by 802.3 or an amendment must use the value described in the chapter "30.3.2.1.2 aPhyType" of the standard.
Otherwise, a vendor-defined value may be used.

h|Behavior
5+|#TODO#

|====

.Valid values for the configuration parameter type.
[#table-fmi3-ls-bus-ethernet-config-parameter-type-values]
[cols="2,1,5"]
|====

h|Name h|Value h|Description
|[[table-fmi3-ls-bus-ethernet-config-parameter-type-values-supported-phy-types]]SUPPORTED_PHY_TYPES|0x0|Indicates the supported Ethernet PHYs of this node.

|====

.Valid values for the MDI mode.
[#table-fmi3-ls-bus-ethernet-mdi-mode-values]
[cols="2,1,5"]
|====

h|Name h|Value h|Description
|[[table-fmi3-ls-bus-ethernet-mdi-mode-values-none]]NONE|0x0|Not applicable
|[[table-fmi3-ls-bus-ethernet-mdi-mode-values-mdi]]MDI|0x1|The MDI is wired in normal configuration.
|[[table-fmi3-ls-bus-ethernet-mdi-mode-values-mdi-x]]MDI_X|0x2|The MDI is wired in crossover configuration.
|[[table-fmi3-ls-bus-ethernet-mdi-mode-values-auto-mdi-x]]AUTO_MDI_X|0x3|The node supports auto MDI/MDI-X.

|====

====== Auto-Negotiation Base Page [[low-cut-ethernet-auto-negotatiation-base-page-operation]]
Represents the transmission of an auto-negotiation base page according to section 28 of <<IEEE-802.3-2022>>.

.Detailed description of the Auto-Negotiation Base Page operation.
[#table-fmi3-ls-bus-ethernet-auto-negotatiation-base-page-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Auto Negotatiation Base Page
h|Description 3+| Base page for section 28 auto-negotiation.
h|OP Code [hex] 3+| 0x30
.9+h|Content h|Argument h|Length h|Description

| OP Code
| 4 bytes
| Type of the operation.

| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 17`.

| Selector
| 1 byte
| Selector field (5 bits for section 28)

| Technology Ability
| 4 bytes
| Technology ability (7 bits for section 28)

| Extended Next Page
| 1 byte
| Indicates the support for extended next pages.
(1 bit for section 28)

| Remote Fault
| 1 byte
| Remote fault indicator.
(1 bit for section 28)

| Ack
| 1 byte
| Acknowledgement.
(1 bit for section 28) Reserved.
Must be `FALSE`.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.

| Next Page
| 1 byte
| Indicates the presence of a next page.
(1 bit for section 28)

h|Behavior
3+|#TODO#

|====

====== Single Differential Pair Auto-Negotiation Base Page [[low-cut-ethernet-single-differential-pair-auto-negotatiation-base-page-operation]]
Represents the transmission of an auto-negotiation base page according to section 98 of <<IEEE-802.3-2022>>.

.Detailed description of the Single Differential Pair Auto-Negotiation Base Page operation.
[#table-fmi3-ls-bus-ethernet-single-differential-pair-auto-negotatiation-base-page-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Single Differential Pair Auto Negotatiation Base Page
h|Description 3+| Base page for section 98 auto-negotiation.
h|OP Code [hex] 3+| 0x31
.13+h|Content h|Argument h|Length h|Description

| OP Code
| 4 bytes
| Type of the operation.

| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 21`.

| Selector
| 1 byte
| Selector field (5 bits for section 98)

| Echoed Nonce
| 1 byte
| Echoed nonce (5 bits for section 98) Reserved.
Must be zeros.

| Symmetric Pause Capability Indication
| 1 byte
| Symmetric Pause capability (2 bits for section 98) Bit 0

| Asymmetric Pause Capability Indication
| 1 byte
| Asymmetric Pause capability (2 bits for section 98) Bit 1

| Force Master/Slave
| 1 byte
| Force master/slave (1 bit for section 98)

| Remote Fault
| 1 byte
| Indicates a remote fault.
(1 bit for section 98)

| Ack
| 1 byte
| Acknowledgement.
(1 bit for section 98) Reserved.
Must be `FALSE`.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.

| Next Page
| 1 byte
| Indicates the presence of a next page (1 bit for section 98)

| Transmitted Nonce
| 1 byte
| Transmitted nonce (5 bits for section 98)

| Technology Ability
| 4 bytes
| Technology ability (27 bits for section 98)

h|Behavior
3+|#TODO#

|====

====== Auto-Negotiation Page [[low-cut-ethernet-auto-negotatiation-page-operation]]
Represents the transmission of an auto-negotiation (next) page according to section 28 or section 98 of <<IEEE-802.3-2022>>.

.Detailed description of the Auto-Negotiation Page operation.
[#table-fmi3-ls-bus-ethernet-auto-negotiation-page-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Auto Negotiation Page
h|Description 3+| Next page for section 28 or 98 auto-negotiation.
h|OP Code [hex] 3+| 0x35
.11+h|Content h|Argument h|Length h|Description

| OP Code
| 4 bytes
| Type of the operation.

| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 24`.

| Message Page
| 1 byte
| Indicates whether this is a message page.

| Extended Page
| 1 byte
| Indicates that this is an extended page (section 28).
Must always be `TRUE` when using section 98 auto-negotation.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.

| Message Code
| 2 bytes
| Message code field.
(11 bits for section 28 message page) (11 bits for section 28 extended message page) (0 bits for section 28 unformatted page) (0 bits for section 28 extended unformatted page) (11 bits for section 98 message page) ( 0 bits for section 98 unformatted page) The unused upper bits must be set to zero.

| Unformatted Code
| 8 bytes
| Unformatted code field.
(0 bits for section 28 message page) (11 bits for section 28 unformatted page) (32 bits for section 28 extended message page) (43 bits for section 28 extended unformatted page) (32 bits for section 98 message page) (43 bits for section 98 unformatted page).
The unused upper bits must be set to zero.

| Toggle
| 1 byte
| Toggle bit for synchronization.
Reserved.
Must be `FALSE`.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.

| Ack
| 1 byte
| Acknowledgement.
Reserved.
Must be `FALSE`.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.

| Ack2
| 1 byte
| Acknowledgement 2.
Reserved.
Must be `FALSE`.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.

| Next Page
| 1 byte
| Indicates the presence of a next page.

h|Behavior
3+|#TODO#

|====

====== Link State Indication [[low-cut-ethernet-link-state-indication-operation]]
Indicates the state of the physical medium attachment.

.Detailed description of the Link State Indication operation.
[#table-fmi3-ls-bus-ethernet-link-state-indication-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Link State Indication
h|Description 3+| Provides information to indicate link state.
h|OP Code [hex] 3+| 0x40
.6+h|Content h|Argument h|Length h|Description

| OP Code
| 4 bytes
| Type of the operation.

| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 74`.

| Physical Medium Attachment
| 64 bytes
| The currently used physical medium attachment as null-terminated string.
Elements describing a PHY standardized by 802.3 or an amendment must use the value described in the chapter "30.3.2.1.2 aPhyType" of the standard.
Otherwise, a vendor-defined value may be used.
If auto-negotiation is enabled but has not yet been performed, the value "unknown" should be used.

| Heartbeat
| 1 byte
| Indicates that the node is sending a regular normal link pulse or IDLE symbol.

| Master Slave Mode
| 1 byte
| Indicates whether the node is operating as `MASTER` or `SLAVE`.
See <<table-fmi3-ls-bus-ethernet-master-slave-mode-values>> for possible values.

h|Behavior
3+|#TODO#

|====

.Valid values for the master slave mode.
[#table-fmi3-ls-bus-ethernet-master-slave-mode-values]
[cols="2,1,5"]
|====

h|Name h|Value h|Description
|[[table-fmi3-ls-bus-ethernet-master-slave-mode-values-none]]NONE|0x0|Not applicable.
|[[table-fmi3-ls-bus-ethernet-master-slave-mode-values-master]]MASTER|0x1|Node is operating as Master.
|[[table-fmi3-ls-bus-ethernet-master-slave-mode-values-slave]]SLAVE|0x2|Node is operating as Slave.

|====

====== Wake Up [[low-cut-ethernet-wakeup-operation]]
Indicates wake up pulse according to TC10.

.Detailed description of the Wakeup operation.
[#table-fmi3-ls-bus-ethernet-wakeup-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Wakeup
h|Description 3+| Indicates a wakeup.
h|OP Code [hex] 3+| 0x50
.3+h|Content h|Argument h|Length h|Description

| OP Code
| 4 bytes
| Type of the operation.

| Length
| 4 bytes
| Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 8`.

h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the wake-up initiator, of the bus using the Bus Simulation.
If a Network FMU does not support wake up, this operation can be ignored on the consumer side.

|====
