==== CAN, CAN FD, CAN XL
This chapter describes the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> for CAN, CAN FD and CAN XL.
The various CAN standards CAN, CAN FD and CAN XL are considered together, because they are very similar and can also be combined in certain scenarios.

===== Overview
To simulate CAN, CAN FD and CAN XL buses, CAN-specific operations are specified based on the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>>.
Overall, the following groups of operations exists:

* Transmit: This group of operations is used to simulate a frame transmission.
There are three specializations of this operation, one each for CAN, CAN FD and CAN XL frames.
* Confirm: An acknowledgment of transmitted CAN frames is defined by the CAN standard.
The confirm operation is used to simulate this behavior.
* Error: This group of operations is used for protocol format errors and to simulate bus failures.
For example, the failure of a transmission can be indicated.
* Arbitration Lost: The operation is used by Bus Simulations to inform Network FMUs that a frame could not be transmitted immediately.
* Configuration: The configuration operation enables the configuration of bus-specific parameters and options that are required to simulate the bus behavior properly.
For example, it allows the specification of the baud rate or influencing the buffer behavior.
* Status: The Status operation is used by Networked FMUs to inform Bus Simulations about the internal state (Active/Passive/Bus Off) which concerns the reaction on bus errors.
* Wake up: CAN supports wake up and sleep scenarios.
Normally there are two ways to wake up from sleep mode: a local wake up on a specified wake-up pin, or a wake up on the CAN bus via a CAN specific wake-up pulse.
This operation is used to simulate triggering a wake up from bus side.

The following table gives a detailed overview of the available operations.
It shows all operations and the arguments they contain.

.Overview of the available operations for CAN, CAN FD and CAN XL.
[#table-operation-content-can]
[cols="9,1,6,5,5,5,5,5,5,5,5"]
|====
.2+h|Operation Name
10+h|Operation Content

h|OP Code
h|Total Length
8+h|Specific Content

|Format Error
|0x00
|:= 5 + n +
(4 byte)
8+|Data +
(n byte)

|CAN Transmit
|0x10
|:= 13 + DL +
(4 byte)
|ID +
(4 byte)
|Ide +
(1 byte)
|Rtr +
(1 byte)
|DL +
(2 byte)
4+|Data +
(n byte)

|CAN FD Transmit
|0x11
|:= 14 + DL +
(4 byte)
|ID +
(4 byte)
|Ide +
(1 byte)
|Brs +
(1 byte)
|Esi +
(1 byte)
|DL +
(2 byte)
3+|Data +
(n byte)

|CAN XL Transmit
|0x12
|:= 19 + DL +
(4 byte)
|ID +
(4 byte)
|Ide +
(1 byte)
|Sec +
(1 byte)
|SDT +
(1 byte)
|VCID +
(1 byte)
|AF +
(4 byte)
|DL +
(2 byte)
|Data +
(n byte)

|Confirm
|0x20
|:= 9 +
(4 byte)
8+|ID +
(4 byte)

|Arbitration Lost
|0x30
|:= 9 +
(4 byte)
8+|ID +
(4 byte)

|Bus Error
|0x31
|:= 12 +
(4 byte)
|ID +
(4 byte)
2+|Error Code +
(1 byte)
2+|Error Flag +
(1 byte)
3+|Is Sender +
(1 byte)

|Configuration
|0x40
|<Length> +
(4 byte)
|Kind +
(1 byte)
7+|_Dynamic Part_

|Status
|0x41
|:= 6 +
(4 byte)
8+|Status +
(1 byte)

|Wakeup
|0x42
|:= 5 +
(4 byte)
8+|---

|====

===== Operations
This section defines the specified operations for CAN, CAN FD and CAN XL.
The following tables provides an overview of all operations and specifies the position and length of the corresponding arguments, as well as the respective flow direction.

====== Transmit [[low-cut-can-transmit-operation]]
There are three types of transmit operations for transmission of CAN, CAN FD and CAN XL frame.

.Detailed description of the CAN Transmit operation.
[#table-can-transmit-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| CAN Transmit
h|Description 3+| Initiates the transmission of CAN frames.
h|OP Code [hex] 3+| 0x10
.8+h|Content h|Argument h|Length h|Description
| OP Code | 1 byte | Contains the OP Code (0x10) of the operation.
| Total Length | 4 byte | Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 13 + Data Length`.
| ID | 4 byte | The specified ID of the CAN message.
| Ide | 1 byte | Specified whether the ID should be transmitted as standard (11-bit) or extended (29-bit) message identifier.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used. 
| Rtr | 1 byte | Specifies whether the given frame represents a Remote Transmission Request frame.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.
| Data Length | 2 byte | Specifies the length of the Data argument in bytes.
| Data | n byte | Stores the given frame data to transfer, whereby the valid length of the data depends on the CAN Format.
h|Behavior
3+|The CAN Transmit operation shall be provided by Network FMUs to initiate the transmission of a CAN frame.
In case of directly connected Network FMUs (see <<common-concepts-direct-communication>>), the FMU importer forwards the operation directly to the receiving Network FMUs.
If a Bus Simulation is involved (see <<common-concepts-composition-with-dedicated-bus-simulation-fmu>> and <<common-concepts-importer-with-integrated-bus-simulation>>), the FMU importer forwards the operation initially to the Bus Simulation, where the operation is distributed with respect to the simulated bus behavior.
Depending on the simulation details, the Bus Simulation might respond with a <<low-cut-can-confirm-operation, Confirm>>, <<low-cut-can-arbitration-lost-operation, Arbitration Lost>>, <<low-cut-can-bus-error-operation, Bus Error>> or <<low-cut-can-format-error-operation, Format Error>> operation.
Depending on the <<low-cut-can-status-operation, status>> of the specified Network FMU further restrictions for CAN Transmit operations <<table-can-status-values, exist>>.

|====

.Detailed description of the CAN FD Transmit operation.
[#table-can-fd-transmit-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| CAN FD Transmit
h|Description 3+| Represents an operation for the transmission of a CAN FD frame.
h|OP Code [hex] 3+| 0x11
.9+h|Content h|Argument h|Length h|Description
| OP Code | 1 byte | Contains the OP Code (0x11) of the operation.
| Total Length | 4 byte | Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 12 + Data Length`.
| ID | 4 byte | The specified ID of the CAN message.
| Ide | 1 byte | Specified whether the ID should be transmitted as standard (11-bit) or extended (29-bit) message identifier.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.
| Brs | 1 byte | Defines the Bit Rate Switch.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.
| Esi | 1 byte | Error State indicator.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.
| Data Length | 2 byte | Specifies the length of the Data argument in bytes.
| Data | n byte | Stores the given frame data to transfer, whereby the valid length of the data depends on the CAN FD Format.
h|Behavior
3+|The CAN FD Transmit operation shall be provided by Network FMUs to initiate the transmission of a CAN FD frame.
In case of directly connected Network FMUs (see <<common-concepts-direct-communication>>), the FMU importer forwards the operation directly to the receiving Network FMUs.
If a Bus Simulation is involved (see <<common-concepts-composition-with-dedicated-bus-simulation-fmu>> and <<common-concepts-importer-with-integrated-bus-simulation>>), the FMU importer forwards the operation initially to the Bus Simulation, where the operation is distributed with respect to the simulated bus behavior.
Depending on the simulation details, the Bus Simulation might response with a <<low-cut-can-confirm-operation, Confirm>>, <<low-cut-can-arbitration-lost-operation, Arbitration Lost>>, <<low-cut-can-bus-error-operation, Bus Error>> or <<low-cut-can-format-error-operation, Format Error>> operation.
Depending on the <<low-cut-can-status-operation, status>> of the specified Network FMU further restrictions for CAN FD Transmit operations <<table-can-status-values, exist>>.

|====

.Detailed description of the CAN XL Transmit operation.
[#table-can-xl-transmit-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| CAN XL Transmit
h|Description 3+| Represents an operation for the transmission of a CAN XL frame.
h|OP Code [hex] 3+| 0x12
.11+h|Content h|Argument h|Length h|Description 
| OP Code | 1 byte | Contains the OP Code (0x12) of the operation.
| Total Length | 4 byte | Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 19 + Data Length`.
| ID | 4 byte | The specified ID of the CAN message.
| Ide | 1 byte | Specified whether the ID should be transmitted as standard (11-bit) or extended (29-bit) message identifier.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.
| Sec | 1 byte | Simple Extended Content
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.
| SDT | 1 byte | Describes the structure of the frames Data Field content (SDU type).
| VCID | 1 byte | Represents the virtual CAN network ID.
| AF | 4 byte | Represents the CAN XL Acceptance Field (AF).
| Data Length | 2 byte | Specifies the length of the Data argument in bytes.
| Data | n byte | Stores the given frame data to transfer, whereby the valid length of the data depends on the CAN XL Format.
h|Behavior
3+|The CAN XL Transmit operation shall be provided by Network FMUs to initiate the transmission of a CAN XL frame.
In case of directly connected Network FMUs (see <<common-concepts-direct-communication>>), the FMU importer forwards the operation directly to the receiving Network FMUs.
If a Bus Simulation is involved (see <<common-concepts-composition-with-dedicated-bus-simulation-fmu>> and <<common-concepts-importer-with-integrated-bus-simulation>>), the FMU importer forwards the operation initially to the Bus Simulation, where the operation is distributed with respect to the simulated bus behavior.
Depending on the simulation details, the Bus Simulation might response with a <<low-cut-can-confirm-operation, Confirm>>, <<low-cut-can-arbitration-lost-operation, Arbitration Lost>>, <<low-cut-can-bus-error-operation, Bus Error>> or <<low-cut-can-format-error-operation, Format Error>> operation.
Depending on the <<low-cut-can-status-operation, status>> of the specified Network FMU further restrictions for CAN XL Transmit operations <<table-can-status-values, exist>>.

|====

====== Confirm [[low-cut-can-confirm-operation]]
The `Confirm operation` is used to signal the successful reception of a transmitted CAN frame (see <<low-cut-can-transmit-operation, Transmit operation>>) by at least one Network FMU.

.Detailed description of the Confirm operation.
[#table-can-confirm-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Confirm
h|Description
3+|Signals successful receipt of a transmitted CAN, CAN FD and CAN XL frame to simulate a CAN acknowledgment behavior.
h|OP Code [hex]
3+|0x20
.4+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code (0x20) of the operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 9`.

|ID
|4 byte
|The ID of the confirmed CAN message.

h|Behavior
3+|The specified operation shall be produced by the Bus Simulation and consumed by Network FMUs.
If the structural parameter `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` (see <<low-cut-can-bus-notification-parameter>>) is set to `false`, the Network FMU does not rely on receiving Confirm operations.
In this case, Bus Simulations should not send Confirm operations to the Network FMU.
Depending on the <<low-cut-can-status-operation, status>> of the specified Network FMU further restrictions for Confirm operations <<table-can-status-values, exist>>.

|====

====== Format Error [[low-cut-can-format-error-operation]]
Represents a format error that indicates a syntax or content error of receiving operations.
See <<low-cut-format-error-operation, Format Error>> for definition.

====== Arbitration Lost [[low-cut-can-arbitration-lost-operation]]
The Arbitration Lost operation defines a feedback message from a Bus Simulation to a Network FMU that a <<low-cut-can-transmit-operation, Transmit operation>> could not be sent immediately due to a concurrent transmit request.

.Detailed description of the Arbitration Lost operation.
[#table-can-arbitration-lost-error-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Arbitration Lost
h|Description
3+|The Arbitration Lost operation indicates that a CAN frame could not be sent immediately and was therefore discarded by the Bus Simulation.
See <<low-cut-can-arbitration>> for further details.
h|OP Code [hex]
3+|0x30
.4+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code (0x30) of the operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 9`.

|ID
|4 byte
|The ID of the CAN message which which could not be transmitted immediately, because it loses arbitration.

h|Behavior
3+|During simulation, several <<low-cut-can-transmit-operation, Transmit operations>> can be sent by Network FMUs to a Bus Simulation at the same time.
In such case, the Bus Simulation has to decide which <<low-cut-can-transmit-operation, Transmit operation>> should proceed first.
Depending on the configuration (see the `Arbitration Lost Behavior` argument of the <<low-cut-can-configuration-operation, Configuration operation>>), the deferred <<low-cut-can-transmit-operation, Transmit operations>> shall either be buffered or discarded and sending the Arbitration Lost operation back to the respective Network FMUs.
A Network FMU receiving the Arbitration Lost operation can decide to provide the <<low-cut-can-transmit-operation, Transmit operation>> again or e.g., to raise an internal transmit timeout failure after a while.
If the structural parameter `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` (see <<low-cut-can-bus-notification-parameter>>) is set to `false`, the Network FMU does not rely on receiving Arbitration Lost operations.
In this case, Bus Simulations should not send Arbitration Lost operations to the Network FMU.

|====

====== Bus Error [[low-cut-can-bus-error-operation]]
The Bus Error operation represents special bus communication errors, which are delivered to every participant in the network.

.Detailed description of the Bus Error operation.
[#table-can-bus-error-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Bus Error
h|Description
3+|Represents an operation for simulated bus errors.
h|OP Code [hex]
3+|0x31
.7+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code (0x31) of the operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 12`.

|ID
|4 byte
|The ID of the CAN message that was transmitted while the error happened.

|Error Code
|1 byte
|The simulated bus error, based on <<table-can-error-codes, the table below>>.

|Error Flag
|1 byte
|Defines whether the Error was detected by a specified Network FMU.
For specification the boolean values `PRIMARY_ERROR_FLAG` and `SECONDARY_ERROR_FLAG` (see <<table-can-bus-error-error-flag-kinds>>) shall be used.

|Is Sender
|1 byte
|Set if the Bus Error operation is a reaction to a <<low-cut-can-transmit-operation, Transmit operation>> that was provided by the specified Network FMU from the Bus Simulation.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.

h|Behavior
3+|While transmitting CAN frames, various kinds of bus error may happen.
A Bus Simulation can simulate such errors by providing Bus Error operations to the Network FMUs.
Based on consumed Bus Error operations, Network FMUs shall maintain an internal CAN node state (see <<low-cut-can-error-handling>>).
To determine the CAN node state properly, Network FMUs need the information about their role at the time when the simulated error happened.
If a Network FMU is sending, the argument `Is Sender` shall be set.
If a Network FMU is detecting the error first, the argument `Error Flag = PRIMARY_ERROR_FLAG` shall be set.
The arguments `Is Sender` must only be set once per simulated error.
If the structural parameter `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` (see <<low-cut-can-bus-notification-parameter>>) is set to `false`, the Network FMU does not rely on receiving Bus Error operations.
In this case, Bus Simulations should not send Bus Error operations to the Network FMU.
|====

The following Error Codes are specified:

.Overview of the available error codes.
[#table-can-error-codes]
[cols="1,3,20"]
|====

h|State h|Error Code h|Description

|BIT_ERROR
|0x01
|Within the CAN standard, the sender also receives transmitted data for comparison.
If the sent and received bits are not identical, this failure results in a Bit Error.

|BIT_STUFFING_ERROR
|0x02
|A Bit Stuff Error occurs if 6 consecutive bits of equal value are detected on the bus.

|FORM_ERROR
|0x03
|Occurs during a violation of End-of-Frame (EOF) format.

|CRC_ERROR
|0x04
|Occurs when the data of a frame and the related checksum do not harmonize.

|ACK_ERROR
|0x05
|At least one receiving node identifies an invalid CAN frame.

|BROKEN_ERROR_FRAME
|0x06
|Represents an invalid transmission of a CAN Error frame.
Within CAN, an Error frame is transmitted by any unit on detection of a bus error.

|====

The following values for the Error Flag option are defined:

.Overview of the available Error Flag values.
[#table-can-bus-error-error-flag-kinds]
[cols="2,1,5"]
|====

h|Error Flag h|Value h|Description
|PRIMARY_ERROR_FLAG|0x01|Defines that a specified Network FMU is detecting the given <<low-cut-can-bus-error-operation, Bus Error>> first.
|SECONDARY_ERROR_FLAG|0x02|Defines that a specified Network FMU is reacting on a <<low-cut-can-bus-error-operation, Bus Error>> and does not detect it.

|====

====== Configuration [[low-cut-can-configuration-operation]]
The `Configuration operation` is used by Network FMUs to send simulation specific options like baud rate settings to Bus Simulations.
The following information is included within this operation: 

.Detailed description of the Configuration operation.
[#table-can-configuration-operation]
[cols="5,1,10,4,3,20"]
|====
h|Name
5+|Configuration
h|Description
5+|Represents an operation for the configuration of a Bus Simulation.
In detail, the configuration of a CAN, CAN FD and CAN XL baud rate is possible.
Also the configuration of further options, like buffer handling, is supported by this operation.
h|OP Code [hex]
5+|0x40
.9+h|Content 3+h|Argument h|Length h|Description
3+|OP Code
|1 byte
|Contains the OP Code (0x40) of the operation.

3+|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 6 + Length of parameter arguments in bytes`.

3+|Parameter Type
|1 byte
|Defines the current configuration parameter.
Note that only one parameter can be set per `Configuration operation`.

.5+h|
4+h|Parameters

|CAN_BAUDRATE
|Baudrate
|4 byte
|The CAN baudrate value to configure.
The required unit for the baudrate value is bit/s.

|CAN_FD_BAUDRATE
|Baudrate
|4 byte
|The CAN FD baudrate value to configure.
The required unit for the baudrate value is bit/s.

|CAN_XL_BAUDRATE
|Baudrate
|4 byte
|The CAN XL baudrate value to configure.
The required unit for the baudrate value is bit/s.

.1+|OPTIONS
|Arbitration Lost Behavior
|1 byte
|This parameter defines how a Bus Simulation shall behave in cases of an arbitration lost scenario.
If the option is set to `BUFFER_AND_RETRANSMIT`, <<low-cut-can-transmit-operation, Transmit operations>> shall be buffered by the Bus Simulation and no <<low-cut-can-arbitration-lost-operation, Arbitration Lost operation>> shall be sent.
If the option is set to `DISCARD_AND_NOTIFY`, the <<low-cut-can-transmit-operation, Transmit operation>> shall be discarded and an <<low-cut-can-arbitration-lost-operation, Arbitration Lost operation>> shall be sent to the Network FMU (see <<low-cut-can-arbitration>>).

h|Behavior
5+|The specified operation shall be produced by a Network FMU and consumed by the Bus Simulation.
The operation shall not be routed to other Network FMUs by the Bus Simulation.
A Network FMU shall ignore this operation on the consumer side.
Configuration operations can be produced multiple times during the runtime of a Network FMU.
In context of CAN FD, also a CAN baud rate should be configured by using `Parameter Type = CAN_BAUDRATE`.
If configuration parameters are not adjusted by a Network FMU, the Bus Simulation shall choose a default behavior by itself.
|====

The following configuration parameters are defined:

.Overview of the available configuration parameters.
[#table-can-configuration-kinds]
[cols="1,1,5"]
|====

h|Parameter h|Value h|Description
|CAN_BAUDRATE|0x01|This code indicates that a CAN baud rate should be configured for the Bus Simulation.
|CAN_FD_BAUDRATE|0x02|Allows the configuration of a CAN FD baudrate for the Bus Simulation.
|CAN_XL_BAUDRATE|0x03|Allows the configuration of a CAN XL baudrate for the Bus Simulation.
|OPTIONS|0x04|This code configures various available options for the Bus Simulation.

|====

The following values for the Arbitration Lost Behavior option are defined:

.Overview of the available Arbitration Lost Behavior values.
[#table-can-configuration-arbitration-lost-behavior-kinds]
[cols="2,1,5"]
|====

h|Arbitration Lost Behavior h|Value h|Description
|BUFFER_AND_RETRANSMIT|0x01|<<low-cut-can-transmit-operation, Transmit operations>> shall be buffered by the Bus Simulation.
|DISCARD_AND_NOTIFY|0x02|<<low-cut-can-transmit-operation, Transmit operations>> shall be discarded and the specified Network FMU shall be notified by the Bus Simulation via an <<low-cut-can-arbitration-lost-operation, Arbitration Lost operation>>.

|====

====== Status [[low-cut-can-status-operation]]
By using the `Status operation`, a Network FMU can communicate the current CAN node state to the Bus Simulation.
The following information is included within this operation: 

.Detailed description of the Status operation.
[#table-can-status-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Status
h|Description
3+|Represents an operation for status handling.
h|OP Code [hex]
3+|0x41
.4+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code (0x41) of the operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 6`.

|Status
|1 byte
|The specified status code, based on <<table-can-status-values, the table below>>.

h|Behavior
3+|The specified operation shall be produced by Network FMUs and consumed by the Bus Simulation.
The operation shall not be routed to other Network FMUs by the Bus Simulation.
A Network FMU shall ignore this operation on the consumer side.
A Network FMU shall report its status to the Bus Simulation after it changes.

|====

The following status values can be used:

.Overview of the available status values.
[#table-can-status-values]
[cols="1,1,5"]
|====

h|Kind h|Value h|Description
|ERROR_ACTIVE
|0x01
|Indicates that a simulated CAN controller within the Network FMU has currently the CAN node state: ERROR ACTIVE.
If required status is not adjusted by a Network FMU, the Bus Simulation shall choose `ERROR_ACTIVE` by itself for a specified Network FMU.

|ERROR_PASSIVE
|0x02
|Indicates that a simulated CAN controller within the Network FMU has currently the CAN node state: ERROR PASSIVE.
This node state is relevant for arbitration, because `ERROR_ACTIVE` and `ERROR_PASSIVE` nodes requires different prioritization.
See <<low-cut-can-arbitration>> for further details.

|BUS_OFF
|0x03
|Indicates that a simulated CAN controller within the Network FMU has currently the CAN node state: BUS OFF.
If a Network FMU communicates the status `BUS_OFF` to the Bus Simulation, the specified Network FMU shall not provide any new <<low-cut-can-transmit-operation, Transmission operations>> to the Bus Simulation.
If all Network FMUs, except the <<low-cut-can-transmit-operation, Transmit operation>> initiating Network FMU, communicate the status `BUS_OFF`, the Bus Simulation shall not provide a <<low-cut-can-confirm-operation, confirmation>>.

|====

====== Wake Up [[low-cut-can-wake-up-operation]]
By using the `Wakeup operation`, the underlying Bus Simulation can trigger a bus-specific wake up.

.Detailed description of the Wakeup operation.
[#table-can-wakeup-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Wakeup
h|Description
3+|Represents an operation for triggering a bus-specific wake up.
h|OP Code [hex]
3+|0x42
.3+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code (0x42) of the operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Total Length = 5`.

h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the wake-up initiator, of the bus using the Bus Simulation.
If a Network FMU does not support wake up, this operation can be ignored on the consumer side.

|====

===== Network Parameters [[low-cut-can-network-parameters]]
Using structural parameters, FMUs can be parameterized according to importer specifications.
This chapter specifies the structural parameters that each CAN-specific FMU shall provide.

====== Bus Notification Parameter [[low-cut-can-bus-notification-parameter]]
For a detailed simulation, the CAN bus behavior regarding acknowledgment, bus errors and arbitration losses must be considered.
A Bus Simulation can simulate this effect by sending bus notifications in terms of <<low-cut-can-confirm-operation, Confirm>>-, <<low-cut-can-bus-error-operation, Bus Error>>- and <<low-cut-can-arbitration-lost-operation, Arbitration Lost operations>> to the Network FMUs.
However, in cases where Network FMUs are connected directly or if a Bus Simulation does not simulate such effects, a Network FMU shall not receive these operations.

In order to inform Network FMUs not to rely on bus notifications, the importer can set the `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` parameter to `false`, which also shall be the default value.
Only if the Bus Simulation either supports <<low-cut-can-confirm-operation, Confirm>>-, <<low-cut-can-bus-error-operation, Bus Error>>- or <<low-cut-can-arbitration-lost-operation, Arbitration Lost operations>>, `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` shall be set to `true`.

.FMU parameter for the configuration of bus notifications.
[[figure-fmu-bus-notifications-parameter]]
----
    org.fmi_standard.fmi_ls_bus.WaitForBusNotification
        Description:  "Specifies whether the respective Network FMU relies on bus notifications."
        Type:         Boolean
        Causality:    structuralParameter
        Variability:  fixed
        Start:        "false"
----

This structural parameter shall only be available for Network FMUs.
A Bus Simulation (FMU) does not require this structural parameter.

===== Configuration of Bus Simulation
The configuration of the Bus Simulation is done by the Network FMUs itself.
For this purpose, the <<low-cut-can-configuration-operation, Configuration operation>> provides several configuration parameters.
<<low-cut-can-configuration-operation, Configuration operations>> can be produced multiple times during the runtime of a Network FMU.
Because the Bus Simulation shall choose a default behavior, it might be useful in several scenarios that Network FMUs finish configuration before the production of <<low-cut-can-transmit-operation, Transmit operations>>.

====== Baudrate Handling
In order to calculate the time required for the transmission of a bus message, it is necessary to inform the Bus Simulation about the specified baud rate from a Network FMU.
This baud rate information can be configured by using `CAN_BAUDRATE`, `CAN_FD_BAUDRATE` and `CAN_XL_BAUDRATE` configuration kind of the <<low-cut-can-configuration-operation, Configuration operation>>.
In a CAN FD scenario, both the configuration for `CAN_BAUDRATE` and for `CAN_FD_BAUDRATE` shall be carried out if the CAN FD bit rate switch feature is used.
Otherwise the configuration of `CAN_BAUDRATE` is sufficient for CAN FD.
The Bus Simulation can derive the required CAN, CAN FD or CAN XL controller type from the baud rate configurations a Network FMU carried out.
If the baud rate information is not adjusted by a specified Network FMU, the Bus Simulation shall choose a default behavior by itself.

====== Buffer Handling
By using the `OPTIONS` configuration kind of a <<low-cut-can-configuration-operation, Configuration operation>>, the buffer handling within the Bus Simulation can be adjusted.
Using buffer handling is required in arbitration scenarios only and will be described <<low-cut-can-arbitration, within this context>>.
If the buffering is not adjusted by a specified Network FMU, the Bus Simulation shall choose a default behavior by itself.

===== Transmission and Acknowledge
The <<low-cut-can-transmit-operation, Transmit operation>> represents the sending of a CAN, CAN FD and CAN XL frame.
With appropriate options, relevant functionalities can be configured and used on a network abstraction level (e.g., Virtual CAN network ID for CAN XL or Bit Rate Switch for CAN FD).
In the real world, flawlessly transmitted CAN frames will be acknowledged by at least one receiver CAN node.
To simulate this behavior, the <<low-cut-can-confirm-operation, Confirm operations>> were introduced.
In addition to support lightweight bus simulations and <<common-concepts-direct-communication, directly connected Network FMUs>>, the structural parameter `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` (see <<low-cut-can-bus-notification-parameter>>) has been defined.

If `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` is set to `false` (default), then Network FMUs shall not rely on receiving <<low-cut-can-confirm-operation, Confirm operations>>.
In this case, the bus simulation is idealized and takes place in a fire-and-forget manner.
If a specified Network FMU is depending on <<low-cut-can-confirm-operation, Confirm operations>> and `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` is set to `false`, the self confirmation shall be realized internally within the respective Network FMU. 

<<#figure-can-direct-communication>> illustrates this communication, whereby FMU 1 transmits network data to FMU 2.
After that, the transmission is directly confirmed by FMU 1 itself, whereby FMU 1 handles that self confirmation internally.

.Direct Confirmation of transmitted network data.
[#figure-can-direct-communication]
image::can_direct_confirmation.svg[width=40%, align="center"]

For a detailed simulation, Bus Simulations shall support <<low-cut-can-confirm-operation, Confirm operations>>.
In this case, the `org.fmi_standard.fmi_ls_bus.WaitForBusNotification` parameter of the Network FMUs shall be set to `true` and Network FMUs can rely on receiving <<low-cut-can-confirm-operation, Confirm operations>>.

The following <<#figure-can-confirmation-with-bus-simulation-fmu>> illustrates the behavior, whereby FMU 1 transmits network data to FMU 2 via a Bus Simulation.

.Confirmation of transmitted network data via Bus Simulation.
[#figure-can-confirmation-with-bus-simulation-fmu]
image::can_confirmation_with_bus_simulation_fmu.svg[width=70%, align="center"]

If all Network FMUs, except the <<low-cut-can-transmit-operation, Transmit operation>> initiating Network FMU, communicate the <<low-cut-can-status-operation, status>> `BUS_OFF`, the Bus Simulation shall not provide a <<low-cut-can-confirm-operation, confirmation>>.

<<low-cut-can-example-transmission>> contains an example of the possible transmission results and displays them in the form of a diagram.

===== Error Handling [[low-cut-can-error-handling]]
The CAN protocol includes a sophisticated fault confinement mechanism to prevent malfunctioning within CAN nodes.
A Transmit Error Counter (TEC) and a Receive Error Counter (REC) represent a historical communication quality metric.
To maintain the TEC and REC values, <<low-cut-can-bus-error-operation, Bus Error operations>> shall be provided to all Network FMUs by the Bus Simulation.
The argument `Is Sender` shall be set to `TRUE` for the Network FMU that the <<low-cut-can-transmit-operation, Transmit operation>> originated from.
The argument `Error Flag` shall be set to `PRIMARY_ERROR_FLAG` if the Network FMU detects the transmission error.
If a Network FMU changes its current CAN node state, the <<low-cut-can-status-operation, Status operation>> shall be provided to the Bus Simulation.
When a Network FMU has provided the status `BUS_OFF` to the Bus Simulation, then it also shall not provide any new <<low-cut-can-transmit-operation, Transmit operations>> to the Bus Simulation to simulate a real bus off behavior.

.Architectural error handling overview.
[#figure-can-architectural-error-handling-overview]
image::can_error_handling_overview.svg[width=100%, align="center"]

===== Arbitration [[low-cut-can-arbitration]]
Arbitration is an instrument of the CAN standard to resolve the conflict of the simultaneous sending of messages from several CAN nodes without a collision.
The arbitration is handled in the Bus Simulation and can be recognized by the fact that the Bus Simulation receives a <<low-cut-can-transmit-operation, Transmit operation>> from several FMUs at the same time.
As soon as an arbitration is lost, an <<low-cut-can-arbitration-lost-operation, Arbitration Lost operation>> shall be returned to the respective sender within the next `Event Mode` step.
As soon as an FMU loses arbitration in this way, it shall independently repeat the corresponding <<low-cut-can-transmit-operation, Transmit operation>>.

.Arbitration of two transmissions at the same time.
[#figure-can-arbitration]
image::can_arbitration.svg[width=70%, align="center"]

Within a <<low-cut-can-configuration-operation, Configuration operation>>, the `Arbitration Lost Behavior` argument can be specified.
Once this option is set to `BUFFER_AND_RETRANSMIT`, the Bus Simulation buffers the frame after losing arbitration and sends it as soon as possible.
In this case, it is not necessary for the Network FMU to trigger the respective frame to be sent again and an <<low-cut-can-arbitration-lost-operation, Arbitration Lost operation>> shall not be returned to the specific Network FMU.
If the `Arbitration Lost Behavior` is set to `DISCARD_AND_NOTIFY`, the specified Network FMU is informed by an <<low-cut-can-arbitration-lost-operation, Arbitration Lost operation>> and needs to repeat the corresponding <<low-cut-can-transmit-operation, Transmit operation>> itself.
Arbitration is available in communication cases with Bus Simulation only.

In the case of arbitration, the Bus Simulation must also take the status of the respective Network FMU into account, which is communicated via a <<low-cut-can-status-operation, Status operation>>.
To simulate the behavior of the CAN Extra Suspend Transmission Time when a CAN node is in Error Passive state, the Bus Simulation shall prefer Network FMUs whose status is `ERROR_ACTIVE` (see <<table-can-status-values>>).

<<low-cut-can-example-can-arbitration-without-buffering>> and <<low-cut-can-example-can-arbitration-with-buffering>> contain examples of the presented arbitration cases and visualize them in the form of sequence diagrams.

===== Wake Up/Sleep
This standard supports wake up and sleep for the CAN bus, whereby only the bus-specific parts are taken into account.
This means that the realization of local virtual ECU wake-up and sleeping processes are internal parts of the respective FMU, which is not covered by this document.
Because entering sleep state is a virtual ECU internal process always within CAN bus, this can be ignored.
Also, the virtual ECU local wake-up process is ignored as well.
The CAN-specific wake-up pulse can be simulated by using the <<low-cut-can-wake-up-operation, Wakeup operation>>.
A <<low-cut-can-wake-up-operation, Wakeup operation>> is initiated by one Network FMU and shall be distributed to all participants of the bus,except the wake-up initiator, by the Bus Simulation.

.Wake up initiated by FMU 1 wakes up FMU 2 and FMU 3 via bus.
[#figure-can-wake-up]
image::can_wake_up.svg[width=70%, align="center"]

===== Examples
This section contains sample sequences to clarify the facts in the CAN part.

====== Transmission [[low-cut-can-example-transmission]]
<<#figure-can-transmission-acknowledge>> illustrates the two possible results of a <<low-cut-can-transmit-operation, Transmit operation>>, whereby the transition from FMU 1 -> FMU 2 represents the successful case and FMU 2 -> FMU 1 represents the unsuccessful case.
For the second transmission, the Bus Simulation injects a failure of transmission.
In step (1), a <<low-cut-can-transmit-operation, Transmit operation>> will be delivered to the Bus Simulation.
Within step (2), the <<low-cut-can-transmit-operation, Transmit operation>> will transferred to FMU 2, so the transmission was successful.
Also in step (2), FMU 1 receives a <<low-cut-can-confirm-operation, Confirm operation>>, which means the transmission was successful.
In step (3), FMU 2 wants to transmit network data to FMU 1:
A <<low-cut-can-transmit-operation, Transmit operation>> will be delivered from FMU 2 to the Bus Simulation.
In step (4), we see that the transmission results in an <<low-cut-can-bus-error-operation, Bus Error operation>>, because the Bus Simulation injects a failure of transmission.
Based on the <<low-cut-can-bus-error-operation, Bus Error operation>> FMU 2 knows that the transmission was not successful.
Within this <<low-cut-can-bus-error-operation, Bus Error operation>>, the `Is Sender` argument is set to `TRUE` for FMU 2, because it provides the failing <<low-cut-can-transmit-operation, Transmit operation>>.
Another <<low-cut-can-bus-error-operation, Bus Error operation>> instance is provided by the Bus Simulation to FMU 1.
For FMU 1, the `Error Flag` argument is set to `PRIMARY_ERROR_FLAG`, which means that FMU detects the specified transmission error.

.Successful and unsuccessful cases of a CAN transmission.
[#figure-can-transmission-acknowledge]
image::can_transmission_acknowledge.svg[width=60%, align="center"]

Normally, transmission failure cannot occur during a simulated bus transmission.
Most common kinds of errors are used to inject transmission errors, for example using the Bus Simulation FMU, for advanced test scenarios.

====== CAN Arbitration without Buffering [[low-cut-can-example-can-arbitration-without-buffering]]
<<#figure-can-arbitration-overview>> shows the realization of a CAN arbitration by using the `Arbitration Lost Behavior` option `DISCARD_AND_NOTIFY` within the <<low-cut-can-configuration-operation, Configuration operation>>.
At the beginning, FMU 1 and FMU 2 each send network data at the same time.
In this situation, an arbitration is necessary to decide which frame should be sent in this case.
Both frames are transferred to the Bus Simulation.
Arbitration takes place within the Bus Simulation.
In the example given, the two frames with CAN ID = 15 and CAN ID = 16 are analyzed and it is decided that CAN ID = 15 wins the arbitration.
The Bus Simulation then calculates the transmission time for the CAN frame with CAN ID = 15.
The next time the FMI `Event Mode` is called up for the Bus Simulation, the corresponding CAN frame is transmitted to FMU 2 and FMU 3.
For CAN ID 16, FMU 2 is informed via an <<low-cut-can-arbitration-lost-operation, Arbitration Lost operation>> that this frame cannot be sent.
FMU 1 gets a <<low-cut-can-confirm-operation, Confirm operation>>, because the specified frame with CAN ID 15 was successfully transmitted.

.Arbitration of CAN frames within Bus Simulation.
[#figure-can-arbitration-overview]
image::can_arbitration_overview.svg[width=80%, align="center"]

====== CAN Arbitration with Buffering [[low-cut-can-example-can-arbitration-with-buffering]]
<<#figure-can-arbitration-overview-with-buffer>> shows the realization of a CAN arbitration by using the `Arbitration Lost Behavior` option `BUFFER_AND_RETRANSMIT` within the <<low-cut-can-configuration-operation, Configuration operation>>.
At the beginning, FMU 1 and FMU 2 each send network data at the same time.
In this situation, an arbitration is necessary to decide which frame should be sent in this case.
Both frames are transferred to the Bus Simulation.
Arbitration takes place within the Bus Simulation.
In the example given, the two frames with CAN ID = 15 and CAN ID = 16 are analyzed and it is decided that CAN ID = 15 wins the arbitration.
The Bus Simulation then calculates the transmission time for the CAN frame with CAN ID = 15.
The next time the FMI `Event Mode` is called up for the Bus Simulation, the corresponding CAN frame is transmitted to FMU 2 and FMU 3.
The <<low-cut-can-transmit-operation, Transmit operation>> of CAN ID 16 is buffered by the Bus Simulation and will be sent within the next time slot.
The Bus Simulation does not return an <<low-cut-can-arbitration-lost-operation, Arbitration Lost operation>> to FMU 2.
FMU 1 gets a <<low-cut-can-confirm-operation, Confirm operation>>, because the specified frame with CAN ID 15 was successfully transmitted.

.Arbitration of CAN frames with buffering within Bus Simulation.
[#figure-can-arbitration-overview-with-buffer]
image::can_arbitration_overview_with_buffer.svg[width=80%, align="center"]
