==== Ethernet [[low-cut-ethernet]]
This chapter describes the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> for Ethernet.

===== Overview [[low-cut-ethernet-overview]]

====== Scope of this standard

Ethernet support in the LS-BUS should cover both normal and automotive Ethernet.

In the Ethernet stack, similar to other busses, the LS-BUS for Ethernet cuts right above the MAC layer. Though, effects on lower layers are also modeled at an abstracted level.

TODO:

* PHY compatibility
* Link establishment
* PLCA

This standard should cover all variants of Ethernet described in IEEE 802.3-2022 while being flexible enough to support future versions without adaption.
Specifically, 100BASE-TX, 1000BASE-T, 100BASE-T1, 1000BASE-T1 and 10BASE-T1S have been evaluated in detail for this standard.
In addition, common extensions are considered.

TODO:

* Mention AVB/TSN (e.g., preemption)
* Mention OpenAlliance (e.g., TC10 wakeup/sleep)
* Reference what exactly is part of the standard, and what can be achieved on higher layers. (table?)

====== Ethernet topologies

Ethernet support both point-to-point and multidrop topologies.
In a point-to-point topology, Ethernet devices are either connected directly and more than two devices are connected using and Ethernet switch.
This topology is used for all modern Ethernet variants except 10BASE-T1S.
In a multidrop topology, multiple devices are connected to the same segment either directly, daisy-chained or interconnected via hubs.
This topology is used for legacy Ethernet standards as well as 10BASE-T1S.

In terms of the LS-BUS, each point-to-point connection or multidrop segment represents a dedicated virtual bus, which may be simulated by an independent bus simulation or combined into an consolidated simuation.
Ethernet switches can be modeled as normal FMUs, where switch ports correspond to LS-BUS terminals, to allow simulating any kind of Ethernet switch.
To simplify interconnecting Ethernet FMUs, a bus simulation may decide to incorporate the Ethernet switching instead of delegating it to a dedicated FMU.


===== Operations [[low-cut-ethernet-operations]]
This section defines the specified operations for Ethernet.
The following tables provides an overview of all operations and specifies the position and length of the corresponding arguments, as well as the respective flow direction.

====== Format Error [[low-cut-ethernet-format-error-operation]]
Represents a format error that indicates a syntax or content error of receiving operations.
See <<low-cut-format-error-operation, `Format Error`>> for definition.

====== Transmit [[low-cut-ethernet-transmit]]
Represents the transmission of an Ethernet frame or MAC Merge Packet (mPacket).

.Detailed description of the Transmit operation.
[#table-fmi3-ls-bus-ethernet-transmit-operation]
[cols="6,1,5,4,3,20"]
|====
h|Name 5+| Transmit
h|Description 5+| Indicates the transmission of an Ethernet frame or mPacket.
h|OP Code [hex] 5+| 0x10
.21+h|Content 3+h|Argument h|Length h|Description


3+| OP Code
| 4 bytes
| Type of the operation.

3+| Length
| 4 bytes
| Total length of the operation.


3+| Start delimiter
| 1 byte
| The start frame (SFD) or start mPacket (SMD) delimiter. Always set to 0xD5 for ordinary Ethernet frames when not using preemption.

3+| Destination address
| 6 bytes
| The destination address of the frame.

3+| Source address
| 6 bytes
| The destination address of the frame.

3+| EtherType or length
| 2 bytes
| Indicates the type of Ethernet frame (Ethernet II) or frame length (802.3).

3+| CRC
| 4 bytes
| The checksum of this Ethernet frame or mPacket.

3+| Data length
| 1 byte
| The length of the data of this Ethernet frame or mPacket. Note that this does not correspond to a field in the Ethernet frame.

3+| Data
| n bytes
| The payload data of the Ethernet frame or mPacket.

|====


====== Transmit verify/respond [[low-cut-ethernet-transmit-verify-respond-operation]]
Represents the transmission of a verify or reponse mPacket.

.Detailed description of the Transmit verify/respond operation.
[#table-fmi3-ls-bus-ethernet-transmit-verify-respond-operation]
[cols="6,1,5,4,3,20"]
|====
h|Name 5+| TransmitVerifyRespond
h|Description 5+| Indicates the transmission of a verify or respond mPacket.
h|OP Code [hex] 5+| 0x11
.21+h|Content 3+h|Argument h|Length h|Description


3+| OP Code
| 4 bytes
| Type of the operation.

3+| Length
| 4 bytes
| Total length of the operation.


3+| Start delimiter
| 1 byte
| The delimiter indicating the type of mPacket.

3+| CRC
| 4 bytes
| The checksum of the mPacket.

3+| Data length
| 1 byte
| The length of the data of this mPacket. Note that this does not correspond to a field in the Ethernet frame.

3+| Data
| n bytes
| The payload data of the Ethernet mPacket.

|====

====== Transmit continuation [[low-cut-ethernet-transmit-continuation-operation]]
Represents the transmission of a continuation mPacket.

.Detailed description of the Transmit continuation operation.
[#table-fmi3-ls-bus-ethernet-transmit-continuation-operation]
[cols="6,1,5,4,3,20"]
|====
h|Name 5+| TransmitContinuation
h|Description 5+| Indicates the transmission of a continuation mPacket of a fragmented Ethernet frame.
h|OP Code [hex] 5+| 0x12
.21+h|Content 3+h|Argument h|Length h|Description


3+| OP Code
| 4 bytes
| Type of the operation.

3+| Length
| 4 bytes
| Total length of the operation.


3+| Start delimiter
| 1 byte
| The delimiter indicating the type of mPacket.

3+| Fragment counter
| 1 byte
| Fragment counter of the continuation mPacket.

3+| CRC
| 4 bytes
| The checksum of the mPacket.

3+| Data length
| 1 byte
| The length of the data of this mPacket. Note that this does not correspond to a field in the Ethernet frame.

3+| Data
| n bytes
| The payload data of the Ethernet mPacket.

|====

====== Wake Up [[low-cut-ethernet-wake-up-operation]]
By using <<low-cut-ethernet-wake-up-operation, `Wakeup`>> and <<low-cut-ethernet-sleep-operation, `Sleep`>> operations, the underlying Bus Simulation can trigger a bus-specific wake up and sleep requests.

.Detailed description of the Wakeup operation.
[#table-ethernet-wakeup-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Wakeup
h|Description
3+|Represents an operation for triggering a bus-specific wake up.
h|OP Code [hex]
3+|0x42
.3+h|Content h|Argument h|Length h|Description
|OP Code
|4 byte
|Contains the OP Code (0x42) of the operation.

|Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 8`.

h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the wake-up initiator, of the bus using the Bus Simulation.
If a Network FMU does not support wake up, this operation can be ignored on the consumer side.

|====

====== Sleep [[low-cut-ethernet-sleep-operation]]
By using <<low-cut-ethernet-wake-up-operation, `Wakeup`>> and <<low-cut-ethernet-sleep-operation, `Sleep`>> operations, the underlying Bus Simulation can trigger a bus-specific wake up and sleep requests.

.Detailed description of the Sleep operation.
[#table-ethernet-sleep-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Sleep
h|Description
3+|Represents an operation for triggering a bus-specific sleep.
h|OP Code [hex]
3+|0x43
.3+h|Content h|Argument h|Length h|Description
|OP Code
|4 byte
|Contains the OP Code (0x43) of the operation.

|Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 8`.

h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the sleep requesting initiator, of the bus using the Bus Simulation.
If a Network FMU does not support sleep requests, this operation can be ignored on the consumer side.

|====

===== Network Parameters [[low-cut-ethernet-network-parameters]]
===== Configuration of Bus Simulation [[low-cut-ethernet-configuration-of-bus-simulation]]
===== Transmission [[low-cut-ethernet-transmission]]

A transmission of an Ethernet frame is modeled by a transmit operation.
The transmit operation is received by the bus simulation and forwarded to the communication partner after the transmission delay.
The bus operation then sends a confirm operation to the sender, if TODO is configured.
In case of an error, a bus error operation may be returned instead.

When using the MAC Merge sublayer (See chapter 99 of 802.3-2022),
the transmit operation can also indicate the transmission of Express frames and the initial fragment of preempted frames.
Continuation packets of a preempted frame are transmitted using the transmit continuation operation.


===== Error Handling [[low-cut-ethernet-error-handling]]
===== Wake Up/Sleep [[low-cut-ethernet-wakeup-sleep]]
This standard supports wake up and sleep functionality for the Ethernet bus, based on the TC10 Sleep/Wake-up
Specification.
Note that Wake Up/Sleep is not available for all Ethernet variants, but only for 10BASE-T1S, 100BASE-T1, 1000BASE-T1 and Multi-G BASE-T1.
However, the realization of local virtual ECU wake-up and sleeping processes, i.e., the transition to the sleep state as well as the virtual ECU local wake-up process, is considered internal to the FMU implementation.
Therefore, only the bus-related aspects are defined in this document.

The Ethernet-specific wake-up pulse can be simulated by using the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation, initiated by one Network FMU.
The Bus Simulation shall distribute this operation to all participants on the bus, excluding the wake-up initiator.

.Wake up initiated by FMU 1 wakes up FMU 2 and FMU 3 via bus.
[#figure-ethernet-wake-up]
image::ethernet_wake_up.svg[width=70%, align="center"]

Analogously, the <<low-cut-ethernet-sleep-operation, `Sleep`>> operation is used to prompt corresponding receivers to go to sleep.
The flow direction is analogous to the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation.
