==== CAN, CAN FD, CAN XL
This section describes the CAN bus specific standardization topics.
CAN as well as CAN FD, CAN XL formats are supported.
The various CAN standards CAN, CAN FD and CAN XL are considered together because they work very similarly and can also be combined in certain scenarios.

===== Overview
To realize CAN, CAN FD and CAN XL support, CAN specific operations are specified based on the <<Overview-Layered-Standard-Bus-Protocol, Layered Standard Bus Protocol>>.
Overall, the following groups of operations are specified:

* Transmit: This group of operations is used to simulate a frame transmission.
There are three specializations of this operation, one each for CAN, CAN FD and CAN XL frames.
* Confirm: During every transmission of a CAN Frame an acknowledgement slot for the receivers is provided.
The acknowledgement slot is used to acknowledge the reception of a valid CAN frame.
So for every transmitted frame a transmission acknowledge is required according to the CAN standard.
The confirm operation is used to simulate this behavior.
* Error: The Error operation is used for error handling, which can be triggered by other operations.
For example, the failure of a transmission can be indicated.
* Configuration: The configuration operation enables the configuration of bus-specific parameters and options that are required for simulating a bus transmission.
For example, it allows specifying the baud rate or influencing buffer behavior.
* Wakeup: CAN supports wake-up and sleep scenarios.
Normally there are two ways to wake up from sleep mode: a local wake up on a specified wake-up pin, or a CAN wake-up on the CAN bus via a CAN specific wake-up pulse.
This operation is used to simulate triggering a wake-up from bus side.

The following table gives a detailed overview of the available operations.
It shows all operations and the arguments they contain.

[#table-operation-content-can]
[cols="9,1,6,5,4,4,5,5,5,5,5"]
|====
.2+h|Operation type
10+h|Operation content

h|OP Code
h|Total Length
8+h|Specific content

|NOOP
|0x00
|:= 5 +
(4 byte)
8+|---

|CAN Transmit
|0x01
|:= 12 + DL +
(4 byte)
|ID +
(4 byte)
|Ide +
(1 bit)
|Rtr +
(1 bit)
|DL +
(2 byte)
4+|Data +
(n byte)

|CAN FD Transmit
|0x02
|:= 12 + DL +
(4 byte)
|ID +
(4 byte)
|Ide +
(1 bit)
|Brs +
(1 bit)
|Esi +
(1 bit)
|DL +
(2 byte)
3+|Data +
(n byte)

|CAN XL Transmit
|0x03
|:= 18 + DL +
(4 byte)
|ID +
(4 byte)
|Ide +
(1 bit)
|Sec +
(1 bit)
|SDT +
(1 byte)
|VCID +
(1 byte)
|AF +
(4 byte)
|DL +
(2 byte)
|Data +
(n byte)

|Confirm
|0x04
|:= 9 +
(4 byte)
8+|ID +
(4 byte)

|Error
|0x05
|:= 10 +
(4 byte)
|ID +
(4 byte)
7+|Error Code +
(1 byte)

|Configuration
|0x06
|<Length> +
(4 byte)
|Kind +
(1 byte)
7+|_Dynamic Part_

|Wakeup
|0x07
|:= 5 +
(4 byte)
8+|---

|====

===== Operations
This section defines the allowed operations for CAN, CAN FD, CAN XL.
The following tables provides an overview of all operations and specifies the position and length of the corresponding arguments, as well as the respective flow direction.

====== NOOP 
Represents no operation.
See <<NOOP-Operation, NOOP operation>> for definition.

====== Transmit [[TransmitOpCodeCanLowCut]]
There are three types of transmit operations, each representing the transmission of a CAN, a CAN FD and a CAN XL frame.

[cols="5,4,3,20"]
|====
h|Name 3+| CAN Transmit
h|Description 3+| Represents an operation for the transmission of a CAN frame.
h|OP Code [hex] 3+| 0x01
.9+h|Content h|Argument h|Length h|Description
| OP Code | 1 byte | Contains the OP Code of the specified operation.
| Total Length | 4 byte | Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Total Length = 12 + Data Length`.
| ID | 4 byte | The specified ID of the CAN message.
The maximum length of an ID is 11-bit and 29-bit if Identifier Extension (Ide) is used.
| Ide | 1 bit | Specifies if CAN Identifier Extension is used or not.
| Rtr | 1 bit | Specifies if the given frame represents an Remote Transmission Request frame.
| - | 6 bit | Reserved for future usage.
| Data Length | 2 byte | Specifies the length of the Data argument in bytes.
| Data | n byte | Stores the given frame data to transfer, whereby the valid length of the data depends on the CAN Format.
h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the transmission initiator, of the bus by the Bus Simulation.
Within the <<Composition-with-dedicated-Bus-Simulation-FMU, Composition with dedicated Bus Simulation FMU>> and <<BusFeatureIntegratedFmuSimulator, Importer with Integrated Bus Simulation>> communication use case every <<TransmitOpCodeCanLowCut, Transmission operation>> transferred to a Bus Simulation has a result in form of either a <<ConfirmOpCodeCanLowCut, positive confirmation>> if the transmission was successful or an <<ErrorOpCodeCanLowCut, error>> including a specified error code if the transmission was not successful.
The next <<TransmitOpCodeCanLowCut, Transmission operation>> shall only be sent as soon as there is a confirmation or an error.

|====

[cols="5,4,3,20"]
|====
h|Name 3+| CAN FD Transmit
h|Description 3+| Represents an operation for the transmission of a CAN FD frame.
h|OP Code [hex] 3+| 0x02
.10+h|Content h|Argument h|Length h|Description
| OP Code | 1 byte | Contains the OP Code of the specified operation.
| Total Length | 4 byte | Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Total Length = 12 + Data Length`.
| ID | 4 byte | The specified ID of the CAN message.
The maximum length of an ID is 11-bit and 29-bit if Identifier Extension (Ide) is used.
| Ide | 1 bit | Specifies if CAN Identifier Extension is used or not.
| Brs | 1 bit | Defines the Bit Rate Switch.
| Esi | 1 bit | Error State indicator.
| - | 5 bit | Reserved for future usage.
| Data Length | 2 byte | Specifies the length of the Data argument in bytes.
| Data | n byte | Stores the given frame data to transfer, whereby the valid length of the data depends on the CAN FD Format.
h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the transmission initiator, of the bus by the Bus Simulation.
Within the <<Composition-with-dedicated-Bus-Simulation-FMU, Composition with dedicated Bus Simulation FMU>> and <<BusFeatureIntegratedFmuSimulator, Importer with Integrated Bus Simulation>> communication use case every <<TransmitOpCodeCanLowCut, Transmission operation>> transferred to a Bus Simulation has a result in form of either a <<ConfirmOpCodeCanLowCut, positive confirmation>> if the transmission was successful or an <<ErrorOpCodeCanLowCut, error>> including a specified error code if the transmission was not successful.
The next <<TransmitOpCodeCanLowCut, Transmission operation>> shall only be sent as soon as there is a confirmation or an error.

|====

[cols="5,4,3,20"]
|====
h|Name 3+| CAN XL Transmit
h|Description 3+| Represents an operation for the transmission of a CAN XL frame.
h|OP Code [hex] 3+| 0x03
.12+h|Content h|Argument h|Length h|Description 
| OP Code | 1 byte | Contains the OP Code of the specified operation.
| Total Length | 4 byte | Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Total Length = 18 + Data Length`.
| ID | 4 byte | The specified ID of the CAN message.
The maximum length of an ID is 11-bit and 29-bit if Identifier Extension (Ide) is used.
| Ide | 1 bit | Specifies if CAN Identifier Extension is used or not.
| Sec | 1 bit | Simple Extended Content
| - | 6 bit | Reserved for future usage.
| SDT | 1 byte | Describes the structure of the frames Data Field content (SDU type).
| VCID | 1 byte | Represents the virtual CAN network ID.
| AF | 4 byte | Represents the CAN XL Acceptance Field (AF).
| Data Length | 2 byte | Specifies the length of the Data argument in bytes.
| Data | n byte | Stores the given frame data to transfer, whereby the valid length of the data depends on the CAN XL Format.
h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the transmission initiator, of the bus by the Bus Simulation.
Within the <<Composition-with-dedicated-Bus-Simulation-FMU, Composition with dedicated Bus Simulation FMU>> and <<BusFeatureIntegratedFmuSimulator, Importer with Integrated Bus Simulation>> communication use case every <<TransmitOpCodeCanLowCut, Transmission operation>> transferred to a Bus Simulation has a result in form of either a <<ConfirmOpCodeCanLowCut, positive confirmation>> if the transmission was successful or an <<ErrorOpCodeCanLowCut, error>> including a specified error code if the transmission was not successful.
The next <<TransmitOpCodeCanLowCut, Transmission operation>> shall only be sent as soon as there is a confirmation or an error.

|====

====== Confirm [[ConfirmOpCodeCanLowCut]]
The `Confirm operation` represents the confirmation of a transmitted frame (see <<TransmitOpCodeCanLowCut, Transmit operation>>).
For every frame, which is successfully transmitted via `Transmit operation`, a `Confirm operation` is expected.
The following information are included within this operation: 

[cols="5,4,3,20"]
|====
h|Name
3+|Confirm
h|Description
3+|Represents an operation to confirm the transmission of a CAN, CAN FD and CAN XL frame to simulate a CAN acknowledgement.
h|OP Code [hex]
3+|0x04
.4+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code of the specified operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Total Length = 9`.

|ID
|4 byte
|The specified ID of the CAN message that should be confirmed.

h|Behavior
3+|The specified operation shall be produced by the Bus Simulation and consumed by a Network FMU.
If `org.fmi-standard.fmi-ls-bus.DirectConfirmation` (see <<direct-confirmation-parameter>>) is set to stem:[true] the confirmation of the transmitted network data shall be directly done by the sender itself.
Otherwise the confirmation of the transmitted network data shall be done by the Bus Simulation.

|====

====== Error [[ErrorOpCodeCanLowCut]]
By using the `Error operation` the Bus Simulation can communicate an error for a specific <<TransmitOpCodeCanLowCut, Transmission operation>>.
The following information are included within this operation: 

[cols="5,4,3,20"]
|====
h|Name
3+|Error
h|Description
3+|Represents an operation for error handling.
h|OP Code [hex]
3+|0x05
.5+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code of the specified operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Total Length = 10`.

|ID
|4 byte
|The specified ID of the CAN message which triggers the error.

|Error Code
|1 byte
|The specified error code, basing on the table below.

h|Behavior
3+|The specified operation shall be produced by the Bus Simulation and consumed by a Network FMU.

|====

The following codes are allowed to use as Error Code: 

[cols="1,1,5"]
|====

h|State h|Error Code h|Description
|ARBITRATION_LOST|0x01|Represents an arbitration lost error, which shall be used if a specific frame initiated by a <<TransmitOpCodeCanLowCut, Transmit operation>> lost the arbitration.
See <<CanArbitration>> for further details.
|OPERATION_ERROR|0x40|Represents a generic operation error, which can be initiated by every operation.
This error shall be used when generally encountering a problem with the syntax or content of an operation.
|COMMUNICATION_ERROR|0x80|Represents a generic transmission error initiated by a <<TransmitOpCodeCanLowCut, Transmit operation>>.
|BIT_ERROR|0x81|Represents an error that the bit received is not the same as the bit transmitted.
Within CAN the sender always receives its transmitted data for a comparison.
If the sent and received bits are not identical this situation results in a Bit Error.
This error case cannot occur during a simulated bus transmission.
The error is used to inject transmission errors, for example using the Bus Simulation, for advanced test scenarios.
The given error is always related to a specific <<TransmitOpCodeCanLowCut, Transmit operation>>.
|BIT_STUFFING_ERROR|0x82|A Bit Stuff Error occurs if 6 consecutive bits of equal value are detected on the bus.
This error case cannot occur during a simulated bus transmission.
The error is used to inject transmission errors, for example using the Bus Simulation, for advanced test scenarios.
The given error is always related to a specific <<TransmitOpCodeCanLowCut, Transmit operation>>.
|FORM_ERROR|0x83|Occurs during a violation of End-of-Frame (EOF) format.
This error case cannot occur during a simulated bus transmission.
The error is used to inject transmission errors, for example using the Bus Simulation, for advanced test scenarios.
The given error is always related to a specific <<TransmitOpCodeCanLowCut, Transmit operation>>.
|CRC_ERROR|0x84|Represents an CRC Error, so if the data of a frame and the related checksum not harmonize.
This error case cannot occur during a simulated bus transmission.
The error is used to inject transmission errors, for example using the Bus Simulation, for advanced test scenarios.
The given error is always related to a specific <<TransmitOpCodeCanLowCut, Transmit operation>>.
|ACK_ERROR|0x85|At least one receiving node identifies an invalid CAN frame.
This error case cannot occur during a simulated bus transmission.
The error is used to inject transmission errors, for example using the Bus Simulation, for advanced test scenarios.
The given error is always related to a specific <<TransmitOpCodeCanLowCut, Transmit operation>>.
|====

====== Configuration [[ConfigurationCanOpCode]]
The `Configuration operation` allows Network FMUs the configuration of the Bus Simulation with parameters like baud rate information and further options.
The following information are included within this operation: 

[cols="5,1,10,4,3,20"]
|====
h|Name
5+|Configuration
h|Description
5+|Represents an operation for the configuration of a Bus Simulation.
In detail the configuration of a CAN, CAN FD and CAN XL baud rate is possible.
Also the configuration of further options, like buffer handling, is supported by this operation.
h|OP Code [hex]
5+|0x06
.10+h|Content 3+h|Argument h|Length h|Description
3+|OP Code
|1 byte
|Contains the OP Code of the specified operation.

3+|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.

3+|Kind
|1 byte
|Defines the kind of configuration.

.6+h|
4+h|Values

|CAN_BAUDRATE
|Baudrate
|4 byte
|The specified baudrate value to configure, whereby the specified ranges are defined by the CAN standard.
The required unit for the baudrate value is bit/s.

|CAN_FD_BAUDRATE
|Baudrate
|4 byte
|The specified baudrate value to configure, whereby the specified ranges are defined by the CAN FD standard.
The required unit for the baudrate value is bit/s.

|CAN_XL_BAUDRATE
|Baudrate
|4 byte
|The specified baudrate value to configure, whereby the specified ranges are defined by the CAN XL standard.
The required unit for the baudrate value is bit/s.

.2+|OPTIONS
|Buffer
|1 bit
|If a specified CAN message ID looses arbitration, this parameter defines if the given <<TransmitOpCodeCanLowCut, Transmission operation>> shall be buffered by the Bus Simulation or shall be removed and the FMU has to trigger the transmission again.
The parameter value is defined as stem:[true = 0] and stem:[false = 1].

|-
|7 bit
|Reserved for future usage.

h|Behavior
5+|The specified operation shall be produced by a Network FMU and consumed by the Bus Simulation.
The operation shall not be routed to other Network FMUs by the Bus Simulation.
A Network FMU shall ignored this operation on consumer side.
The configuration shall be completed by a specified Network FMU before it produces any <<TransmitOpCodeCanLowCut, Transmission operation>>.
Any configuration can be repeated multiple times during the runtime of a Network FMU.
In context of CAN FD, also a CAN baud rate should always be configured by using `Kind = CAN_BAUDRATE`.
If required configuration parameters are not adjusted by a Network FMU the Bus Simulation shall choose a default behavior by itself.
|====

The following Kind values are allowed to be used: 

[cols="1,1,5"]
|====

h|Kind h|Value h|Description
|CAN_BAUDRATE|0x01|This code indicates that a CAN baud rate should be configured for the Bus Simulation.
|CAN_FD_BAUDRATE|0x02|Allows the configuration of a CAN FD baudrate for the Bus Simulation.
|CAN_XL_BAUDRATE|0x03|Allows the configuration of a CAN XL baudrate for the Bus Simulation.
|OPTIONS|0x04|This code configures various available options for the Bus Simulation.

|====

====== Wake-up [[WakeupCanOpCode]]
By using the `Wakeup operation` the underlying Bus Simulation can trigger a bus-specific wake up.

[cols="5,4,3,20"]
|====
h|Name
3+|Wakeup
h|Description
3+|Represents an operation for triggering a bus-specific wake up.
h|OP Code [hex]
3+|0x07
.3+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code of the specified operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Total Length = 5`.

h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the wake-up initiator, of the bus by using the Bus Simulation.
If a Network FMU does not support wake-up this operation can be ignored on consumer side.

|====

===== Configuration of Bus Simulation
The configuration of the Bus Simulation is done by the specified Network FMUs itself.
For this purpose, a <<ConfigurationCanOpCode, Configuration operation>> is specified with several configuration kinds.
The initial configuration of the Bus Simulation shall be completed by a Network FMU before the first transmission is triggered.
The configuration may be repeated multiple times during the runtime of a Network FMU.

====== Baudrate Handling
In order to calculate the time required for the transmission of a bus message, it is necessary to inform the Bus Simulation about the specified baud rate from a Network FMU.
This baud rate information can be configured by using `CAN_BAUDRATE`, `CAN_FD_BAUDRATE` and `CAN_XL_BAUDRATE` configuration kind of the <<ConfigurationCanOpCode, Configuration operation>>.
In a CAN FD scenario, both the configuration for `CAN_BAUDRATE` and for `CAN_FD_BAUDRATE` shall be carried out if the CAN FD bit rate switch feature is used.
Otherwise the configuration of `CAN_BAUDRATE` is sufficient for CAN FD.
The Bus Simulation can derive the required CAN, CAN FD or CAN XL controller type from the baud rate configurations a Network FMU carried out.
If the baud rate information is not adjusted by a specified Network FMU the Bus Simulation shall choose a default behavior by itself.

====== Buffer Handling
By using the `OPTIONS` configuration kind of a <<ConfigurationCanOpCode, Configuration operation>> the buffer handling within the Bus Simulation can be adjusted.
Using buffer handling is required in arbitration scenarios only and will be described <<CanArbitration, within this context>>.
If the buffering is not adjusted by a specified Network FMU the Bus Simulation shall choose a default behavior by itself.

===== Transmission and Acknowledge
The <<TransmitOpCodeCanLowCut, Transmission operation>> represents the sending of a CAN, CAN FD and CAN XL frame.
With appropriate options, relevant functionalities can be configured and used on a network abstraction level (e.g. Virtual CAN network ID for CAN XL or Bit Rate Switch for CAN FD).
For realization of the CAN transmission acknowledge feature a Transmit/Confirm pattern is used.
For CAN, the transmission of network data consists of exactly two phases.
In the first phase, the specific network data are send.
In the second step, the sender receives feedback if the transmission was successful or not.
In the case of an unsuccessful transmission, a reason for the faulty transmission is also provided.
Depending on the reason of faulty transmission the sender can decide if the specified transmission shall be repeated or not.

This directly means that every <<TransmitOpCodeCanLowCut, Transmission operation>> transferred to a Bus Simulation has a result either in form of a <<ConfirmOpCodeCanLowCut, positive confirmation>> if the transmission was successful or an <<ErrorOpCodeCanLowCut, error>> if the transmission was not successful.
The next <<TransmitOpCodeCanLowCut, Transmission operation>> shall only be sent as soon as there is a confirmation or an error.
If `org.fmi-standard.fmi-ls-bus.DirectConfirmation` (see <<direct-confirmation-parameter>>) is set to stem:[true] the confirmation of the transmitted network data shall be directly done by the sender itself.
Otherwise the confirmation of the transmitted network data shall be done by the Bus Simulation.

<<#figure-can-direct-communication>> illustrates this communication, whereby FMU 1 transmits network data to FMU 2.
After that the transmission is directly confirmed by FMU 1 itself.

.Direct Confirmation of transmitted network data.
[#figure-can-direct-communication]
image::principles_of_communication_direct.svg[width=40%, align="center"]

If a Bus Simulation is used the confirmation is done by the Bus Simulation itself.
The following <<#figure-can-confirmation-with-bus-simulation-fmu>> illustrates the behavior, whereby FMU 1 transmits network data to FMU 2 via a Bus Simulation.

.Confirmation of transmitted network data via Bus Simulation.
[#figure-can-confirmation-with-bus-simulation-fmu]
image::can_confirmation_with_bus_simulation_fmu.svg[width=70%, align="center"]

<<example-can-possible-results-of-transmission>> contains an example of the possible transmission results and visualize them in the form of a diagram.

===== Arbitration [[CanArbitration]]
Arbitration is an instrument of the CAN standard to resolve the conflict of the simultaneous sending of messages from several CAN nodes without a collision.
The arbitration is handled completely in the Bus Simulation and can be recognized by the fact that the Bus Simulation receives a <<TransmitOpCodeCanLowCut, Transmission operation>> from several FMUs in the same step.
As soon as an arbitration is lost, an <<ErrorOpCodeCanLowCut, Error operation>> with `Error Code = ARBITRATION_LOST` must be returned to the respective sender within the next `Event Mode` step.
As soon as an FMU loses arbitration in this way, it shall independently repeat the corresponding <<TransmitOpCodeCanLowCut, Transmission operation>>.

.Arbitration of two transmissions at the same time.
[#figure-can-arbitration]
image::can_arbitration.svg[width=70%, align="center"]

Within a <<ConfigurationCanOpCode, Configuration operation>>, the `Buffer` argument can be specified.
Once this is set, the Bus Simulation buffers the frame after losing arbitration and sends it as soon as possible.
When using this parameter, it is therefore not necessary for the FMU to trigger the respective frame to be sent again.
In this scenario the <<ErrorOpCodeCanLowCut, Error operation>> with `Error Code = ARBITRATION_LOST` shall not be returned to the specific FMU.
Arbitration is available in communication cases with Bus Simulation only.

<<example-can-arbitration>> and <<example-can-arbitration-with-buffer-option>> contain examples of the presented arbitration cases and visualize them in the form of sequence diagrams.

===== Wake-up/Sleep
This standard supports wake-up and sleep for the CAN bus, whereby only the bus-specific parts are taken into account.
This means that the realization of local virtual ECU wake-up and sleeping processes are internal parts of the respective FMU, which is not covered by this document.
Because entering sleep state is a virtual ECU internal process always within CAN bus, this can be ignored.
Also the virtual ECU local wake-up process is ignored as well.
The CAN specific wake-up pulse can be simulated by using the <<WakeupCanOpCode, Wake-up operation>>.
A <<WakeupCanOpCode, Wake-up operation>> is initiated by one Network FMU and shall be distributed to all participants of the bus by the Bus Simulation, except the wake-up initiator.

.Wake-up initiated by FMU 1 wakes-up FMU 2 and FMU 3 via bus.
[#figure-can-wake-up]
image::can_wake_up.svg[width=70%, align="center"]

===== Examples
This section contains sample sequences to clarify the facts in the CAN part.

====== Transmission [[example-can-possible-results-of-transmission]]
<<#figure-can-transmission-acknowledge>> illustrates the two possible results of a <<TransmitOpCodeCanLowCut, Transmission operation>>, whereby the transition from FMU 1 -> FMU 2 represents the successful case and FMU 2 -> FMU 1 represents the unsuccessful case.
In step (1), a <<TransmitOpCodeCanLowCut, Transmission operation>> will be delivered to the Bus Simulation.
Within step (2), the <<TransmitOpCodeCanLowCut, Transmission operation>> will transferred to FMU 2, so the transmission was successful.
Also in step (2), FMU 1 receives a <<ConfirmOpCodeCanLowCut, Confirm operation>>, which means the transmission was successful.
In step (3), FMU 2 wants to transmit network data to FMU 1:
A <<TransmitOpCodeCanLowCut, Transmission operation>> will be delivered from FMU 2 to the Bus Simulation.
In step (4), we see that the transmission results in an <<ErrorOpCodeCanLowCut, Error operation>>.
Because of this FMU 2 knows that the transmission was not successful.

.Successful and not successful cases of a CAN transmission.
[#figure-can-transmission-acknowledge]
image::can_transmission_acknowledge.svg[width=60%, align="center"]

Normally, transmission failure cannot occur during a simulated bus transmission.
Most common kinds of errors are used to inject transmission errors, for example using the Bus Simulation FMU, for advanced test scenarios.

====== CAN Arbitration [[example-can-arbitration]]
<<#figure-can-arbitration-overview>> shows the realization of a CAN arbitration.
At the beginning, FMU 1 and FMU 2 each send network data at the same time.
In this situation, an arbitration is necessary so that it can be decided which frame should be sent in this case.
Both frames are transferred to the Bus Simulation.
Arbitration takes place within the Bus Simulation.
In the example given, the two frames with CAN ID = 15 and CAN ID = 16 are analyzed and it is decided that CAN ID = 15 wins the arbitration.
The Bus Simulation then calculates the transmission time for the CAN frame with CAN ID = 15.
The next time the FMI `Event Mode` is called up for the Bus Simulation, the corresponding CAN frame is transmitted to FMU 2 and FMU 3.
For CAN ID 16, FMU 2 is informed via an <<ErrorOpCodeCanLowCut, Error operation>> with `Error Code = ARBITRATION_LOST` that this frame cannot be sent.
FMU 1 gets a <<ConfirmOpCodeCanLowCut, Confirm operation>>, because the specified frame with CAN ID 15 was successfully transmitted.

.Arbitration of CAN frames within Bus Simulation.
[#figure-can-arbitration-overview]
image::can_arbitration_overview.svg[width=80%, align="center"]

====== CAN Arbitration with Buffer Option [[example-can-arbitration-with-buffer-option]]
<<#figure-can-arbitration-overview-with-buffer>> shows the realization of a CAN arbitration by using the `Buffer` option within the <<ConfigurationCanOpCode, Configuration operation>>.
At the beginning, FMU 1 and FMU 2 each send network data at the same time.
In this situation, an arbitration is necessary so that it can be decided which frame should be sent in this case.
Both frames are transferred to the Bus Simulation.
Arbitration takes place within the Bus Simulation.
In the example given, the two frames with CAN ID = 15 and CAN ID = 16 are analyzed and it is decided that CAN ID = 15 wins the arbitration.
The Bus Simulation then calculates the transmission time for the CAN frame with CAN ID = 15.
The next time the FMI `Event Mode` is called up for the Bus Simulation, the corresponding CAN frame is transmitted to FMU 2 and FMU 3.
The <<TransmitOpCodeCanLowCut, Transmission operation>> of CAN ID 16 is buffered by the Bus Simulation and will be sent within the next time slot.
The Bus Simulation does not return an <<ErrorOpCodeCanLowCut, Error operation>> with an `Error Code = ARBITRATION_LOST` to FMU 2.
FMU 1 gets a <<ConfirmOpCodeCanLowCut, Confirm operation>>, because the specified frame with CAN ID 15 was successfully transmitted.

.Arbitration of CAN frames with buffering within Bus Simulation.
[#figure-can-arbitration-overview-with-buffer]
image::can_arbitration_overview_with_buffer.svg[width=80%, align="center"]
