==== LIN [[low-cut-lin]]
This chapter describes the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> for LIN.

===== Overview [[low-cut-lin-overview]]
To simulate LIN buses, LIN-specific operations are specified based on the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>>.
Overall, the following groups of operations exists:

* Transmit and Confirm: This group of operations is used to simulate a frame transmission.
There are three specific operations that represent the different communication options between a LIN Master and one or more LIN Slaves.
* Bus- and Format Error: This group of operations is used for protocol format errors and to simulate bus failures.
* Configuration: This operation enables the configuration of bus-specific parameters and options that are required to simulate the bus behavior properly.
For example, it allows the specification of the baud rate.
* Wake up: LIN supports wake up and sleep scenarios.
Normally there are two ways to wake up from sleep mode: a local wake up on a specified wake-up pin, or a wake-up on the LIN bus via a LIN specific wake-up pulse.
This operation is used to simulate triggering a wake-up from bus side.

The following table gives a detailed overview of the available operations.
It shows all operations and the arguments they contain.

.Overview of the available operations for LIN.
[#table-operation-content-lin]
[cols="9,1,6,5,5,5,5,5,5,5,5"]
|====
.2+h|Operation Name
10+h|Operation Content

h|OP Code
h|Length
8+h|Specific Content

|Format Error
|0x01
|:= 10 + n +
(4 bytes)
|DL +
(2 bytes)
7+|Data +
(n bytes)

|Header
|0x10
|:= 10 +
(4 bytes)
|PID +
(1 byte)
7+|Response Data Length +
(1 byte)

|Response
|0x11
|:= 11 + DL +
(4 bytes)
|PID +
(1 byte)
2+|Response Error +
(1 byte)
|DL +
(1 byte)
4+|Data +
(n bytes)

|Header Response
|0x12
|:= 10 + DL +
(4 bytes)
|PID +
(1 byte)
|DL +
(1 byte)
6+|Data +
(n bytes)

|Confirm
|0x20
|:= 9 +
(4 bytes)
8+|PID +
(1 byte)

|Bus Error
|0x30
|:= 10 +
(4 bytes)
|PID +
(1 byte)
7+|Error Code +
(1 byte)

|Configuration
|0x40
|<Length> +
(4 bytes)
|Kind +
(1 byte)
7+|_Dynamic Part_

|Wakeup
|0x41
|:= 8 +
(4 bytes)
8+|---

|====

===== Operations [[low-cut-lin-operations]]
This section defines the allowed operations for LIN.
The following tables provide an overview of all operations and specifies the position and length of the corresponding arguments, as well as the respective flow direction.

====== Transmit [[low-cut-lin-transmit-operation]]
There are three types of <<low-cut-lin-transmit-operation, `Transmit`>> operations, each representing the transmission of a LIN header, a response and a combination of a header and response.

.Detailed description of the LIN Header operation.
[#table-lin-header-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Header
h|Description 3+| Represents an operation for the transmission of a LIN header from a LIN Master to LIN slaves.
h|OP Code [hex] 3+| 0x10
.5+h|Content h|Argument h|Length h|Description
| OP Code | 4 bytes | Contains the OP Code of the specified operation.
For this operation the OP Code always has the value 0x10.
| Length | 4 bytes | Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Length = 10`.
| PID | 1 byte | The specified protected ID (PID) of the LIN message.
The maximum length of a PID is 8-bit.
| Response Data Length | 1 byte | The size of the response in bytes.
h|Behavior
3+|The Header operation shall be provided by Network FMUs to initiate the transmission of a LIN header.
In case of direct connected Network FMUs (see <<common-concepts-direct-communication>>), the FMU importer forwards the operation directly to the receiving Network FMUs.
If a Bus Simulation is involved (see <<common-concepts-composition-with-dedicated-bus-simulation-fmu>> and <<common-concepts-importer-with-integrated-bus-simulation>>), the FMU importer forwards the operation initially to the Bus Simulation, where the operation is distributed with respect to the simulated bus behavior.
Depending on the simulation details, the Bus Simulation might respond with a <<low-cut-lin-bus-error-operation, `Bus Error`>> or <<low-cut-lin-format-error-operation, `Format Error`>> operation.

|====

.Detailed description of the LIN Response operation.
[#table-lin-response-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Response
h|Description 3+| Represents an operation for the transmission of a LIN response from a LIN Slave to the LIN Master.
h|OP Code [hex] 3+| 0x11
.7+h|Content h|Argument h|Length h|Description
| OP Code | 4 bytes | Contains the OP Code of the specified operation.
For this operation the OP Code always has the value 0x11.
| Length | 4 bytes | Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Length = 11 + Data Length`.
| PID | 1 byte | The specified protected ID (PID) of the LIN message.
The maximum length of a PID is 8-bit.
| Response Error | 1 byte | Represents the Response Error field of a LIN frame.
For specification the boolean values `TRUE` and `FALSE` (see <<table-boolean-value-kinds>>) shall be used.
| Data Length | 1 byte | Specifies the length of the Data argument in bytes.
| Data | n bytes | Stores the given frame data to transfer, whereby the valid length of the data depends on the LIN Format.
h|Behavior
3+|The Response operation shall be provided by Network FMUs to initiate a response to a given LIN header.
In case of direct connected Network FMUs (see <<common-concepts-direct-communication>>), the FMU importer forwards the operation directly to the receiving Network FMUs.
If a Bus Simulation is involved (see <<common-concepts-composition-with-dedicated-bus-simulation-fmu>> and <<common-concepts-importer-with-integrated-bus-simulation>>), the FMU importer forwards the operation initially to the Bus Simulation, where the operation is distributed with respect to the simulated bus behavior.
Depending on the simulation details, the Bus Simulation might respond with a <<low-cut-lin-bus-error-operation, `Bus Error`>> or <<low-cut-lin-format-error-operation, `Format Error`>> operation.

|====

.Detailed description of the LIN Header Response operation.
[#table-lin-header-response-operation]
[cols="5,4,3,20"]
|====
h|Name 3+| Header Response
h|Description 3+| Represents an operation for the transmission of a LIN header and response from a LIN Master to LIN slaves.
h|OP Code [hex] 3+| 0x12
.6+h|Content h|Argument h|Length h|Description
| OP Code | 4 bytes | Contains the OP Code of the specified operation.
For this operation the OP Code always has the value 0x12.
| Length | 4 bytes | Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Length = 10 + Data Length`.
| PID | 1 byte | The specified protected ID (PID) of the LIN message.
The maximum length of a PID is 8-bit.
| Data Length | 1 byte | Specifies the length of the Data argument in bytes.
| Data | n bytes | Stores the given frame data to transfer, whereby the valid length of the data depends on the LIN Format.
h|Behavior
3+|The Header Response operation shall be provided by Network FMUs to initiate the transmission of a LIN frame that contains the specified header and response.
In case of direct connected Network FMUs (see <<common-concepts-direct-communication>>), the FMU importer forwards the operation directly to the receiving Network FMUs.
If a Bus Simulation is involved (see <<common-concepts-composition-with-dedicated-bus-simulation-fmu>> and <<common-concepts-importer-with-integrated-bus-simulation>>), the FMU importer forwards the operation initially to the Bus Simulation, where the operation is distributed with respect to the simulated bus behavior.
Depending on the simulation details, the Bus Simulation might respond with a <<low-cut-lin-bus-error-operation, `Bus Error`>> or <<low-cut-lin-format-error-operation, `Format Error`>> operation.

|====

====== Confirm [[low-cut-lin-confirm-operation]]
The <<low-cut-lin-confirm-operation, `Confirm`>> operation is used to signal the successful transmission of a <<low-cut-lin-transmit-operation, `Transmit`>> operation.

.Detailed description of the Confirm operation.
[#table-lin-confirm-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Confirm
h|Description
3+|Signals a successful transmitted LIN Header or/and Response.
h|OP Code [hex]
3+|0x20
.4+h|Content h|Argument h|Length h|Description
|OP Code
|4 bytes
|Contains the OP Code (0x20) of the operation.

|Length
|4 bytes
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 9`.

|PID
|1 bytes
|The protected ID of the confirmed <<low-cut-lin-transmit-operation, `Transmit`>> operation.

h|Behavior
3+|The specified operation shall be produced by the Bus Simulation and consumed by Network FMUs.
The Bus Simulation provides the <<low-cut-lin-confirm-operation, `Confirm`>> operation for the Network FMU, which has previously provided the <<low-cut-lin-transmit-operation, `Transmit`>> operation to be confirmed.
Only Network FMUs with the corresponding optionally exposed <<low-cut-lin-bus-notification-parameter, `BusNotifications`>> parameter set to `fmi3True` might wait for this operation.

|====

====== Format Error [[low-cut-lin-format-error-operation]]
See <<low-cut-format-error-operation, `Format Error`>> for definition.

====== Bus Error [[low-cut-lin-bus-error-operation]]
The <<low-cut-lin-bus-error-operation, `Bus Error`>> represents special bus communication errors, which are delivered to the LIN Master node in the network.

.Detailed description of the Bus Error operation.
[#table-lin-bus-error-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Bus Error
h|Description
3+|Represents an operation for bus communication error handling.
h|OP Code [hex]
3+|0x30
.5+h|Content h|Argument h|Length h|Description
|OP Code
|4 bytes
|Contains the OP Code of the specified operation.
For this operation the OP Code always has the value 0x30.

|Length
|4 bytes
|Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Length = 10`.

|PID
|1 byte
|The specified protected ID of the LIN message which triggers the error.

|Error Code
|1 byte
|The specified error code, basing on the table below.

h|Behavior
3+|The specified operation shall be produced by the Bus Simulation and consumed by Network FMUs.
An Error operation is always a reaction from the Bus Simulation to a <<low-cut-lin-transmit-operation, `Transmit`>> operation that was produced by a Network FMU.
Out of this Error operations are available in the <<common-concepts-composition-with-dedicated-bus-simulation-fmu, Composition with dedicated Bus Simulation FMU>> and <<common-concepts-importer-with-integrated-bus-simulation, Importer with Integrated Bus Simulation>> communication use case only.
Only Network FMUs with the corresponding optionally exposed <<low-cut-lin-bus-notification-parameter, `BusNotifications`>> parameter set to `fmi3True` might wait for this operation.

|====

The following codes are allowed to use as Error Code:

.Overview of the available error states and codes.
[#table-lin-bus-error-codes]
[cols="1,3,20"]
|====

h|State h|Error Code h|Description

|BIT_ERROR
|0x01
|A BIT_ERROR means that a received bit does not match the expected value.
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to a <<#table-lin-header-operation, `Header`>> operation and shall be delivered to the Network FMU that is configured as <<table-lin-configuration-node-definition-kinds, `LIN_MASTER`>> within the specified LIN network.

|CHECKSUM_ERROR
|0x02
|Represents a CRC error.
The error can occur during a collision of multiple response frames when Event-Triggered-Frames are used.
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to a <<#table-lin-response-operation, `Response`>> operation and shall be delivered to the Network FMU that is configured as <<table-lin-configuration-node-definition-kinds, `LIN_MASTER`>> of the specified LIN network.

|IDENTIFIER_PARITY_ERROR
|0x03
|Represents an Identifier Parity Error.
The error can occur during a collision of multiple LIN headers.
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to a <<#table-lin-header-operation, `Header`>> operation and shall be delivered to all Network FMUs of the specified LIN network.

|SLAVE_NOT_RESPONDING_ERROR
|0x04
|Represents a Slave Not Responding Error.
The error can occur if LIN Slaves does not respond to a specified LIN header.
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to a <<#table-lin-header-operation, `Header`>> operation and shall be delivered to the Network FMU that is configured as <<table-lin-configuration-node-definition-kinds, `LIN_MASTER`>> within the specified LIN network.

|SYNCH_FIELD_ERROR
|0x05
|Represents an Inconsistent-Synch Field Error.
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to a <<#table-lin-header-operation, `Header`>> operation and shall be delivered to the Network FMUs that are configured as <<table-lin-configuration-node-definition-kinds, `LIN_SLAVE`>> within the specified LIN network.

|SYNCH_TOLERANCE_ERROR
|0x06
|The calculated baud rate deviates too much from the original baud rate after clock synchronization (tolerance exceeded).
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to a <<#table-lin-header-operation, `Header`>> operation and shall be delivered to the Network FMUs that are configured as <<table-lin-configuration-node-definition-kinds, `LIN_SLAVE`>> within the specified LIN network.

|HEADER_TIMEOUT_ERROR
|0x07
|A header timeout error means that a slave node did not receive a complete header from the master within the specified time frame.
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to a <<#table-lin-header-operation, `Header`>> operation and shall be delivered to the Network FMUs that are configured as <<table-lin-configuration-node-definition-kinds, `LIN_SLAVE`>> within the specified LIN network.

|FRAME_ERROR
|0x08
|This represents an error in the stop bit or in the frame format.
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to any <<low-cut-lin-transmit-operation, `Transmit`>> operation and shall be delivered to all Network FMUs of the specified LIN network.

|PHYSICAL_BUS_ERROR
|0x09
|Represents a Physical Bus Error.
This <<low-cut-lin-bus-error-operation, `Bus Error`>> operation is a direct reaction to any <<low-cut-lin-transmit-operation, `Transmit`>> operation and shall be delivered to all Network FMUs of the specified LIN network.

|====

====== Configuration [[low-cut-lin-configuration-operation]]
The <<low-cut-lin-configuration-operation, `Configuration`>> operation allows Network FMUs the configuration of the Bus Simulation with parameters like baud rate information and further options.
The following information are included within this operation:


.Detailed description of the Configuration operation.
[#table-lin-configuration-operation]
[cols="5,1,10,4,3,20"]
|====
h|Name
5+|Configuration
h|Description
5+|Represents an operation for the configuration of a Bus Simulation.
In detail the configuration of a LIN baud rate is possible.
Also the configuration of further options, like LIN Master or LIN Slave representation, is supported by this operation.
h|OP Code [hex]
5+|0x40
.7+h|Content 3+h|Argument h|Length h|Description
3+|OP Code
|4 bytes
|Contains the OP Code (0x40) of the operation.

3+|Length
|4 bytes
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 9 + Length of parameter arguments in bytes`.

3+|Parameter Type
|1 byte
|Defines the current configuration parameter.
Note that only one parameter can be set per <<low-cut-lin-configuration-operation, `Configuration`>> operation.

.3+h|
4+h|Parameters

|LIN_BAUDRATE
|Baud Rate
|4 bytes
|The specified baud rate value to configure, whereby the specified ranges are defined by the LIN standard.
The required unit for the baud rate value is bit/s.

|LIN_NODE_DEFINITION
|Node Definition
|1 byte
|Configures the required node type (Master or Slave) within a Bus Simulation.
Possible values are: `LIN_MASTER` and `LIN_SLAVE` (see <<table-lin-configuration-node-definition-kinds>>).

h|Behavior
5+|The specified operation shall be produced by a Network FMU and consumed by the Bus Simulation.
The operation shall not be routed to other Network FMUs by the Bus Simulation.
A Network FMU shall ignore this operation on consumer side.
The configuration shall be completed by a specified Network FMU before it produces any <<low-cut-lin-transmit-operation, `Transmit`>> operations.
The configuration must not be repeated multiple times during the runtime of a Network FMU.
A Bus Simulation should stop as soon as more than one `LIN_MASTER` is configured in a network.
If required configuration parameters are not adjusted by a Network FMU the Bus Simulation shall choose a default behavior by itself.
|====

The following Kind values are allowed to be used:

.Overview of the available configuration kinds and values.
[#table-lin-configuration-kinds]
[cols="1,1,5"]
|====

h|Kind h|Value h|Description
|LIN_BAUDRATE|0x01|This code indicates that a LIN baud rate should be configured for the Bus Simulation.
|LIN_NODE_DEFINITION|0x02|This code configures the specified node type (Master or Slave) within a Bus Simulation.

|====

The following values for `LIN_NODE_DEFINITION` are defined:

.Overview of the available node definition values for LIN.
[#table-lin-configuration-node-definition-kinds]
[cols="2,1,5"]
|====

h|Node Definition h|Value h|Description
|LIN_MASTER|0x01|Configuration of a LIN Master node within a specified Bus Simulation.
|LIN_SLAVE|0x02|Configuration of a LIN Slave node within a specified Bus Simulation.

|====

====== Wake Up [[low-cut-lin-wake-up-operation]]
By using the <<low-cut-lin-wake-up-operation, `Wakeup`>> operation the underlying Bus Simulation can trigger a bus-specific wake-up.

.Detailed description of the Wakeup operation.
[#table-lin-wakeup-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Wakeup
h|Description
3+|Represents an operation for triggering a bus-specific wake-up.
h|OP Code [hex]
3+|0x41
.3+h|Content h|Argument h|Length h|Description
|OP Code
|4 bytes
|Contains the OP Code of the specified operation.
For this operation the OP Code always has the value 0x41.

|Length
|4 bytes
|Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Length = 8`.

h|Behavior
3+|The specified operation shall be produced by a Network FMU and distributed to all participants, except the wake-up initiator, of the bus by using the Bus Simulation.
If a Network FMU does not support wake-up this operation can be ignored on consumer side.

|====

===== Network Parameters [[low-cut-lin-network-parameters]]
This chapter defines parameters that Network FMU might provide to configure LIN-specific behavior.

====== Bus Notification Parameter [[low-cut-lin-bus-notification-parameter]]
For a detailed simulation, a Network FMU needs information about whether the message sent has arrived or whether a bus error has occurred.
A Bus Simulation can simulate these effects by sending bus notifications in terms of <<low-cut-lin-confirm-operation, `Confirm-`>> and <<low-cut-lin-bus-error-operation, `Bus Error`>> operations to the Network FMUs.

However, in scenarios where Network FMUs are connected directly to each other, or where the Bus Simulation does not simulate such effects, it must be possible to configure the Network FMU such that it does not wait for any response after a <<low-cut-lin-transmit-operation, `Transmit`>> operation.
Therefore, a parameter with `memberName = "BusNotifications"` can be added within the LIN-specific  <<low-cut-configuration-terminal,Configuration Terminal>>. +
If a Network FMU supports bus notifications, the <<low-cut-lin-bus-notification-parameter, `BusNotifications`>> parameter shall be exposed.
The default value of this parameter shall be `false`. +
_[The default value `false` allows a simple integration of Network FMUs to simulation scenarios where <<low-cut-lin-confirm-operation, `Confirm-`>> or <<low-cut-lin-bus-error-operation, `Bus Error`>> operations are not used.]_

Only Network FMUs with the corresponding optionally exposed <<low-cut-lin-bus-notification-parameter, `BusNotifications`>> parameter set to `fmi3True` might wait for <<low-cut-lin-confirm-operation, `Confirm-`>> and <<low-cut-lin-bus-error-operation, `Bus Error`>> operations and respond accordingly; otherwise Network FMUs must not wait ("fire-and-forget").
Even if the Network FMU does not expect bus notifications, i.e. <<low-cut-lin-bus-notification-parameter, `BusNotifications`>> variable was not set to `fmi3True`, but receives them, it shall ignore them, i.e. it shall not report warnings or errors.

_[Note that the bus notification parameter just informs the Network FMU if it can expect to receive notification operations or not.
The parameter doesn't define in any way on how to react upon receiving notification operations.]_

.Parameter to configure bus notifications within a LIN Bus Terminal of Network FMUs.
[[figure-fmu-lin-bus-notifications-parameter]]
----
 memberName:    BusNotifications
 type:          Boolean
 causality:     parameter
 variability:   fixed
 start:         false
----

A Bus Simulation FMU shall indicate via a variable with `memberName = "BusNotifications"` within the LIN-specific  <<low-cut-configuration-terminal,Configuration Terminal>> whether it provides bus notifications or not.
If the provision of bus notifications can be configured (e.g., via a structural parameter), the attributes of the <<low-cut-lin-bus-notification-parameter, `BusNotifications`>> variable shall contain `causality = "calculatedParameter"` and `variability = "fixed"`; or `causality = "output"` and `variability = "constant"` otherwise.

.Parameter to configure bus notifications within a LIN Bus Terminal of the Bus Simulation.
[[figure-fmu-lin-bus-notifications-parameter-in-bus-simulation]]
----
 memberName:    BusNotifications
 type:          Boolean
 causality:     calculatedParameter/output
 variability:   fixed/constant
----

===== Transmission and Reception [[low-cut-lin-transmission-and-reception]]
#To be defined.#

===== Detection of Collisions [[low-cut-lin-detection-of-collisions]]
#To be defined.#

===== Configuration of Bus Simulation [[low-cut-lin-configuration-of-bus-simulation]]
The configuration of the Bus Simulation is done by the Network FMUs itself.
For this purpose, the <<low-cut-lin-configuration-operation, `Configuration`>> operation provides several configuration parameters.
<<low-cut-lin-configuration-operation, `Configuration`>> operations can be produced multiple times during the runtime of a Network FMU.
Because the Bus Simulation shall choose a default behavior, it might be useful in several scenarios that Network FMUs finish configuration before the production of <<low-cut-lin-transmit-operation, `Transmit`>> operations.

====== Baud Rate Handling [[low-cut-lin-baud-rate-handling]]
In order to calculate the time required for the transmission of a bus message, it is necessary to inform the Bus Simulation about the specified baud rate from a Network FMU.
This baud rate information can be configured by using `LIN_BAUDRATE` configuration kind of the <<low-cut-lin-configuration-operation, `Configuration`>> operation.
If the baud rate information is not adjusted by a specified Network FMU, the Bus Simulation shall choose a default behavior by itself.

====== Node Definition [[low-cut-lin-node-definition]]
By using the `LIN_NODE_DEFINITION` kind of <<low-cut-lin-configuration-operation, `Configuration`>> operation, the specified node type `LIN_MASTER` or `LIN_SLAVE` needs to be adjusted.
This configuration must be done before the first exchange of <<low-cut-lin-transmit-operation, `Transmit`>> operations.
A Bus Simulation should stop as soon as more than one LIN Master is configured in a network.

===== Error Handling [[low-cut-lin-error-handling]]
LIN provides extensive options for detecting bus errors.
Overall, the respective bus errors affect the internal controller status within the Network FMUs.
To maintain the internal controller status, <<low-cut-lin-bus-error-operation, `Bus Error`>> operations shall be provided to all relevant Network FMUs by the Bus Simulation.
Depending on the type of <<low-cut-lin-bus-error-operation, `Bus Error`>> operation and specific kind of <<low-cut-lin-transmit-operation, `Transmit`>> operation a different subset of Network FMUs must be notified via <<low-cut-lin-bus-error-operation, `Bus Error`>> operation (see <<table-lin-bus-error-codes>> for details).

.Architectural error handling overview.
[#figure-lin-architectural-error-handling-overview]
image::lin_error_handling_overview.svg[width=80%, align="center"]

===== Wake Up/Sleep [[low-cut-lin-wakeup-sleep]]
This standard supports wake up and sleep for the LIN bus, whereby only the bus-specific parts are taken into account.
This means that the realization of local virtual ECU wake-up and sleeping processes are internal parts of the respective FMU, which is not covered by this document.
Because entering sleep state is a virtual ECU internal process always within LIN bus, this can be ignored.
Also, the virtual ECU local wake-up process is ignored as well.
The LIN-specific wake-up pulse can be simulated by using the <<low-cut-lin-wake-up-operation, `Wakeup`>> operation.
A <<low-cut-lin-wake-up-operation, `Wakeup`>> operation is initiated by one Network FMU and shall be distributed to all participants of the bus,except the wake-up initiator, by the Bus Simulation.

.Wake up initiated by FMU 1 wakes up FMU 2 and FMU 3 via bus.
[#figure-lin-wake-up]
image::lin_wake_up.svg[width=70%, align="center"]
