==== Ethernet [[low-cut-ethernet]]
This chapter describes the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> for Ethernet.

===== Overview [[low-cut-ethernet-overview]]

====== Scope of this standard

This standard should allows simulation of Ethernet bus systems and shall cover commercial, industrial and automotive use cases.

This standard should cover all variants of Ethernet described in <<IEEE-802.3-2022>> while being flexible enough to support future versions without adaption due to the high cadence of the Ethernet standarization process.
In addition, common supplementary standards are considered, including the following:

* <<OpenAlliance-TC10-100BASE-T1, Open Alliance TC10 sleep/wake-up>> (including <<OpenAlliance-TC10-100BASE-T1, 100BASE-T>>, <<OpenAlliance-TC10-1000BASE-T1, 1000BASE-T1>> and <<OpenAlliance-TC10-10BASE-T1S, 10BASE-T1S>>)

Especially the physical layers 100BASE-TX, 1000BASE-T, 10GBASE-T, 100BASE-T1, 1000BASE-T1 and 10BASE-T1S have been evaluated in detail for this standard.
In addition, it should consider requirements for time-sensitive networking (TSN), specifically the use of the MAC Merge sublayer (also known as Ethernet Frame Preemption).

In the 802.3 architecture, the layered standard aims to provide an abstraction of the Ethernet controller on the Media Access Control (MAC) sublayer.
Effects on lower layers are modeled on a simplified level.


====== Ethernet topologies

Ethernet support both point-to-point and multidrop topologies.
In a point-to-point topology, Ethernet devices are either connected directly and more than two devices are connected using and Ethernet switch.
This topology is used for all modern Ethernet variants except 10BASE-T1S.
In a multidrop topology, multiple devices are connected to the same segment either directly, daisy-chained or interconnected via hubs.
This topology is used for legacy Ethernet standards as well as 10BASE-T1S.

In terms of the LS-BUS, each point-to-point connection or multidrop segment represents a dedicated virtual bus, which may be simulated by an independent bus simulation or combined into an consolidated simuation.
Ethernet switches can be modeled as normal FMUs, where switch ports correspond to LS-BUS terminals, to allow simulating any kind of Ethernet switch.
To simplify interconnecting Ethernet FMUs, a bus simulation may decide to incorporate the Ethernet switching instead of delegating it to a dedicated FMU.


===== Transmission [[low-cut-ethernet-transmission]]

A transmission of an Ethernet frame is modeled by a transmit operation.
The transmit operation is received by the bus simulation and forwarded to the communication partner after the transmission delay which should be calculated by the bus simulation.

The bus simulation then sends a confirm operation to the sender, if the <<low-cut-ethernet-bus-notification-parameter, Bus Notification parameter>> is configured.
In the case of an error or collision, a bus error operation may be returned instead.

The following sections will describe special transmission scenarios.

====== Normal transmission

TODO

====== Transmission with avoided collision

TODO

====== Transmission with collision

TODO

====== Fragmented transmission using the MAC Merge sublayer

When using the MAC Merge sublayer (See chapter 99 of 802.3-2022),
the transmit operation can also indicate the transmission of Express frames and the initial fragment of preempted frames.
Continuation packets of a preempted frame are transmitted using the transmit continuation operation.

TODO: Examples


===== Configuration of bus simulation [[low-cut-ethernet-configuration-of-bus-simulation]]

To initialize the Ethernet communication, the network FMUs need to exchange
their capabilities and link state.
This serves to properly simulate compatibility of the used PHY and to determine the correct link speed and behavior.
In addition, simulation of auto-negotiation, auto MDI-X, and configuration of other lower layer mechanisms like PLCA is facilitated using this mechanism.

Before an Ethernet network FMU may communicate, it must send a configuration operation (TODO: reference).
Only after also receiving a bus configuration operation and evaluating it against its own configuration for compatibility, it may start transmitting frames.

In a direct connection scenario, configuration operations are exchanged as-is.
With a bus simulation, configuration operations may either be forwarded by a bus simulation or the bus simulation may supply its own configuration operation to each node.
In a multidrop configuration, the bus simulation shall not forward configuration operations but should supply a single configuration operation to each network FMU.


===== Error Handling [[low-cut-ethernet-error-handling]]
===== Wake Up/Sleep [[low-cut-ethernet-wakeup-sleep]]
This standard supports wake up and sleep functionality for the Ethernet bus, based on the TC10 Sleep/Wake-up
Specification.
Note that Wake Up/Sleep is not available for all Ethernet variants, but only for 10BASE-T1S, 100BASE-T1, 1000BASE-T1 and Multi-G BASE-T1.
However, the realization of local virtual ECU wake-up and sleeping processes, i.e., the transition to the sleep state as well as the virtual ECU local wake-up process, is considered internal to the FMU implementation.
Therefore, only the bus-related aspects are defined in this document.

The Ethernet-specific wake-up pulse can be simulated by using the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation, initiated by one Network FMU.
The Bus Simulation shall distribute this operation to all participants on the bus, excluding the wake-up initiator.

.Wake up initiated by FMU 1 wakes up FMU 2 and FMU 3 via bus.
[#figure-ethernet-wake-up]
image::ethernet_wake_up.svg[width=70%, align="center"]

Analogously, the <<low-cut-ethernet-sleep-operation, `Sleep`>> operation is used to prompt corresponding receivers to go to sleep.
The flow direction is analogous to the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation.


===== Network parameters [[low-cut-ethernet-network-parameters]]
By using configuration parameters on bus terminal-level, network FMUs can be parameterized by the user or bus simulation (e.g., by using the parameter propagation mechanism).
This chapter specifies the configuration parameters that should exist on an Ethernet bus terminal.

====== Bus notification parameter [[low-cut-ethernet-bus-notification-parameter]]
For a detailed simulation, a network FMU needs information about whether a frame has been sent or whether a bus error has occurred.
A bus simulation can simulate these effects by sending bus notifications in terms of <<low-cut-ethernet-confirm-operation, `Confirm-`>> and <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operations to the network FMUs.


include::4_4_4_ethernet_operations.adoc[]
