:imagesdir: images

==== Ethernet [[low-cut-ethernet]]
This chapter describes the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> for Ethernet.

===== Overview [[low-cut-ethernet-overview]]

====== Scope of this standard

This standard should allow simulation of Ethernet bus systems and shall cover commercial, industrial and automotive use cases.

This standard should cover all variants of Ethernet described in <<IEEE-802.3-2022>> while being flexible enough to support future versions without adaption due to the high cadence of the Ethernet standardization process.
In addition, common supplementary standards are considered, including the following:

* <<OpenAlliance-TC10-100BASE-T1, Open Alliance TC10 sleep/wake-up>> (including <<OpenAlliance-TC10-100BASE-T1, 100BASE-T>>, <<OpenAlliance-TC10-1000BASE-T1, 1000BASE-T1>> and <<OpenAlliance-TC10-10BASE-T1S, 10BASE-T1S>>)

Especially the physical layers 100BASE-TX, 1000BASE-T, 10GBASE-T, 100BASE-T1, 1000BASE-T1 and 10BASE-T1S have been evaluated in detail for this standard.
In addition, it should consider requirements for time-sensitive networking (TSN), specifically the use of the MAC Merge sublayer (also known as Ethernet Frame Preemption).

In the 802.3 architecture, the layered standard aims to provide an abstraction of the Ethernet controller on the Media Access Control (MAC) sublayer.
Effects on lower layers are modeled on a simplified level.


====== Ethernet topologies

Ethernet support both point-to-point and multidrop topologies.
In a point-to-point topology, Ethernet devices are either connected directly or more than two devices are connected using an Ethernet switch.
This topology is used for all modern Ethernet variants except 10BASE-T1S.
In a multidrop topology, multiple devices are connected to the same segment either directly, daisy-chained or interconnected via hubs.
This topology is used in legacy Ethernet systems as well as 10BASE-T1S networks.

In terms of the LS-BUS, each point-to-point connection or multidrop segment represents a dedicated virtual bus, which may be simulated by an independent bus simulation or combined into a consolidated simulation.
Ethernet switches can be modeled as normal FMUs, where switch ports correspond to LS-BUS terminals, to allow simulating any kind of Ethernet switch.
To simplify interconnecting Ethernet FMUs, a bus simulation may decide to incorporate the Ethernet switching instead of delegating it to a dedicated FMU.


===== Transmission and reception [[low-cut-ethernet-transmission]]

A transmission of an Ethernet frame is modeled by a transmit operation.
The transmit operation is received by the bus simulation and forwarded to the communication partner after the transmission delay which should be calculated by the bus simulation.

The bus simulation then sends a <<low-cut-ethernet-confirm-operation, `Confirm`>> operation to the sender, if the <<low-cut-ethernet-bus-notification-parameter, Bus Notification parameter>> is configured.
In the case of an error or collision, a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation may be returned instead.

The following sections will describe different transmission scenarios in detail.

====== Normal transmission

In a normal transmission, the Network FMU sends a transmit operation which is
forwarded to the communication partner after the calculated transmit time.
The bus operation confirm the transmission with a <<low-cut-ethernet-confirm-operation, `Confirm`>> operation.

.Normal transmission.
[#figure-ethernet-transmit]
image::ethernet_transmit.svg[width=80%, align="center"]


====== Transmission with avoided collision

On a real Ethernet bus, an Ethernet node can use carrier sensing to detect ongoing transmissions to defer its own transmission until the medium is free.
In the LS-BUS, this is not possible, thus a special bus error is introduced to indicate when the medium is busy.

When a Network FMU starts a transmission in this case, the bus simulation returns a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation with error code <<table-fmi3-ls-bus-ethernet-bus-error-code-values-medium-busy, _MediumBusy_>>.
The Network FMU should the re-attempt the transmission at a later point in time.

Note: In this scenario the ongoing transmission continues.

.Transmission with avoided collision.
[#figure-ethernet-transmit-collision-avoided]
image::ethernet_transmit_collision_avoided.svg[width=80%, align="center"]


====== Transmission with collision

If the Ethernet node does not detect an ongoing transmission in time, the Ethernet frames collide causing both transmissions to be destroyed.

When a Network FMU starts a transmission in this case, the bus simulation returns a <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operation with error code <<table-fmi3-ls-bus-ethernet-bus-error-code-values-collision, _Collision_>>.
This is also sent to other nodes on the bus including the sender of the other transmission.

Note: In this scenario the ongoing transmission is destroyed as well.

.Transmission with collision.
[#figure-ethernet-transmit-collision]
image::ethernet_transmit_collision.svg[width=80%, align="center"]


====== Fragmented transmission using the MAC Merge sublayer

When using the MAC Merge sublayer (See chapter 99 of <<IEEE-802.3-2022>>),
the transmit operation can also indicate the transmission of Express frames and the initial fragment of preempted frames.
Continuation packets of a preempted frame are transmitted using the <<low-cut-ethernet-transmit-continuation-operation, Transmit Continuation Operation>>.

Before the MAC Merge sublayer is used, _Verify_ and _Respond_ frames are used to verify that the link partner supports this functionality, these are indicated by an <<low-cut-ethernet-transmit-verify-respond-operation, Transmit Verify/Respond Operation>>.

.Fragmented transmission. The frame 1 is fragmented into two fragments 1.1 and 1.2 due to a transmission of an Express frame 2.
[#figure-ethernet-transmit-fragmented]
image::ethernet_transmit_fragmented.svg[width=80%, align="center"]


===== Configuration and startup [[low-cut-ethernet-configuration-and-startup]]

To initialize the Ethernet communication, the network FMUs need to exchange
their capabilities and the current parameters of the Ethernet link.
This serves to properly simulate compatibility of the used PHY and to determine the correct link speed and behavior.

In addition, configuration and simulation of auto-negotiation, auto MDI-X and lower layer mechanisms like PLCA is supported using this mechanism.

The configuration and startup phase consists of the following steps:

. Exchange of configuration operations (see <<low-cut-ethernet-configuration-phase>>)
. Sending of an initial <<low-cut-ethernet-link-state-indication-operation, Link State Indication Operation>>
. <<low-cut-ethernet-configuration-phase, Auto-Negotiation>> (optional)
. Sending of an updated <<low-cut-ethernet-link-state-indication-operation, Link State Indication Operation>> (optional)

These phases are described in further detail in the following sections.

TODO: PLCA

====== Configuration Phase [[low-cut-ethernet-configuration-phase]]

Before an Ethernet network FMU may communicate, it must send a <<table-fmi3-ls-bus-ethernet-configuration-operation, Configuration Operation>>.
Only after also receiving a bus configuration operation and evaluating it against its own configuration for compatibility, it may start transmitting frames.

In a direct connection scenario, configuration operations are exchanged as-is.
With a bus simulation, configuration operations may either be forwarded by a bus simulation or the bus simulation may supply its own configuration operation to each node.
In a multidrop configuration, the bus simulation shall not forward configuration operations but should supply a single configuration operation to each network FMU.

In addition to the configuration operation, the link state should be indicated with a <<low-cut-ethernet-link-state-indication-operation, Link State Indication Operation>>.
This may be done right after the configuration operation or at the latest after receiving the communication operation of the connected FMU.


====== Auto-Negotiation [[low-cut-ethernet-auto-negotiation]]

If auto-negotiation is enabled for the Network FMU, it should perform it after the configuration phase.
The initial link indication should set a physical medium attachment of "unknown".

Both auto-negotiation according to <<IEEE-802.3-2022, IEEE 802.3>> section 28 (e.g., for 10BASE-T, 100BASE-TX, 1000BASE-T, 10GBASE-T) and <<IEEE-802.3-2022, IEEE 802.3>> section 98 (e.g., for 100BASE-T1, 1000BASE-T1, 10BASE-T1S) are supported.
Auto-negotiation according to <<IEEE-802.3-2022, IEEE 802.3>> section 37 (e.g., for 1000BASE-LX, 1000BASE-CX) is currently not explicitly supported.

This standard defines a simplified auto-negotiation procedure in which all pages are exchanged at the same time.

To perform auto-negotiation, the Network FMU should send a <<low-cut-ethernet-auto-negotatiation-base-page-operation, Section 28 Base Page Operation>> or <<low-cut-ethernet-single-differential-pair-auto-negotatiation-base-page-operation, Section 98 Base Page Operation>> optionally followed by one more <<low-cut-ethernet-auto-negotatiation-message-page-operation, Message Page Operations>> (for section 28), <<low-cut-ethernet-auto-negotatiation-unformatted-page-operation, Unformatted Page Operations>> (for section 28), <<low-cut-ethernet-auto-negotatiation-extended-unformatted-page-operation, Extended Message Page Operations>> (for section 28 and section 98), or <<low-cut-ethernet-auto-negotatiation-extended-message-page-operation, Extended Unformatted Page Operations>> (for section 28 and section 98).
Note that the section 28 extended next pages and section 98 next pages have the same structure and are thus represented by the same bus operations.

After both sending and receiving the auto-negotiation pages, the Network FMU should determine the highest-common-denominator physical medium attachment and enable communication if compatible with the connected node.
This should be indicated with a <<low-cut-ethernet-link-state-indication-operation, Link State Indication Operation>>.

===== Error Handling [[low-cut-ethernet-error-handling]]

To model errors on the Ethernet bus, <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operations are used.
These operations may be sent by a bus simulation to all FMUs which may detect that errors.

A bus simulation may also inject errors into the simulation, by sending a bus error operation.

.Architectural error handling overview.
[#figure-ethernet-architectural-error-handling-overview]
image::ethernet_error_handling_overview.svg[width=100%, align="center"]

TODO: Extend and specify error scenarios


===== Wake Up/Sleep [[low-cut-ethernet-wakeup-sleep]]
This standard supports wake up and sleep functionality for the Ethernet bus, based on the TC10 Sleep/Wake-up
Specification.
Note that Wake Up/Sleep is not available for all Ethernet variants, but only for 10BASE-T1S, 100BASE-T1, 1000BASE-T1 and Multi-G BASE-T1.
However, the realization of local virtual ECU wake-up and sleeping processes, i.e., the transition to the sleep state as well as the virtual ECU local wake-up process, is considered internal to the FMU implementation.
Therefore, only the bus-related aspects are defined in this document.

The Ethernet-specific wake-up pulse can be simulated by using the <<low-cut-ethernet-wake-up-operation, `Wakeup`>> operation, initiated by one Network FMU.
The Bus Simulation shall distribute this operation to all participants on the bus, excluding the wake-up initiator.

.Wake up initiated by FMU 1 wakes up FMU 2 and FMU 3 via bus.
[#figure-ethernet-wake-up]
image::ethernet_wake_up.svg[width=70%, align="center"]

===== Network parameters [[low-cut-ethernet-network-parameters]]
By using configuration parameters on bus terminal-level, network FMUs can be parameterized by the user or bus simulation (e.g., by using the parameter propagation mechanism).
This chapter specifies the configuration parameters that should exist on an Ethernet bus terminal.

====== Bus notification parameter [[low-cut-ethernet-bus-notification-parameter]]
For a detailed simulation, a network FMU needs information about whether a frame has been sent or whether a bus error has occurred.
A bus simulation can simulate these effects by sending bus notifications in terms of <<low-cut-ethernet-confirm-operation, `Confirm-`>> and <<low-cut-ethernet-bus-error-operation, `Bus Error`>> operations to the network FMUs.


include::4_4_4_ethernet_operations.adoc[]
