== Network Abstraction ("low cut") [[network-abstraction]]
This chapter describes the Network Abstraction or "low cut" in detail.

=== Overview
The network abstraction allows the implementation of virtual bus drivers within FMUs on the level of the hardware abstraction layer.
Exchanging data in terms of <<Overview-Layered-Standard-Bus-Protocol, Layered Standard Bus Protocol>> via variables grouped by a dedicated bus terminal (see <<ClockVariableLowCut>>), allows the implementation of bus simulations in a wide range from idealized up to a detailed behavior including e.g. timing, arbitration, error, status and other effects.
During simulation, the network communication is controlled by send and receive bus operations.
Based on these operations, networked FMUs have to react as specified by this layered standard in dependency of their role.
This role can be a Bus Simulation FMU or an importer with bus simulation support on one side, and networked FMUs (e.g. virtual ECUs) on the other side (see <<SystemCompositions, System Compositions>>).
The Layered Standard Bus Protocol in general is bus type specific, but has some similarities.
Bus communication often follows a Transmit/Confirm pattern where a networked FMU sends a Transmit operation containing the network message as payload.
Depending on the <<SystemCompositions, System Composition>>, the importer forwards the Transmit operation directly to receiving FMUs or to a dedicated bus simulation.
The Bus Simulation then might delay the transfer of the Transmit operation to the receiving FMUs to simulate timing behavior, before sending a bus specific Confirm operation back to the sending FMU.

.Transmission overview.
[#figure-transmission-overview]
image::transmit_messages.svg[width=50%, align="center"]

The point in time in which FMUs will (potentially) send new network messages must be given to the importer in advance.
Based on these times, the importer has to calculate the next `communicationStepSize` for all networked FMUs.
For simulating bus communication with timing effects, the FMUs should set the Co-Simulation attribute `canHandleVariableCommunicationStepSize = true`.

.Example for network simulation with timing behavior.
[#figure-transmission-example-with-timing-behavior]
image::bus_simulation_example.svg[width=80%, align="center"]

For simplification reasons or if a detail bus simulation is not desired, fixed-step size FMUs can also be used with the Network Abstraction.
However, depending on the chosen simulation step-size, delay effects of the bus simulation have to be taken into account.
The combination of fixed-step size and variable-step size FMUs requires the decoupling of the Bus Simulation logic and the Bus Simulation timing.
This decoupling is realized by queuing Tx\Rx bus operations inside the Bus Simulation as well as queuing Tx bus operations inside Network FMUs and will be addressed by this standard.
By queuing bus operations, System Composition with variable-step size FMUs as well as fixed-step size FMUs can be simulated together without affecting each other.

=== Layered Standard Bus Protocol [[Overview-Layered-Standard-Bus-Protocol]]
The Layered Standard Bus Protocol allows the transmission of bus operations between FMUs in binary form via clocks and clocked variables (see <<NetworkAbstractionVariables>>).
Depending on the role (Network or Bus Simulation), FMUs have to react on received operations as specified by this layered standard.
Operations and the reaction on reception are bus type specific and therefore described in the bus specific chapters.
However, the description follows a uniform structure and consists of two parts, an overview table and a detail description of all operations.

The overview table represents the binary format of operations and is structured as follows:

* OP Code: The operation code defines the unique value of the operation.
It consists of one byte in length.
* Total Length: A four byte total data length (OP Code + Total Length + Arguments) field following the OP Code.[[TotalLengthField]]   
For operation with variable size arguments, the total length can vary in value at runtime.
* Arguments: The arguments of the respective operation.
The number of arguments is defined for each operation within this standard.
For arguments with a variable length an argument pair composed of length and data is used.

The following table shows an example for an operation definition.
The name is _OperationName_ and has the OP Code 0x01.
The operation has three arguments _Arg1_ (2 bytes long), _Arg2_Length_ (1 byte long), _Arg2_Data_ (_<Arg2Length>_ bytes long), whereby argument 2 and argument 3 form a coherent variable length argument.

.Definition of an operation within the Layered Standard Bus Protocol.
[#table-operation-definition]
[cols="1,1,1,1,1,1"]
|====
.2+h|Operation type
5+h|Operation content

h|OP Code
h|Total Length
3+h|Specific content

|OperationName
|0x01
|7 + <Arg2_Length>
|1 byte Arg1
|1 byte Arg2_Length
|<Arg2_Length> byte Arg2_Data
|Yes

|====

Additionally, all operations are described separately in detail in the following structure:

.Operation example within the Layered Standard Bus Protocol.
[#table-operation-definition-example]
[cols="5,4,3,20"]
|====
h|Name
3+|Name of the operation _(e.g. OperationName)_
h|Description
3+|Contains a description of the specified operation.
h|OP Code [hex]
3+|OP Code of the operation _(e.g. 0x01)_
.6+h|Content h|Argument h|Length h|Description
|OP Code
|1 byte
|Contains the OP Code of the specified operation.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Total Length = 7 + <Arg2_Length>`.

|Arg1
|1 byte
|The first data argument of this operation.

|Arg2_Length
|1 byte
|Contains the length of the Arg2_Data argument in bytes.

|Arg2_Data
|n byte
|The second data argument of this operation.

h|Behavior
3+|Describes the behavior of a Network FMU and the Bus Simulation in the context of this operation.
_e.g. The specified operation shall be produced by a Network FMU and consumed by the Bus Simulation._

|====

Remarks:

* Numbers shall be transmitted with `little-endian` byte order.
* Since the standard allows to concatenate multiple operations (see <<CommunicationVariable, Tx\Rx Data Variables>>), the <<TotalLengthField, Total Length>> field was introduced to allow the implementation of a generic parser for received operations.

==== NOOP Operation [[NOOP-Operation]]
A special operation of the Layered Standard Bus Protocol is the `NOOP` operation.
This operation is independent from the bus type and shall be returned by networked FMUs if no other operations are pending for transmission.

.Detailed description of the NOOP operation.
[#table-noop-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|NOOP
h|Description
3+|Represents no operation.
h|OP Code [hex]
3+|0x00
.3+h|Content
h|Argument
h|Length
h|Description

|OP Code
|1 byte
|Contains the OP Code of the specified operation.
For this operation the OP Code always has the value 0x00 within all bus types.

|Total Length
|4 byte
|Defines the cumulative length of all arguments in bytes.
For this operation always applies: `Total Length = 5`.

h|Behavior
3+|The specified operation shall be produced and consumed by Network FMUs and the Bus Simulation.

|====

=== Variables [[NetworkAbstractionVariables, Variables]]
This section explains how Layered Standard Bus Protocol operations are sent and received by FMUs using FMI3 clock and clocked variables footnote:[For details, refer to Functional Mock-up Interface Specification (fmi-standard.org) chapter 2.2.8 Clocks.].
While the former (see <<ClockVariableLowCut, Tx\Rx Clock Variables>>) are used for scheduling and time synchronization, the latter (see <<CommunicationVariable, Tx\Rx Data Variables>>) are used to carry the Layered Standard Bus Protocol operations in binary form.
To summarize, four variables with the following name schema are used:

The input variable `BusName::Rx_Data` is clocked by the clock variable `BusName::Rx_Clock`, both with `causality` set to `input`.

The output variable `BusName::Tx_Data` is clocked by the clock variable `BusName::Tx_Clock`, both with `causality` set to `output`.

Both variable pairs must be listed as member of its corresponding <<BUSTerminalLowCut, Bus Terminal>>.
How to set the `BusName` placeholder is bus type specific and therefore described in the bus specific chapters.

==== Tx\Rx Clock Variables [[ClockVariableLowCut]]
As described in the FMI3 specification, Clock variables are used to synchronize events between importer and across FMUs.
Since Clock variables are strictly related to the `Event Mode`, networked FMUs shall set the Co-Simulation attribute `hasEventMode = fmi3True` in the model description file.

For simulating bus communication according to the Network Abstraction, a time-based clock is used for the `Tx_Clock` variable to signal the point in time when layered standard bus operations must be transferred by the importer to the receiver FMUs.
Its up to the implementer to either use a `periodic` or `aperiodic` Clock.

This allows the FMU (or better the exporting tool) to balance the accuracy and performance of its network communication:

 - While aperiodic clocks allow very accurate network simulations, frequently entering `Event Mode` will reduce the network simulation speed.
 - Using periodic clocks and queuing the operations to be transmitted reduces the number of `Event Mode` entries and speeds up the simulation at the cost of simulation accuracy.
 - One could use (structural) parameters to define the accuracy of aperiodic clocks, allowing control of the simulation accuracy and performance with the same FMU.

The input clocks (`Rx_Clock`) shall be triggered clocks.

The importer will then connect and merge output clock activations, even those of different clock types, and forwards them to the input clocks, as required by the network semantics.

#TODO all#: Should we mandate that all output clock types must be the same? Or should we allow the exporter to mix clock types for the different abstraction layers, or even for the different frames? Since different FMUs might use different clock types anyway, an importer needs to handle the mixed case anyway.
Any other reason to be more strict here?
 
===== Bus Communication Points [[bus-communication-points]]
For transferring bus operations from the Tx_Data to the Rx_Data variables, networked FMUs must be synchronous in time.
This point in time is also referred to as the `Bus Communication Point`.
The importer must ensure that networked FMUs hit such points synchronously by calling `fmi3DoStep` with a proper `communicationStepSize` argument.
To determine the `communicationStepSize` for the first simulation step, the importer gets the Tx clock time in `Initialization Mode` as follows: 

* For aperiodic Tx clocks, the importer calls `fmi3GetInterval`.
* For periodic Tx clocks, the importer shall evaluate the clock attributes (e.g. `intervalDecimal`) as defined in the model description.
  If `intervalDecimal` is not defined, the importer shall call `fmi3GetShift`.

Based on the Tx clock intervals received in the `Initialization Mode`, the importer calls `fmi3DoStep` with a determined `communicationStepSize` to reach the next Bus Communication Point.
After returning from `fmi3DoStep`, the importer has to enter the `Event Mode` by calling `fmi3EnterEventMode`.
In `Event Mode` the importer activates the Tx and Rx clock by calling `fmi3SetClock`.
The importer then starts to transfer bus operations from the Tx_Data to the Rx_Data variable (see <<CommunicationVariable>>).

To determine the `communicationStepSize` for the next simulation step, the importer gets the Tx clock time as follows: 

* For aperiodic Tx clocks, the importer calls `fmi3GetInterval`.
* For periodic Tx clocks, the importer shall evaluate the clock attributes as defined in the model description.

If an FMU wants to respond to a received bus operation in the same time step, then `fmi3GetInterval` must return 0.
In this case the importer remains in `Event Mode` and starts a new iteration.
If an FMU does not know the next Tx clock time for any reason, `fmi3GetInterval` shall return with `qualifier = fmi3IntervalNotYetKnown`.

==== Tx\Rx Data Variables [[CommunicationVariable, Communication Variables]]
The Tx\Rx variables are of type `fmi3Binary` and contains one or more bus operations, as sent or receive by the FMU.
The senders can chose how many bus operations are buffered and/or for how long operations are buffered before activating an output clock to trigger the actual sending of these operation.
This allows senders to trade accuracy for speed: buffering more and interrupting the simulation less will lead to faster simulations, but less accurate timing of the network communication.

==== MIME Types
Within FMI, every binary FMI variable has a `mimeType`, which indicates the type of data passed as a binary.
This type indicates which specific bus type is involved.
It ensures that only bus types of the same type can be interconnected, since FMI only allows the connection of two mime types of the same binary variables.
The following table lists the names of MIME types used for the Tx\Rx data variables:

.Overview of the available MIME types for the different supported bus types.
[#table-mime-types]
[cols="4,5",options="header"]
|====
|MIME type name
|Description

|org.fmi-standard.fmi-ls-bus.v1.can
|Binary variables simulating the automotive CAN network including CAN, CAN FD and CAN XL

|org.fmi-standard.fmi-ls-bus.v1.lin
|Binary variables simulating the automotive LIN network

|org.fmi-standard.fmi-ls-bus.v1.flexray
|Binary variables simulating the automotive FlexRay network

|org.fmi-standard.fmi-ls-bus.v1.ethernet
|Binary variables simulating the automotive Ethernet network

|org.fmi-standard.fmi-ls-bus.v1.spi
|Binary variables simulating the automotive SPI network

|====

As in the table above the version of a specified bus type is integrated within the MIME type.
The MIME type and the associated versioning ensure that only compatible bus types can be connected to each other.
The version number marks the set of available operations.
Only the major version is included by the specified MIME type.
The versioning follows the rules of https://semver.org/[Semantic Versioning 2.0.0].

=== Terminal Definitions
This section defines terminals for network abstraction or low cut.

==== Bus Terminal [[BUSTerminalLowCut,bus terminal]]
Each network connected to the FMU must be described in `icons/terminalsAndIcons.xml` as a `<Terminal>` element of `<fmiTerminalsAndIcons><Terminals>`.
The attribute `name` of the `<Terminal>` must match the name of the specified network _[e.g. the name of the can channel: Powertrain]_ within a low cut.
If the specified FMU is connected to more than one network, there shall be exactly one `<Terminal>` for each network.

Attribute definitions::
 * `terminalKind` must be set to `bus`.
 * `matchingRule` must be set to `bus`.
 * `name` is the network name, e.g. `Powertrain`, see <<ExampleLowCut, Example>> and constraints above.

Element definitions::
 * `BusName::Rx_Data` and `BusName::Tx_Data` and their clocks `BusName::Rx_Clock` and `BusName::Tx_Clock` are exposed in the `modelDescription.xml`, they must be listed as `<TerminalMemberVariable>` elements here.
 * There must be no `<TerminalStreamMemberVariable>` element.

The <<#figure-frame-variables-terminals-lowcut, following figure>> shows a FMU with four variables `Tx_Data`, `Tx_Clock`, `Rx_Data`, `Rx_Clock` that are aggregated to a `<Terminal>` named _Bus Terminal_:

.Frame variables and terminals.
[#figure-frame-variables-terminals-lowcut]
image::bus_terminal.svg[width=30%, align="center"]

==== Example [[ExampleLowCut,ExampleLowCut]]
The following excerpts from files are used throughout this document as examples and should illustrate how the different concepts relate.

.Example modelDescription.xml for ECU node
[#modelDescriptionLowCut.xml]
[source, XML]
----
include::examples/X_network4FMI_modelDescription_lowCut.xml[]
----

The following file shows the `<Terminal>` related definition:

.Example terminalsAndIcons.xml file
[#terminalsAndIconLowCut.xml]
[source, XML]
----
include::examples/X_network4FMI_terminalsAndIcons_lowCut.xml[]
----

=== Network Parameters [[NetworkParameters]]
Using structural parameters, FMUs can be parameterized according to importer specifications.
This chapter specifies the structural parameters that each FMU shall provide.
 
#TODO all#: define further parameter names and their semantics influencing bus behavior and/or version of the fmi-ls-bus version (FMU declares them as parameters or structural parameters depending on internal mechanisms)

==== Direct Confirmation Parameter [[direct-confirmation-parameter]]
Within the <<DirectCommunication, Direct Communication>> case the transmission is always positively confirmed by the FMU itself.
Within the <<Composition-with-dedicated-Bus-Simulation-FMU, Composition with dedicated Bus Simulation FMU>> and <<BusFeatureIntegratedFmuSimulator, Importer with Integrated Bus Simulation>> communication use case, the Bus Simulation returns a feedback of a successful or faulty transmission.
Justified by this scenarios the FMU importer shall parameterize the FMUs according to the selected <<SystemCompositions, System Composition>> via the following defined structural parameters:

.FMU parameters for system composition selection by the FMU importer.
[[figure-fmu-system-composition-parameters]]
----
    org.fmi-standard.fmi-ls-bus.DirectConfirmation
        Description:  "Specifies if a transmission is always positively confirmed by the FMU itself"
        Type:         Boolean
        Causality:    structuralParameter
        Variability:  fixed
        Start:        "true"
----

`org.fmi-standard.fmi-ls-bus.DirectConfirmation` shall be set to `True` if a given FMU importer wants to integrate the specified FMUs via the <<DirectCommunication, Direct Communication>> case; otherwise to `False`.

This structural parameter shall only be available for Network FMUs.
A Bus Simulation (FMU) does not require this structural parameter.

=== Example
#TODO dSPACE#: Providing examples

=== Bus Specific Details [[BusTypeSpecificDetails]]
The Network Abstraction ("low cut") defines an abstraction layer for several different bus types, which are supported by this standard.
For every bus types the individual specified <<Overview-Layered-Standard-Bus-Protocol, Layered Standard Bus Protocol>> is taken into account.
This is followed by a concrete description of important bus-specific aspects.
Finally, processes are described in detail with the help of examples and sequence diagrams.

include::4_4_1_can.adoc[]

include::4_4_2_lin.adoc[]

include::4_4_3_flexray.adoc[]

include::4_4_4_ethernet.adoc[]