== Network Abstraction (Low-Cut) [[low-cut]]

This chapter describes the Network Abstraction or Low-Cut in detail.

=== Overview [[low-cut-overview]]

The Network Abstraction allows the implementation of virtual bus drivers within FMUs on the level of the hardware abstraction layer.
Exchanging data in terms of the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> via variables grouped by a dedicated Bus Terminal (see <<low-cut-variables>>), allows the implementation of bus simulations in a wide range from idealized up to detailed behavior, including e.g., timing, arbitration, error, status and other effects.
During simulation, the network communication is controlled by send and receive Bus Operations.
Based on these operations, FMUs implementing this layered standard have to react depending on their role as specified in this document.
This role can be a Bus Simulation FMU or an importer with bus simulation support on one side, and Network FMUs (e.g., virtual ECUs) on the other side (see <<common-concepts-system-compositions, System Compositions>>).
To allow importers an easy distinction between these FMU roles, for Bus Simulation FMUs the attribute `isBusSimulationFMU` shall be set to `true` in the Manifest file.

In general, the Layered Standard Bus Protocol is bus-type-specific, but there are some similarities among different bus types.
Bus communication often follows a `Transmit`/`Confirm` pattern, where a Network FMU sends a `Transmit` operation containing the network message as payload.
Depending on the <<common-concepts-system-compositions, System Composition>>, the importer forwards the `Transmit` operation either directly to receiving FMUs or to a dedicated bus simulation.
The Bus Simulation then might delay the transfer of the `Transmit` operation to the receiving FMUs to simulate timing behavior, before sending a bus-specific `Confirm` operation back to the sending FMU.

.Transmission overview.
[#figure-transmission-overview]
image::images/transmit_messages.svg[width=500]

The point in time at which FMUs will (potentially) send new network messages can be given to the importer in advance with the proper Clock type.
Based on these times, the importer has to calculate the next `communicationStepSize` for all networked FMUs.
For simulating bus communication with timing effects, the FMUs should set the Co-Simulation attribute `canHandleVariableCommunicationStepSize = "true"`.

.Example for network simulation with timing behavior.
[#figure-transmission-example-with-timing-behavior]
image::images/bus_simulation_example.svg[width=800]

For simplification reasons or if a detailed bus simulation is not desired, fixed-step size FMUs can also be used with Network Abstraction.
However, depending on the chosen simulation step-size, delay effects of the bus simulation have to be taken into account.
Compositions with fixed-step size and variable-step size FMUs require the decoupling of the Bus Simulation logic and the Bus Simulation timing.
This decoupling is realized by queuing Tx/Rx Bus Operations inside the Bus Simulation as well as queuing Tx Bus Operations inside Network FMUs.
By queuing Bus Operations, System Compositions with variable-step size FMUs as well as fixed-step size FMUs can be simulated together without affecting each other.

=== Layered Standard Bus Protocol [[low-cut-layered-standard-bus-protocol]]

The Layered Standard Bus Protocol allows the transmission of Bus Operations between FMUs in binary form via Clocks and clocked variables (see <<low-cut-variables>>).
Depending on their role (Network or Bus Simulation), FMUs have to respond to received operations as specified by this layered standard.
Operations and the reaction on receipt are bus-type-specific and therefore described in the bus-specific chapters.
However, the description follows a uniform structure and consists of two parts, an overview table and a detailed description of all operations.

The overview table represents the binary format of operations and is structured as follows:

* OP Code: The operation code defines the unique value of the operation.
It consists of four bytes in length.

[[TotalLengthField]]
* Length: A four byte total data length (OP Code + Length + Arguments) field following the OP Code.
For operation with variable size arguments, the total length can vary in value at runtime.

* Arguments: The arguments of the respective operation.
The number of arguments is defined for each operation within this standard.
For arguments with a variable length, an argument pair composed of length and data is used.

The following table shows an example of an operation definition.
The name is _OperationName_ and has the OP Code 0x01.
The operation has three arguments _Arg1_ (2 bytes long), _Arg2_Length_ (1 byte long), _Arg2_Data_ (_<Arg2Length>_ bytes long), whereby argument 2 and argument 3 form a coherent variable length argument.

.Definition of an operation within the Layered Standard Bus Protocol.
[#table-operation-definition]
[cols="1,1,1,1,1,1"]
|====
.2+h|Operation Type
5+h|Operation Content

h|OP Code
h|Length
3+h|Specific Content

|OperationName
|0x01
|10 + <Arg2_Length>
|1 byte Arg1
|1 byte Arg2_Length
|<Arg2_Length> byte Arg2_Data
|====

Additionally, all operations are described separately in detail in the following structure:

.Operation example within the Layered Standard Bus Protocol.
[#table-operation-definition-example]
[cols="5a,4a,3a,20a"]
|====
h|Name
3+|Name of the operation _(e.g., OperationName)_
h|Description
3+|Contains a description of the specified operation.
h|OP Code [hex]
3+|OP code of the operation _(e.g., 0x01)_
.6+h|Content h|Argument h|Length h|Description
|OP Code
|4 bytes
|Contains the OP Code of the specified operation.

|Length
|4 bytes
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 10 + <Arg2_Length>`.

|Arg1
|1 byte
|The first argument of the operation.

|Arg2_Length
|1 byte
|Contains the length of the Arg2_Data argument in bytes.

|Arg2_Data
|n byte
|The second argument of the operation.

h|Behavior
3+|Describes the behavior of a Network FMU and the Bus Simulation in the context of this operation.

NOTE: E.g., the specified operation shall be produced by a Network FMU and consumed by the Bus Simulation.
|====

Remarks:

* Numbers shall be transmitted with `little-endian` byte order.
* Since the standard allows concatenating multiple operations (see <<low-cut-tx-rx-data-variables, Tx/Rx Data Variables>>), the <<TotalLengthField, Length>> field is introduced to allow the implementation of a generic parser for received operations.

A CAN frame will serve as a concrete <<figure-bus-operation-can-frame-mapping-example, example>>.
Sending a CAN frame is represented by the Bus Operation: CAN Transmit.
Since the FMI-LS-BUS describes the simulation of network communication above the electrical level, not all content of a CAN frame is relevant.
The corresponding argument values ​​do not have to be analogous to those of the original frame representation.
Argument values can be transformed, i.e., presented in a different form, for easier use.
<<figure-bus-operation-can-frame-mapping-example>> illustrates the mapping between the FMI-LS-BUS CAN Transmit Bus Operation and a Standard CAN Data Frame. 
In detail <<figure-bus-operation-can-frame-mapping-example>> shows which information is directly mapped, which is used with transformed values and which information is not required/used.

.Mapping between the FMI-LS-BUS CAN Transmit Bus Operation and a Standard CAN Data Frame.
[#figure-bus-operation-can-frame-mapping-example]
image::images/bus_operation_can_frame_mapping_example.svg[width=650]

==== Format Error [[low-cut-format-error-operation]]

A <<low-cut-format-error-operation, `Format Error`>> operation will be sent by a network participant if a corrupt Bus Operation was received.
A corrupt Bus Operation is an operation that does not match the expected format, e.g. an unknown OP Code or an operation with an invalid length.


.Detailed description of the Format Error operation.
[#table-format-error-operation]
[cols="5,4,3,20"]
|====
h|Name
3+|Format Error
h|Description
3+|Represents a generic format operation error, which can be initiated by every operation.
This error shall be used when generally encountering a problem with the content of an operation.
h|OP Code [hex]
3+|0x01
.5+h|Content
h|Argument
h|Length
h|Description

|OP Code
|4 bytes
|Contains the OP Code of the specified operation.
For this operation, the OP Code always has the value 0x01 within all bus types.

|Length
|4 bytes
|Defines the cumulative length of all arguments in bytes.
The following applies for this operation: `Length = 10 + Length of Data argument in bytes`.

|Data Length
|2 bytes
|Specifies the length of the Data argument in bytes.

|Data
|n byte
|Stores the complete binary data of the operation that caused the specified <<low-cut-format-error-operation, `Format Error`>>.

h|Behavior
3+|The specified operation shall be produced and consumed by Network FMUs and the Bus Simulation.
|====

====  Provided C Implementation [[low-cut-provided-c-implementation]]

To facilitate the implementation of Low Cut FMUs, C header files with implementations for Bus Operations are provided:

* link:headers/fmi3LsBus.h[fmi3LsBus.h] provides general macros, types and structures for common Bus Operations.
These header files apply to all supported bus types of the layered standard.
* link:headers/fmi3LsBusUtil.h[fmi3LsBusUtil.h] provides common utility macros and structures for all supported bus types.
* link:headers/fmi3LsBusCan.h[fmi3LsBusCan.h] provides macros, types and structures of Bus Operations for CAN, CAN FD and CAN XL.
* link:headers/fmi3LsBusUtilCan.h[fmi3LsBusUtilCan.h] provides CAN, CAN FD and CAN XL explicit utility macros.
* link:headers/fmi3LsBusFlexRay.h[fmi3LsBusFlexRay.h] provides macros, types and structures of Bus Operations for FlexRay.
* link:headers/fmi3LsBusUtilFlexRay.h[fmi3LsBusUtilFlexRay.h] provides FlexRay explicit utility macros.
* link:headers/fmi3LsBusEthernet.h[fmi3LsBusEthernet.h] provides macros, types and structures of Bus Operations for Ethernet.
* link:headers/fmi3LsBusUtilEthernet.h[fmi3LsBusUtilEthernet.h] provides Ethernet explicit utility macros.

==== Basic Type Definitions [[low-cut-basic-type-definitions]]

The following basic types are defined for this standard, which apply to all supported buses.
These basic types are used in the bus-specific parts within the operation definitions as operation arguments.

The following values for the boolean basic type are defined:

.Overview of the available boolean values.
[#table-boolean-value-kinds]
[cols="2,1,5"]
|====

h|Boolean h|Value h|Description
|FALSE|0x00|Describes the boolean value: False.
|TRUE|0x01|Describes the boolean value: True.
|====

=== Variables [[low-cut-variables, Variables]]

This section explains how layered standard bus protocol operations are sent and received by FMUs using Clocks and clocked variables footnote:[For details, refer to Functional Mock-up Interface Specification (fmi-standard.org) chapter 2.2.8 Clocks.]. +
While <<low-cut-tx-clocks, Tx Clock>> and <<low-cut-rx-clocks, Rx Clock>> are used for scheduling and time synchronization, <<low-cut-tx-rx-data-variables, Tx/Rx Data Variables>> are used to carry Bus Operations in binary form.

* The `Rx_Data` variable is clocked by the `Rx_Clock` Clock, both with `causality` set to `input`.
* The `Tx_Data` variable is clocked by the `Tx_Clock` Clock.
* The `causality` of the `Tx_Data` variable shall be `output`.
* The `causality` of `Tx_Clock` depends on the selected Clock type (see <<low-cut-tx-time-based-clocks, Tx Clocks>>).

Both variables (and their corresponding Clocks) must be members of its corresponding <<low-cut-bus-terminal, Bus Terminal>>.

==== Tx Clocks [[low-cut-tx-clocks]]

As described in the FMI 3.0 specification, Clocks are used to synchronize events between the importer and across FMUs.

NOTE: Note: The Clock type of `Tx_Clock` can influence the bus simulation significantly - the differences should be taken into account.

===== Time-based Tx Clocks [[low-cut-tx-time-based-clocks]]

For time-based Clocks, the event times are known before a simulation step is started, and the importer can adapt the next `communicationStepSize` for all networked FMUs accordingly.

<<low-cut-communication-points>> illustrates the operating principle of the exchange of Bus Operations using a time-based `Tx_Clock` with `intervalVariability=countdown`.
The network topology is shown on the left part and the corresponding data flow on the right part of the figure.
In this example FMU 1 and FMU 2 are communicating via a Bus Simulation.
Each of them have a <<low-cut-bus-terminal, Bus Terminal>> where the specified Bus Operations are exchanged.
Within the first communication point, FMU 1 announces the time point when it wants to transmit data by setting the interval and the interval qualifier of the `countdown` `Tx_Clock`.
The importer will then call the `fmi3DoStep` functions of the FMUs with a corresponding communication step size to hit the requested time point (second communication point).
In the `Event Mode` the Bus Operation (the clocked binary variable) is then passed from FMU 1 to the Bus Simulation.
The Bus Simulation itself also uses a `countdown` `Tx_Clock` and announces a point in the future at which the Bus Operation should be transmitted to FMU 2.
The interval provided by the Bus Simulation might consider effects of the bus like the actual transmission time, but the interval could even be zero in case of an ideal bus abstraction.
When the corresponding `Tx_Clock` Clock becomes active, the Bus Operation is passed from the Bus Simulation to FMU 2.

.Example Bus Communication Points announced by time-based aperiodic countdown Tx_Clock.
[#low-cut-communication-points]
image::images/low_cut_communication_points.svg[width=1000]

The announced Tx time however does not mean that a Bus Operation really has to be transferred, but that the connected networked FMUs should enter the `Event Mode` at that time.
An importer has to determine proper communication step sizes to synchronize networked FMUs at the announced Tx time.

NOTE: Note: During simulation it can happen that no `Tx_Data` has to be transferred to the `Rx_Data` variable at the announced Tx time. In this case the returned 'valueSize' of the `Tx_Data` variable is 0.

Although the `causality` of a `time-based` `Tx_Clock` and a `triggered` `Rx_Clock` are each `input`, it is allowed to connect both, since a `time-based` Clock of an FMU is considered only to be a request to the importer to provide a corresponding Clock source.

.Consideration of time-base Tx_Clock connections.
[#low-cut-time-based-port-connection]
image::images/low_cut_time_based_port_connection.svg[width=500]

However, because of the common Clock source, both Clocks (`Rx_Clock` and `Tx_Clock`) might get active at the same time.
To make sure that the `Rx_Data` variable is set properly, an importer has to activate the `Rx_Clock` respecting the `Tx_Data` and `Rx_Data` dependency.

NOTE: Note: For clarity, a connecting line between `Tx_Clock` and `Rx_Clock` is always shown in figures of this document.

Network FMUs using a `time-based` `Tx_Clock` should set the Co-Simulation attribute `canHandleVariableCommunicationStepSize = "true"` in the model description file, since `fmi3DoStep` is typically called with variable `communicationStepSize`.

===== Triggered Tx Clocks [[low-cut-tx-triggered-clocks]]

A `triggered` Clock basically allows signalling events when returning from `fmi3DoStep` either by using an `Early Return` or when the requested communication point at latexmath:[t_{i+1}] was reached.
Since signaling `Tx_Clock` events with an early return at latexmath:[t < t_{i+1}] would require to set connected networked FMUs back in time to reach Bus Communication Points synchronously, a `triggered` `Tx_Clock` must only be set when returning from `fmi3DoStep` with the `earlyReturn` argument set to `fmi3False`.
In consequence, Bus Communication Points and regular communication points coincide and take place at the same time.
The time of a Bus Communication Point can therefore not be defined independently, but is given by the importer.
Pending Tx data shall be signaled by returning from `fmi3DoStep` with the `eventHandlingNeeded` arguments set to `fmi3True`.

.Triggered Tx_Clock/Rx_Clock connection.
[#low-cut-triggered-port-connection]
image::images/low_cut_communication_with_triggered_tx_clock.svg[width=1000]

==== Rx Clocks [[low-cut-rx-clocks]]

The input Clocks (`Rx_Clock`) shall be `triggered` Clocks.

==== Tx/Rx Data Variables [[low-cut-tx-rx-data-variables, Communication Variables]]

The `Tx_Data`/`Rx_Data` variables are of type `fmi3Binary` and may contain zero, one or multiple Bus Operations, as sent or received by the FMU.
If no Bus Operations shall be sent by a specified Network FMU at a given Bus Communication Point, the size of the corresponding binary `Tx_Data` variable shall be set to zero.
A sending FMU can choose how many Bus Operations are buffered and/or for how long Bus Operations are buffered before it indicates that the corresponding time based Clock should be activated or the corresponding triggered Clock get triggered.
This allows senders to trade accuracy for speed: Buffering more and interrupting the simulation less will lead to faster simulations, but less accurate timing of the network communication.

==== MIME Types [[low-cut-mime-types]]

Every binary variable has a `mimeType`, which indicates the type of data passed as a binary.
This type indicates which specific bus type is involved.
It ensures that only bus types of the same type can be interconnected, since FMI only allows the connection of two MIME types of the same binary variables.
The following table lists the MIME types to use for the Tx/Rx data variables within a <<low-cut-bus-terminal, Bus Terminal>>:

.Overview of the available MIME types for the supported bus types.
[#table-mime-types]
[cols="4,3",options="header"]
|====
|MIME type
|Description

|application/org.fmi-standard.fmi-ls-bus.can; version="1.0.0"
|Binary variables simulating a CAN network including CAN, CAN FD and CAN XL

|application/org.fmi-standard.fmi-ls-bus.lin; version="1.0.0-alpha.1"
|Binary variables simulating a LIN network

|application/org.fmi-standard.fmi-ls-bus.flexray; version="1.0.0-beta.1"
|Binary variables simulating a FlexRay network

|application/org.fmi-standard.fmi-ls-bus.ethernet; version="1.0.0-alpha.2"
|Binary variables simulating an Ethernet network
|====

The version of a bus type is defined in the `version` parameter of the MIME type.
The MIME type and the associated versioning help importers to detect incompatible bus types.
The version number marks the set of available operations for a specified bus type.
The versioning follows the rules of semantic versioning, as defined in <<PW13>>.

=== Terminal Definitions [[low-cut-terminal-definitions]]

A schematic representation of an FMU with a Bus Terminal is shown in the <<#figure-frame-variables-terminals-lowcut, following figure>>:

.Frame variables and terminals.
[#figure-frame-variables-terminals-lowcut]
image::images/bus_terminal.svg[width=300]

==== Bus Terminal [[low-cut-bus-terminal,Bus Terminal]]

Each network connected to the FMU must be described in `terminalsAndIcons/terminalsAndIcons.xml` as a `<Terminal>` element of `<fmiTerminalsAndIcons><Terminals>`.
There shall be exactly one `<Terminal>` element for each network of the FMU.

Attributes of a Bus Terminal::
 * `terminalKind` must be `org.fmi-ls-bus.network-terminal`.
 * `matchingRule` must be `org.fmi-ls-bus.transceiver`. +
Terminal member variables with memberName `Tx_{Data|Clock}` variables shall be connected to Terminal member variables with memberName `Rx_{Data|Clock}`, and vice versa. +
The variable type shall be equal.
 * `name` should be the network name, e.g., "Powertrain", see <<example-terminalsAndIconLowCut-xml, example>>.

Elements of a Bus Terminal::
 * A Bus Terminal shall contain four `<TerminalMemberVariable>` elements with the following `memberName` attributes: +
`Tx_Data`, `Tx_Clock`, `Rx_Data` and `Rx_Clock`. +
The `memberName` attribute is used to define the role of the referred variable in the Bus Terminal. +
The `variableKind` of these four members must be `signal`.
 * The use of the same variable within different Bus Terminals is not allowed.
 * Bus systems can add specific configuration parameters in a nested <<low-cut-configuration-terminal,Configuration Terminal>>. +
Empty Configuration Terminals can be omitted.

===== Configuration Terminal [[low-cut-configuration-terminal, Configuration Terminal]]

Within Configuration Terminals, bus-specific configuration parameters are defined.
A Configuration Terminal satisfies the following definition:

Attributes of the nested Configuration Terminal::
 * `name` must be "Configuration".
 * `terminalKind` must be `org.fmi-ls-bus.network-terminal.configuration`.
 * `matchingRule` must be `bus`.

==== Grouping of Bus Terminals [[low-cut-grouping-of-bus-terminals]]

In problem-specific domains, it may be useful to group several Bus Terminal elements semantically.
This grouping is also done using terminals.
The grouping can be done at any nesting depth.
Grouping can generally be used for all bus types of Network Abstraction.
Depending on the bus-specific definition, buses can introduce special terminal kinds for grouping of Bus Terminals to give them more semantics and to use their functionality.

Attributes of the Grouping Terminal::
 * `terminalKind` may be explicitly defined by a specific bus to give more meaning to a respective group of Bus Terminals; otherwise not set.
 * `matchingRule` must be `none`.

Elements of a Grouping Terminal::
 * The `<Terminal>` element shall contain the desired number of <<low-cut-bus-terminal, Bus Terminal>> elements. 

==== Example [[low-cut-example]]

The following excerpts from files are used throughout this document as examples and illustrate how the different concepts relate.

.Example modelDescription.xml for ECU node.
[[example-modelDescriptionLowCut-xml]]
[source, XML]
----
include::examples/X_network4FMI_modelDescription_lowCut.xml[]
----

The following file shows the <<low-cut-bus-terminal, Bus Terminal>>-related definition:

.Example terminalsAndIcons.xml file.
[[example-terminalsAndIconLowCut-xml]]
[source, XML]
----
include::examples/X_network4FMI_terminalsAndIcons_lowCut.xml[]
----

=== Bus-Specific Details [[low-cut-bus-specific-details]]

For each supported bus type, the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> is defined.
This chapter describes the operations of the <<low-cut-layered-standard-bus-protocol, Layered Standard Bus Protocol>> to enable the simulation of supported bus types.

include::4_4_1_can.adoc[]

include::4_4_2_lin.adoc[]

include::4_4_3_flexray.adoc[]

include::4_4_4_ethernet.adoc[]
